/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const WorldclockIndexLazyRouteImport = createFileRoute('/worldclock/')()
const TimerIndexLazyRouteImport = createFileRoute('/timer/')()
const StopwatchIndexLazyRouteImport = createFileRoute('/stopwatch/')()
const AlarmIndexLazyRouteImport = createFileRoute('/alarm/')()
const WorldclockClockIdIndexLazyRouteImport = createFileRoute(
  '/worldclock/$clockId/',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const WorldclockIndexLazyRoute = WorldclockIndexLazyRouteImport.update({
  id: '/worldclock/',
  path: '/worldclock/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/worldclock/index.lazy').then((d) => d.Route),
)
const TimerIndexLazyRoute = TimerIndexLazyRouteImport.update({
  id: '/timer/',
  path: '/timer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timer/index.lazy').then((d) => d.Route))
const StopwatchIndexLazyRoute = StopwatchIndexLazyRouteImport.update({
  id: '/stopwatch/',
  path: '/stopwatch/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/stopwatch/index.lazy').then((d) => d.Route),
)
const AlarmIndexLazyRoute = AlarmIndexLazyRouteImport.update({
  id: '/alarm/',
  path: '/alarm/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alarm/index.lazy').then((d) => d.Route))
const WorldclockClockIdIndexLazyRoute =
  WorldclockClockIdIndexLazyRouteImport.update({
    id: '/worldclock/$clockId/',
    path: '/worldclock/$clockId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/worldclock/$clockId/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/alarm': typeof AlarmIndexLazyRoute
  '/stopwatch': typeof StopwatchIndexLazyRoute
  '/timer': typeof TimerIndexLazyRoute
  '/worldclock': typeof WorldclockIndexLazyRoute
  '/worldclock/$clockId': typeof WorldclockClockIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/alarm': typeof AlarmIndexLazyRoute
  '/stopwatch': typeof StopwatchIndexLazyRoute
  '/timer': typeof TimerIndexLazyRoute
  '/worldclock': typeof WorldclockIndexLazyRoute
  '/worldclock/$clockId': typeof WorldclockClockIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/alarm/': typeof AlarmIndexLazyRoute
  '/stopwatch/': typeof StopwatchIndexLazyRoute
  '/timer/': typeof TimerIndexLazyRoute
  '/worldclock/': typeof WorldclockIndexLazyRoute
  '/worldclock/$clockId/': typeof WorldclockClockIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarm'
    | '/stopwatch'
    | '/timer'
    | '/worldclock'
    | '/worldclock/$clockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarm'
    | '/stopwatch'
    | '/timer'
    | '/worldclock'
    | '/worldclock/$clockId'
  id:
    | '__root__'
    | '/'
    | '/alarm/'
    | '/stopwatch/'
    | '/timer/'
    | '/worldclock/'
    | '/worldclock/$clockId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlarmIndexLazyRoute: typeof AlarmIndexLazyRoute
  StopwatchIndexLazyRoute: typeof StopwatchIndexLazyRoute
  TimerIndexLazyRoute: typeof TimerIndexLazyRoute
  WorldclockIndexLazyRoute: typeof WorldclockIndexLazyRoute
  WorldclockClockIdIndexLazyRoute: typeof WorldclockClockIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worldclock/': {
      id: '/worldclock/'
      path: '/worldclock'
      fullPath: '/worldclock'
      preLoaderRoute: typeof WorldclockIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer/': {
      id: '/timer/'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch/': {
      id: '/stopwatch/'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarm/': {
      id: '/alarm/'
      path: '/alarm'
      fullPath: '/alarm'
      preLoaderRoute: typeof AlarmIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worldclock/$clockId/': {
      id: '/worldclock/$clockId/'
      path: '/worldclock/$clockId'
      fullPath: '/worldclock/$clockId'
      preLoaderRoute: typeof WorldclockClockIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlarmIndexLazyRoute: AlarmIndexLazyRoute,
  StopwatchIndexLazyRoute: StopwatchIndexLazyRoute,
  TimerIndexLazyRoute: TimerIndexLazyRoute,
  WorldclockIndexLazyRoute: WorldclockIndexLazyRoute,
  WorldclockClockIdIndexLazyRoute: WorldclockClockIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
