// wjdlz/NOTE: GENERATE BY vx/scripts/apps/config-mocks.ts DO NOT EDIT THIS FILE DIRECTLY

const app = require('./app')
const port = process.env.V_MOCK_PORT || 3030
const name = process.env.V_MOCK_APP_NAME || 'vx-app-mock'

app.listen(port, () =>
  console.log(`[INFO] ${name} | server is running | http://localhost:${port}`)
)
