/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as llmsLlmsFullDottxtRouteImport } from './routes/(llms)/llms-full[.]txt'
import { Route as llmsLlmsDottxtRouteImport } from './routes/(llms)/llms[.]txt'
import { Route as ApiHeartbeatRouteRouteImport } from './routes/api/heartbeat/route'
import { Route as ApiPulseRouteRouteImport } from './routes/api/pulse/route'
import { Route as ApiSearchRouteRouteImport } from './routes/api/search/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125DocsSplatRouteImport } from './routes/{-$lang}/docs/$'
import { Route as Char123LangChar125DocsChar123Char125DotmdRouteImport } from './routes/{-$lang}/docs/{$}[.]md'
import { Route as Char123LangChar125UiDocsSplatRouteImport } from './routes/{-$lang}/ui-docs/$'
import { Route as Char123LangChar125UiNotebookSplatRouteImport } from './routes/{-$lang}/ui-notebook/$'

const Char123LangChar125ProLazyRouteImport = createFileRoute('/{-$lang}/pro')()

const llmsLlmsFullDottxtRoute = llmsLlmsFullDottxtRouteImport.update({
  id: '/(llms)/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const llmsLlmsDottxtRoute = llmsLlmsDottxtRouteImport.update({
  id: '/(llms)/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeartbeatRouteRoute = ApiHeartbeatRouteRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRouteRoute = ApiPulseRouteRouteImport.update({
  id: '/api/pulse',
  path: '/api/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRouteRoute = ApiSearchRouteRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125ProLazyRoute =
  Char123LangChar125ProLazyRouteImport.update({
    id: '/{-$lang}/pro',
    path: '/{-$lang}/pro',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/{-$lang}/pro.lazy').then((d) => d.Route),
  )
const Char123LangChar125DocsSplatRoute =
  Char123LangChar125DocsSplatRouteImport.update({
    id: '/{-$lang}/docs/$',
    path: '/{-$lang}/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125DocsChar123Char125DotmdRoute =
  Char123LangChar125DocsChar123Char125DotmdRouteImport.update({
    id: '/{-$lang}/docs/{$}.md',
    path: '/{-$lang}/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125UiDocsSplatRoute =
  Char123LangChar125UiDocsSplatRouteImport.update({
    id: '/{-$lang}/ui-docs/$',
    path: '/{-$lang}/ui-docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125UiNotebookSplatRoute =
  Char123LangChar125UiNotebookSplatRouteImport.update({
    id: '/{-$lang}/ui-notebook/$',
    path: '/{-$lang}/ui-notebook/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRouteRoute
  '/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/llms.txt': typeof llmsLlmsDottxtRoute
  '/{-$lang}/pro': typeof Char123LangChar125ProLazyRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
  '/{-$lang}/ui-docs/$': typeof Char123LangChar125UiDocsSplatRoute
  '/{-$lang}/ui-notebook/$': typeof Char123LangChar125UiNotebookSplatRoute
}
export interface FileRoutesByTo {
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRouteRoute
  '/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/llms.txt': typeof llmsLlmsDottxtRoute
  '/{-$lang}/pro': typeof Char123LangChar125ProLazyRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
  '/{-$lang}/ui-docs/$': typeof Char123LangChar125UiDocsSplatRoute
  '/{-$lang}/ui-notebook/$': typeof Char123LangChar125UiNotebookSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRouteRoute
  '/(llms)/llms-full.txt': typeof llmsLlmsFullDottxtRoute
  '/(llms)/llms.txt': typeof llmsLlmsDottxtRoute
  '/{-$lang}/pro': typeof Char123LangChar125ProLazyRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
  '/{-$lang}/ui-docs/$': typeof Char123LangChar125UiDocsSplatRoute
  '/{-$lang}/ui-notebook/$': typeof Char123LangChar125UiNotebookSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{-$lang}/pro'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
    | '/{-$lang}/ui-docs/$'
    | '/{-$lang}/ui-notebook/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{-$lang}/pro'
    | '/{-$lang}'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
    | '/{-$lang}/ui-docs/$'
    | '/{-$lang}/ui-notebook/$'
  id:
    | '__root__'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/(llms)/llms-full.txt'
    | '/(llms)/llms.txt'
    | '/{-$lang}/pro'
    | '/{-$lang}/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
    | '/{-$lang}/ui-docs/$'
    | '/{-$lang}/ui-notebook/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiHeartbeatRouteRoute: typeof ApiHeartbeatRouteRoute
  ApiPulseRouteRoute: typeof ApiPulseRouteRoute
  ApiSearchRouteRoute: typeof ApiSearchRouteRoute
  llmsLlmsFullDottxtRoute: typeof llmsLlmsFullDottxtRoute
  llmsLlmsDottxtRoute: typeof llmsLlmsDottxtRoute
  Char123LangChar125ProLazyRoute: typeof Char123LangChar125ProLazyRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125DocsSplatRoute: typeof Char123LangChar125DocsSplatRoute
  Char123LangChar125DocsChar123Char125DotmdRoute: typeof Char123LangChar125DocsChar123Char125DotmdRoute
  Char123LangChar125UiDocsSplatRoute: typeof Char123LangChar125UiDocsSplatRoute
  Char123LangChar125UiNotebookSplatRoute: typeof Char123LangChar125UiNotebookSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(llms)/llms-full.txt': {
      id: '/(llms)/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof llmsLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(llms)/llms.txt': {
      id: '/(llms)/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof llmsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse': {
      id: '/api/pulse'
      path: '/api/pulse'
      fullPath: '/api/pulse'
      preLoaderRoute: typeof ApiPulseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/pro': {
      id: '/{-$lang}/pro'
      path: '/{-$lang}/pro'
      fullPath: '/{-$lang}/pro'
      preLoaderRoute: typeof Char123LangChar125ProLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/$': {
      id: '/{-$lang}/docs/$'
      path: '/{-$lang}/docs/$'
      fullPath: '/{-$lang}/docs/$'
      preLoaderRoute: typeof Char123LangChar125DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/{$}.md': {
      id: '/{-$lang}/docs/{$}.md'
      path: '/{-$lang}/docs/{$}.md'
      fullPath: '/{-$lang}/docs/{$}.md'
      preLoaderRoute: typeof Char123LangChar125DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/ui-docs/$': {
      id: '/{-$lang}/ui-docs/$'
      path: '/{-$lang}/ui-docs/$'
      fullPath: '/{-$lang}/ui-docs/$'
      preLoaderRoute: typeof Char123LangChar125UiDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/ui-notebook/$': {
      id: '/{-$lang}/ui-notebook/$'
      path: '/{-$lang}/ui-notebook/$'
      fullPath: '/{-$lang}/ui-notebook/$'
      preLoaderRoute: typeof Char123LangChar125UiNotebookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiHeartbeatRouteRoute: ApiHeartbeatRouteRoute,
  ApiPulseRouteRoute: ApiPulseRouteRoute,
  ApiSearchRouteRoute: ApiSearchRouteRoute,
  llmsLlmsFullDottxtRoute: llmsLlmsFullDottxtRoute,
  llmsLlmsDottxtRoute: llmsLlmsDottxtRoute,
  Char123LangChar125ProLazyRoute: Char123LangChar125ProLazyRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125DocsSplatRoute: Char123LangChar125DocsSplatRoute,
  Char123LangChar125DocsChar123Char125DotmdRoute:
    Char123LangChar125DocsChar123Char125DotmdRoute,
  Char123LangChar125UiDocsSplatRoute: Char123LangChar125UiDocsSplatRoute,
  Char123LangChar125UiNotebookSplatRoute:
    Char123LangChar125UiNotebookSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
