/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiHeartbeatRouteRouteImport } from './routes/api/heartbeat/route'
import { Route as ApiPulseRouteRouteImport } from './routes/api/pulse/route'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as UiDocsSplatRouteImport } from './routes/ui-docs/$'
import { Route as UiNotebookSplatRouteImport } from './routes/ui-notebook/$'
import { Route as Char123LangChar125DocsSplatRouteImport } from './routes/{-$lang}/docs/$'
import { Route as Char123LangChar125DocsChar123Char125DotmdRouteImport } from './routes/{-$lang}/docs/{$}[.]md'

const ProLazyRouteImport = createFileRoute('/pro')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProLazyRoute = ProLazyRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pro.lazy').then((d) => d.Route))
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeartbeatRouteRoute = ApiHeartbeatRouteRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRouteRoute = ApiPulseRouteRouteImport.update({
  id: '/api/pulse',
  path: '/api/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDocsSplatRoute = UiDocsSplatRouteImport.update({
  id: '/ui-docs/$',
  path: '/ui-docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UiNotebookSplatRoute = UiNotebookSplatRouteImport.update({
  id: '/ui-notebook/$',
  path: '/ui-notebook/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125DocsSplatRoute =
  Char123LangChar125DocsSplatRouteImport.update({
    id: '/{-$lang}/docs/$',
    path: '/{-$lang}/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125DocsChar123Char125DotmdRoute =
  Char123LangChar125DocsChar123Char125DotmdRouteImport.update({
    id: '/{-$lang}/docs/{$}.md',
    path: '/{-$lang}/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro': typeof ProLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRoute
  '/ui-docs/$': typeof UiDocsSplatRoute
  '/ui-notebook/$': typeof UiNotebookSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro': typeof ProLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRoute
  '/ui-docs/$': typeof UiDocsSplatRoute
  '/ui-notebook/$': typeof UiNotebookSplatRoute
  '/$lang': typeof LangIndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pro': typeof ProLazyRoute
  '/api/heartbeat': typeof ApiHeartbeatRouteRoute
  '/api/pulse': typeof ApiPulseRouteRoute
  '/api/search': typeof ApiSearchRoute
  '/ui-docs/$': typeof UiDocsSplatRoute
  '/ui-notebook/$': typeof UiNotebookSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/{-$lang}/docs/$': typeof Char123LangChar125DocsSplatRoute
  '/{-$lang}/docs/{$}.md': typeof Char123LangChar125DocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pro'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/ui-docs/$'
    | '/ui-notebook/$'
    | '/$lang/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pro'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/ui-docs/$'
    | '/ui-notebook/$'
    | '/$lang'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/pro'
    | '/api/heartbeat'
    | '/api/pulse'
    | '/api/search'
    | '/ui-docs/$'
    | '/ui-notebook/$'
    | '/$lang/'
    | '/{-$lang}/docs/$'
    | '/{-$lang}/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProLazyRoute: typeof ProLazyRoute
  ApiHeartbeatRouteRoute: typeof ApiHeartbeatRouteRoute
  ApiPulseRouteRoute: typeof ApiPulseRouteRoute
  ApiSearchRoute: typeof ApiSearchRoute
  UiDocsSplatRoute: typeof UiDocsSplatRoute
  UiNotebookSplatRoute: typeof UiNotebookSplatRoute
  LangIndexRoute: typeof LangIndexRoute
  Char123LangChar125DocsSplatRoute: typeof Char123LangChar125DocsSplatRoute
  Char123LangChar125DocsChar123Char125DotmdRoute: typeof Char123LangChar125DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse': {
      id: '/api/pulse'
      path: '/api/pulse'
      fullPath: '/api/pulse'
      preLoaderRoute: typeof ApiPulseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-docs/$': {
      id: '/ui-docs/$'
      path: '/ui-docs/$'
      fullPath: '/ui-docs/$'
      preLoaderRoute: typeof UiDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-notebook/$': {
      id: '/ui-notebook/$'
      path: '/ui-notebook/$'
      fullPath: '/ui-notebook/$'
      preLoaderRoute: typeof UiNotebookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/$': {
      id: '/{-$lang}/docs/$'
      path: '/{-$lang}/docs/$'
      fullPath: '/{-$lang}/docs/$'
      preLoaderRoute: typeof Char123LangChar125DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/docs/{$}.md': {
      id: '/{-$lang}/docs/{$}.md'
      path: '/{-$lang}/docs/{$}.md'
      fullPath: '/{-$lang}/docs/{$}.md'
      preLoaderRoute: typeof Char123LangChar125DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProLazyRoute: ProLazyRoute,
  ApiHeartbeatRouteRoute: ApiHeartbeatRouteRoute,
  ApiPulseRouteRoute: ApiPulseRouteRoute,
  ApiSearchRoute: ApiSearchRoute,
  UiDocsSplatRoute: UiDocsSplatRoute,
  UiNotebookSplatRoute: UiNotebookSplatRoute,
  LangIndexRoute: LangIndexRoute,
  Char123LangChar125DocsSplatRoute: Char123LangChar125DocsSplatRoute,
  Char123LangChar125DocsChar123Char125DotmdRoute:
    Char123LangChar125DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
