export const tableStyles = {
  wrapper: 'h-full w-full sm:p-2',
  topBarContainer: 'mb-[18px] flex items-center justify-between gap-4',
  topBarLeft: 'flex sm:items-center flex-row justify-between  gap-4 sm:gap-2',
  topBarLeftInner: 'flex items-center gap-2',
  membersText: 'text-default-700 text-base font-medium',
  chip: 'text-default-500 flex items-center',
  selectedActionsContainer: 'flex items-center gap-2',
  divider: 'hidden h-5 sm:flex',
  selectedCountText: 'text-default-800 text-sm whitespace-nowrap',
  actionButton: 'min-w-[5px] min-h-[5px]',
  selectedActions: 'min-w-[25px] min-h-[25px]',
  selectedActionsButton: 'bg-default-100 text-default-800 hidden sm:flex',
  selectedActionsMoreButton: 'text-default-400 sm:hidden ',
  dropdownIcon: 'text-default-400',
  topBarRight: 'flex items-center',
  searchContainer: 'flex items-center',
  searchButton:
    'bg-default-100 hover:bg-default-200 flex h-8 w-8 items-center justify-center rounded-full transition-colors',
  searchInput: 'mr-2',
  searchCloseIcon: 'text-default-400',
  filterSortButtons: 'hidden sm:block',
  filterSortButton: 'bg-default-100 text-default-800',
  filterSortIcon: 'text-default-400',
  popoverContent: 'h-50 w-50 overflow-y-auto',
  filterPopoverContent: 'flex w-full flex-col gap-6 px-2 py-5',
  mobileActions: 'sm:hidden',
  mobileActionsButton: 'text-default-400',
  mobileFilterButton: 'text-default-700 -ml-2 justify-start',
  table: {
    td: 'before:bg-transparent',
    sortIcon: 'ml-1 text-default-400',
    // sortIconHover: 'opacity-0 group-hover:opacity-100 transition-opacity',
    headerContent: 'w-full flex justify-between items-center'
  },
  // Changed to justify-between
  tableHeader: 'flex items-center ',
  tableHeaderUser: 'flex w-full  items-center justify-center ',
  tableHeaderInfo: 'flex  items-center justify-between',
  sortIcon: 'text-default-400',
  cell: {
    userInfoName: 'text-default-foreground',
    userInfoDescription: 'text-default-500',
    lastLoginContainer: 'flex items-center gap-1',
    lastLoginIcon: 'text-default-300 h-[16px] w-[16px]',
    lastLoginText: 'text-small text-default-foreground text-nowrap capitalize',
    statusContainer:
      'bg-default-100 flex w-fit items-center gap-[2px] rounded-lg px-2 py-1',
    statusText: 'text-default-800 px-1',
    actionsContainer: 'flex items-center justify-end',
    actionIcon: 'text-default-400 cursor-pointer',
    actionDropdownButton: 'text-default-400',
    copyButton: 'cursor-pointer hover:text-primary-500 transition-colors'
  },
  paginationContainer: 'flex w-full items-center  justify-between gap-2  py-4',
  paginationButtonContainer: 'gap-2 items-center flex',
  tableSectionContainer: 'flex items-start justify-between',
  tableWrapper: 'w-full',
  tableCard: 'sm:border-default-200 mt-4 sm:border bg-transparent'
}
