/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as FolderRouteRouteImport } from './routes/$folder/route'
import { Route as IndexRouteImport } from './routes/index'

const FolderIndexLazyRouteImport = createFileRoute('/$folder/')()
const FolderEmailIdIndexLazyRouteImport =
  createFileRoute('/$folder/$emailId/')()

const FolderRouteRoute = FolderRouteRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderIndexLazyRoute = FolderIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FolderRouteRoute,
} as any).lazy(() => import('./routes/$folder/index.lazy').then((d) => d.Route))
const FolderEmailIdIndexLazyRoute = FolderEmailIdIndexLazyRouteImport.update({
  id: '/$emailId/',
  path: '/$emailId/',
  getParentRoute: () => FolderRouteRoute,
} as any).lazy(() =>
  import('./routes/$folder/$emailId/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$folder': typeof FolderRouteRouteWithChildren
  '/$folder/': typeof FolderIndexLazyRoute
  '/$folder/$emailId/': typeof FolderEmailIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$folder': typeof FolderIndexLazyRoute
  '/$folder/$emailId': typeof FolderEmailIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$folder': typeof FolderRouteRouteWithChildren
  '/$folder/': typeof FolderIndexLazyRoute
  '/$folder/$emailId/': typeof FolderEmailIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$folder' | '/$folder/' | '/$folder/$emailId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$folder' | '/$folder/$emailId'
  id: '__root__' | '/' | '/$folder' | '/$folder/' | '/$folder/$emailId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderRouteRoute: typeof FolderRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$folder': {
      id: '/$folder'
      path: '/$folder'
      fullPath: '/$folder'
      preLoaderRoute: typeof FolderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folder/': {
      id: '/$folder/'
      path: '/'
      fullPath: '/$folder/'
      preLoaderRoute: typeof FolderIndexLazyRouteImport
      parentRoute: typeof FolderRouteRoute
    }
    '/$folder/$emailId/': {
      id: '/$folder/$emailId/'
      path: '/$emailId'
      fullPath: '/$folder/$emailId/'
      preLoaderRoute: typeof FolderEmailIdIndexLazyRouteImport
      parentRoute: typeof FolderRouteRoute
    }
  }
}

interface FolderRouteRouteChildren {
  FolderIndexLazyRoute: typeof FolderIndexLazyRoute
  FolderEmailIdIndexLazyRoute: typeof FolderEmailIdIndexLazyRoute
}

const FolderRouteRouteChildren: FolderRouteRouteChildren = {
  FolderIndexLazyRoute: FolderIndexLazyRoute,
  FolderEmailIdIndexLazyRoute: FolderEmailIdIndexLazyRoute,
}

const FolderRouteRouteWithChildren = FolderRouteRoute._addFileChildren(
  FolderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderRouteRoute: FolderRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
