/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FolderRouteRouteImport } from './routes/$folder/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FolderIndexRouteImport } from './routes/$folder/index'
import { Route as FolderEmailIdIndexRouteImport } from './routes/$folder/$emailId/index'

const FolderRouteRoute = FolderRouteRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderIndexRoute = FolderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FolderRouteRoute,
} as any)
const FolderEmailIdIndexRoute = FolderEmailIdIndexRouteImport.update({
  id: '/$emailId/',
  path: '/$emailId/',
  getParentRoute: () => FolderRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$folder': typeof FolderRouteRouteWithChildren
  '/$folder/': typeof FolderIndexRoute
  '/$folder/$emailId/': typeof FolderEmailIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$folder': typeof FolderIndexRoute
  '/$folder/$emailId': typeof FolderEmailIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$folder': typeof FolderRouteRouteWithChildren
  '/$folder/': typeof FolderIndexRoute
  '/$folder/$emailId/': typeof FolderEmailIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$folder' | '/$folder/' | '/$folder/$emailId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$folder' | '/$folder/$emailId'
  id: '__root__' | '/' | '/$folder' | '/$folder/' | '/$folder/$emailId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderRouteRoute: typeof FolderRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$folder': {
      id: '/$folder'
      path: '/$folder'
      fullPath: '/$folder'
      preLoaderRoute: typeof FolderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folder/': {
      id: '/$folder/'
      path: '/'
      fullPath: '/$folder/'
      preLoaderRoute: typeof FolderIndexRouteImport
      parentRoute: typeof FolderRouteRoute
    }
    '/$folder/$emailId/': {
      id: '/$folder/$emailId/'
      path: '/$emailId'
      fullPath: '/$folder/$emailId/'
      preLoaderRoute: typeof FolderEmailIdIndexRouteImport
      parentRoute: typeof FolderRouteRoute
    }
  }
}

interface FolderRouteRouteChildren {
  FolderIndexRoute: typeof FolderIndexRoute
  FolderEmailIdIndexRoute: typeof FolderEmailIdIndexRoute
}

const FolderRouteRouteChildren: FolderRouteRouteChildren = {
  FolderIndexRoute: FolderIndexRoute,
  FolderEmailIdIndexRoute: FolderEmailIdIndexRoute,
}

const FolderRouteRouteWithChildren = FolderRouteRoute._addFileChildren(
  FolderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderRouteRoute: FolderRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
