import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

import { generateMetadata, getMetadataFiles } from './index.ts'

const config: Parameters<typeof getMetadataFiles>[0] = {
  framework: 'tanstack',
  core: {
    id: 'test',
    name: 'Test',
    shortName: 'Test',
    version: '1',
    description: 'Test app',
    publisher: { name: 'Test', url: 'https://example.com' },
    url: 'https://example.com'
  },
  branding: { themeColor: '#000', backgroundColor: '#fff' },
  pwa: {
    display: 'standalone',
    orientation: 'any',
    scope: '/',
    startUrl: '/',
    categories: [],
    icons: [],
    screenshots: [],
    shortcuts: []
  },
  metadata: {
    title: 'Test',
    keywords: [],
    theme: {
      lightColor: '#fff',
      darkColor: '#000',
      lightBackgroundColor: '#fff',
      darkBackgroundColor: '#000'
    },
    platforms: {
      apple: {
        mobileWebAppCapable: true,
        webAppCapable: true,
        touchIcon: '/icon.png',
        startupImages: []
      },
      microsoft: { startUrl: '/' }
    },
    social: {
      openGraph: { type: 'website' },
      twitter: { creator: '@test', site: '@test', card: 'summary' }
    }
  }
}

const generatedModule = (i18n?: typeof config.i18n) => {
  const generated = getMetadataFiles({ ...config, i18n }).find(file =>
    file.path.endsWith('/src/generated/vx.ts')
  )

  if (!generated) throw new Error('Expected the generated Vx metadata module')

  return generated.content
}

const generatedPage = (name: 'offline.html' | '404.html') => {
  const page = getMetadataFiles(config).find(file => file.path.endsWith(name))

  if (!page) throw new Error(`Expected generated ${name}`)

  return page.content
}

describe('generated language metadata', () => {
  it('defaults both metadata and i18n to English when omitted', () => {
    const source = generatedModule()
    expect(source.match(/"defaultLanguage": "en"/g)).toHaveLength(2)
    expect(source.match(/"languages": \[\s*"en"\s*\]/g)).toHaveLength(2)
    expect(source).not.toContain('vxI18n = undefined')
    expect(source).toContain(
      'export type Locale = (typeof vxI18n.languages)[number]'
    )
  })

  it('preserves the configured default and supported languages', () => {
    const source = generatedModule({
      defaultLanguage: 'ta',
      languages: ['en', 'ta']
    })
    expect(source.match(/"defaultLanguage": "ta"/g)).toHaveLength(2)
    expect(source.match(/"languages": \[\s*"en",\s*"ta"\s*\]/g)).toHaveLength(2)
  })

  it('adds a configured default language to the supported languages', () => {
    const source = generatedModule({ defaultLanguage: 'ta', languages: ['en'] })
    expect(source.match(/"languages": \[\s*"en",\s*"ta"\s*\]/g)).toHaveLength(2)
  })
})

describe('generated metadata pages', () => {
  it('renders page templates with escaped application values', () => {
    const page = generatedPage('offline.html')

    expect(page).toContain('<title>Offline | Test</title>')
    expect(page).toContain('<!-- Generated by Vx metadata. DO NOT EDIT. -->')
    expect(page).toContain(
      '          <img\n            class="vx-offline__image"\n            src='
    )
    expect(page).toContain('content="Test"')
    expect(page).not.toContain('{{')
  })
})

describe('metadata output ownership', () => {
  it('preserves app-owned edits during generation', () => {
    const projectRoot = mkdtempSync(path.join(tmpdir(), 'vx-metadata-'))
    try {
      writeFileSync(
        path.join(projectRoot, 'vx.app.json'),
        JSON.stringify(config)
      )
      writeFileSync(path.join(projectRoot, '.env'), 'PORT=4321\n')
      writeFileSync(
        path.join(projectRoot, 'index.html'),
        '<html>\n<head>\n\n</head>\n<body><div id="custom-root"></div></body></html>'
      )
      const generated = generateMetadata({ projectRoot })
      expect(generated).toContain(path.join(projectRoot, '.env'))
      expect(generated).toContain(path.join(projectRoot, 'index.html'))
      expect(readFileSync(path.join(projectRoot, '.env'), 'utf8')).toContain(
        'PORT=4321'
      )
      expect(
        readFileSync(path.join(projectRoot, 'index.html'), 'utf8')
      ).toContain('<div id="custom-root"></div>')
      writeFileSync(path.join(projectRoot, '.env'), 'PORT=4567\n')
      generateMetadata({ projectRoot })
      expect(readFileSync(path.join(projectRoot, '.env'), 'utf8')).toContain(
        'PORT=4567'
      )
    } finally {
      rmSync(projectRoot, { recursive: true, force: true })
    }
  })
})

it.each(['vite', 'tanstack', 'tanstack-docs', 'next'] as const)(
  'limits exports for %s',
  framework => {
    const generated = getMetadataFiles({ ...config, framework }).find(file =>
      file.path.endsWith('/src/generated/vx.ts')
    )
    if (!generated) throw new Error('Expected the generated Vx metadata module')

    const source = generated.content
    expect(source.includes('export const nextMetadata')).toBe(
      framework === 'next'
    )
    expect(source.includes('export const nextViewport')).toBe(
      framework === 'next'
    )
    expect(source.includes('export const tanstackHead')).toBe(
      framework.startsWith('tanstack')
    )
    expect(source.includes('export const vxDocs')).toBe(
      framework === 'tanstack-docs'
    )
  }
)
