import {
  existsSync,
  mkdirSync,
  readFileSync,
  watch,
  writeFileSync
} from 'node:fs'
import path from 'node:path'

import { type DocsConfig, resolveDocsConfig } from '../presets/docs'

type VxConfig = {
  core: VxCoreConfig
  docs?: DocsConfig
  i18n?: VxI18nConfig
  branding: {
    themeColor: string
    backgroundColor: string
  }
  pwa: VxPwaConfig
  metadata: VxMetadataConfig
}

type VxI18nConfig = {
  defaultLanguage: string
  languages: string[]
}

type VxCoreConfig = {
  id: string
  name: string
  shortName: string
  version: string
  description: string
  publisher: {
    name: string
    url: string
  }
  url: string
}

type VxPwaConfig = {
  display: string
  orientation: string
  scope: string
  startUrl: string
  categories: string[]
  icons: VxIconSource
  screenshots: VxImage[]
  shortcuts: VxShortcut[]
}

type VxIcon = {
  src: string
  sizes: string
  type: string
}

type VxIconSet = {
  path: string
  sizes: number[]
  type: string
}

type VxIconSource = VxIcon[] | VxIconSet

type VxImage = {
  src: string
  sizes: string
  type: string
}

type VxShortcut = {
  name: string
  shortName: string
  url: string
  icons: VxIconSource
}

type VxMetadataConfig = {
  title: string
  keywords: string[]
  theme: {
    lightColor: string
    darkColor: string
    lightBackgroundColor: string
    darkBackgroundColor: string
  }
  platforms: {
    apple: {
      mobileWebAppCapable: boolean
      webAppCapable: boolean
      touchIcon: string
      startupImages: VxStartupImageSource
    }
    microsoft: {
      startUrl: string
    }
  }
  social: {
    openGraph: {
      type: string
      image?: string
    }
    twitter: {
      creator: string
      site: string
      card: string
      image?: string
    }
  }
}

type VxStartupImage = {
  colorScheme?: 'light' | 'dark'
  device?: string
  width?: number
  height?: number
  pixelRatio?: number
  path?: string
  media?: string
  src?: string
}

type VxStartupImageSet = {
  path: string
  colorSchemes?: Array<'light' | 'dark'>
  sizes: VxStartupImage[]
}

type VxStartupImageSource = VxStartupImage[] | VxStartupImageSet

export type GenerateMetadataOptions = {
  projectRoot?: string
  publicDir?: string
}

type MetadataFile = {
  path: string
  content: string
}

type HtmlAttributeValue = boolean | string | undefined

const generatedNotice = 'Generated by Vx metadata. DO NOT EDIT.'
const indexMetadataStartMarker = '<!-- VX_METADATA_START -->'
const indexMetadataEndMarker = '<!-- VX_METADATA_END -->'

const readJson = <T>(file: string): T =>
  JSON.parse(readFileSync(file, 'utf8')) as T

const lowerFirst = (value: string) =>
  value ? `${value.charAt(0).toLowerCase()}${value.slice(1)}` : value

const normalizePath = (value: string) => value.split(path.sep).join('/')

const getProjectAssetBaseUrl = (projectRoot: string) =>
  `https://static.cdn.vezham.com/${normalizePath(path.relative(process.cwd(), projectRoot))}`

const createVersionedAssetUrl = (baseUrl: string, version: string) => {
  const versionParam = `vx=${encodeURIComponent(version)}`

  return (assetPath: string) =>
    `${baseUrl.replace(/\/$/, '')}/${assetPath.replace(/^\//, '')}?${versionParam}`
}

const getStaticAssetUrl = (assetPath: string, version: string) =>
  `https://static.cdn.vezham.com/${assetPath.replace(/^\//, '')}?vx=${encodeURIComponent(version)}`

const toAssetUrl = (
  assetPath: string,
  versionedAssetUrl: (assetPath: string) => string
) =>
  /^https?:\/\//.test(assetPath) || assetPath.startsWith('/')
    ? assetPath
    : versionedAssetUrl(assetPath)

type SocialImageSource = 'default' | 'path' | 'url'

type ResolvedSocialImage = {
  source: SocialImageSource
  url: string
}

const resolveSocialImage = (image: string | undefined): ResolvedSocialImage => {
  const value = image?.trim()

  if (!value) {
    return {
      source: 'default',
      url: '/og/image.png'
    }
  }

  if (/^https?:\/\//i.test(value)) {
    return { source: 'url', url: value }
  }

  return {
    source: 'path',
    url: `/${value.replace(/^\/+/, '')}`
  }
}

const getStartupImageMedia = (image: VxStartupImage) => {
  if (image.media) {
    return image.media
  }

  const colorScheme = image.colorScheme
    ? `(prefers-color-scheme: ${image.colorScheme})`
    : undefined
  const width = image.width ? `(device-width: ${image.width}px)` : undefined
  const height = image.height ? `(device-height: ${image.height}px)` : undefined
  const pixelRatio = image.pixelRatio
    ? `(-webkit-device-pixel-ratio: ${image.pixelRatio})`
    : undefined

  return [colorScheme, width, height, pixelRatio].filter(Boolean).join(' and ')
}

const createStartupImagePath = (template: string, image: VxStartupImage) =>
  template
    .replaceAll('{colorScheme}', image.colorScheme ?? '')
    .replaceAll('{device}', image.device ?? '')
    .replaceAll('{width}', String(image.width ?? ''))
    .replaceAll('{height}', String(image.height ?? ''))
    .replaceAll('{pixelRatio}', String(image.pixelRatio ?? ''))

const normalizeStartupImages = (
  startupImages: VxStartupImageSource
): VxStartupImage[] => {
  if (Array.isArray(startupImages)) {
    return startupImages
  }

  return (startupImages.colorSchemes ?? ['light', 'dark']).flatMap(
    colorScheme =>
      startupImages.sizes.map(size => {
        const image = { ...size, colorScheme }
        const sourcePath = size.path ?? size.src ?? startupImages.path

        return {
          ...image,
          path: createStartupImagePath(sourcePath, image)
        }
      })
  )
}

const writeMetadataFile = ({ path: file, content }: MetadataFile) => {
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, content)
}

const stringifyManifest = (manifest: Record<string, unknown>) =>
  JSON.stringify(manifest, null, 2).replace(
    '"categories": [\n    "productivity",\n    "personalization",\n    "utilities"\n  ]',
    '"categories": ["productivity", "personalization", "utilities"]'
  )

const stringifyTs = (value: unknown) => JSON.stringify(value, null, 2)

const escapeHtml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')

const isDefined = <T>(value: T | undefined): value is T => value !== undefined

const normalizeHtmlAttributeName = (name: string) =>
  name === 'charSet' ? 'charset' : name

const renderHtmlAttribute = ([name, value]: [string, HtmlAttributeValue]) => {
  if (value === undefined) {
    return undefined
  }

  if (value === true) {
    return name
  }

  if (value === false) {
    return undefined
  }

  return `${normalizeHtmlAttributeName(name)}="${escapeHtml(value)}"`
}

const renderHtmlTag = (
  tag: string,
  attributes: Record<string, HtmlAttributeValue>,
  indent = '    '
) => {
  const renderedAttributes = Object.entries(attributes)
    .map(renderHtmlAttribute)
    .filter(isDefined)
  const inlineTag = `${indent}<${tag} ${renderedAttributes.join(' ')} />`

  if (inlineTag.length <= 100) {
    return inlineTag
  }

  return `${indent}<${tag}\n${renderedAttributes
    .map(attribute => `${indent}  ${attribute}`)
    .join('\n')} />`
}

const escapeRegex = (value: string) =>
  value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const normalizeIcons = (icons: VxIconSource): VxIcon[] => {
  if (Array.isArray(icons)) {
    return icons
  }

  return icons.sizes.map(size => ({
    src: icons.path.replaceAll('{size}', String(size)),
    sizes: `${size}x${size}`,
    type: icons.type
  }))
}

const getRuntimeMetadata = (config: VxConfig, projectRoot = process.cwd()) => {
  const { core, metadata, pwa } = config
  const { apple, microsoft } = metadata.platforms
  const { openGraph, twitter } = metadata.social
  const versionedAssetUrl = createVersionedAssetUrl(
    getProjectAssetBaseUrl(projectRoot),
    core.version
  )
  const title = metadata.title
  const description = lowerFirst(core.description)
  const lightThemeColor = metadata.theme.lightColor
  const darkThemeColor = metadata.theme.darkColor
  const lightBackgroundColor = metadata.theme.lightBackgroundColor
  const darkBackgroundColor = metadata.theme.darkBackgroundColor
  const faviconLight = versionedAssetUrl('favicon-light.png')
  const faviconDark = versionedAssetUrl('favicon-dark.png')
  const maskIcon = versionedAssetUrl('safari-pinned-tab.svg')
  const appleTouchIcon = versionedAssetUrl(apple.touchIcon)
  const openGraphImage = resolveSocialImage(openGraph.image)
  const twitterImage = resolveSocialImage(
    twitter.image?.trim() ? twitter.image : openGraph.image
  )
  const startupImages = normalizeStartupImages(apple.startupImages).map(
    image => ({
      media: getStartupImageMedia(image),
      url: toAssetUrl(image.path ?? image.src ?? '', versionedAssetUrl)
    })
  )

  return {
    title,
    description,
    url: core.url,
    manifest: '/manifest.webmanifest',
    browserConfig: '/browserconfig.xml',
    startUrl: microsoft.startUrl ?? pwa.startUrl,
    author: core.publisher,
    keywords: metadata.keywords,
    theme: {
      lightColor: lightThemeColor,
      darkColor: darkThemeColor,
      lightBackgroundColor,
      darkBackgroundColor
    },
    mobileWebAppCapable: apple.mobileWebAppCapable,
    apple: {
      title: core.name,
      capable: apple.webAppCapable,
      touchIcon: appleTouchIcon,
      startupImages
    },
    icons: {
      faviconLight,
      faviconDark,
      maskIcon
    },
    microsoft: {
      applicationName: core.name,
      config: '/browserconfig.xml',
      startUrl: microsoft.startUrl
    },
    openGraph: {
      type: openGraph.type,
      title: core.name,
      description,
      image: openGraphImage.url,
      imageSource: openGraphImage.source,
      url: core.url
    },
    twitter: {
      creator: twitter.creator,
      site: twitter.site,
      title: core.name,
      description,
      image: twitterImage.url,
      url: core.url,
      card: twitter.card
    }
  }
}

const getDomain = (url: string) => {
  try {
    return new URL(url).hostname
  } catch {
    return url.replace(/^https?:\/\//, '').replace(/\/.*$/, '')
  }
}

const getLocalHostName = (url: string) =>
  getDomain(url).replace(/\.vezham\.app$/, '.vezham.local')

const getVxEnv = ({ core }: VxConfig) => ({
  HOST_NAME: getLocalHostName(core.url),
  V_APP_ID: core.id,
  V_APP_NAME: core.name,
  V_APP_VER: core.version
})

const syncEnvContent = (
  content: string,
  values: Record<string, string>
): string => {
  const lines = content ? content.replace(/\n$/, '').split('\n') : []
  const synced = new Set<string>()
  const envLinePattern = /^([A-Z][A-Z0-9_]*)=/
  const nextLines = lines.map(line => {
    const key = line.match(envLinePattern)?.[1]

    if (!key || !(key in values)) {
      return line
    }

    synced.add(key)

    return `${key}=${values[key]}`
  })
  const missingLines = Object.entries(values)
    .filter(([key]) => !synced.has(key))
    .map(([key, value]) => `${key}=${value}`)

  if (missingLines.length > 0) {
    const prePortIndex = nextLines.findIndex(line =>
      line.startsWith('PRE_PORT=')
    )
    const portIndex = nextLines.findIndex(line => line.startsWith('PORT='))
    const insertIndex =
      prePortIndex >= 0 ? prePortIndex + 1 : portIndex >= 0 ? portIndex + 1 : 0

    nextLines.splice(insertIndex, 0, ...missingLines)
  }

  return `${nextLines.join('\n')}\n`
}

const getTanStackHead = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    meta: [
      { charSet: 'utf-8' },
      {
        name: 'viewport',
        content:
          'width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=1, shrink-to-fit=no'
      },
      { name: 'author', content: metadata.author?.name ?? '' },
      { name: 'keywords', content: metadata.keywords.join(', ') },
      { title: metadata.title },
      { name: 'description', content: metadata.description },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightColor
      },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightBackgroundColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkBackgroundColor
      },
      {
        name: 'mobile-web-app-capable',
        content: metadata.mobileWebAppCapable ? 'yes' : 'no'
      },
      { name: 'apple-mobile-web-app-title', content: metadata.apple.title },
      {
        name: 'apple-mobile-web-app-capable',
        content: metadata.apple.capable ? 'yes' : 'no'
      },
      {
        name: 'application-name',
        content: metadata.microsoft.applicationName
      },
      {
        name: 'msapplication-config',
        content: metadata.microsoft.config
      },
      {
        name: 'msapplication-starturl',
        content: metadata.microsoft.startUrl
      },
      { property: 'og:type', content: metadata.openGraph.type },
      { property: 'og:title', content: metadata.openGraph.title },
      { property: 'og:description', content: metadata.openGraph.description },
      { property: 'og:image', content: metadata.openGraph.image },
      { property: 'og:url', content: metadata.openGraph.url },
      { name: 'twitter:creator', content: metadata.twitter.creator },
      { name: 'twitter:site', content: metadata.twitter.site },
      { name: 'twitter:title', content: metadata.twitter.title },
      {
        name: 'twitter:description',
        content: metadata.twitter.description
      },
      { name: 'twitter:image', content: metadata.twitter.image },
      { name: 'twitter:url', content: metadata.twitter.url },
      { name: 'twitter:card', content: metadata.twitter.card }
    ],
    links: [
      { rel: 'manifest', href: metadata.manifest },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'apple-touch-icon',
        href: metadata.apple.touchIcon
      },
      ...metadata.apple.startupImages.map(image => ({
        rel: 'apple-touch-startup-image',
        media: image.media,
        href: image.url
      }))
    ]
  }
}

const getIndexHtmlMetadataBlock = (
  config: VxConfig,
  projectRoot = process.cwd()
) => {
  const head = getTanStackHead(config, projectRoot)
  const [charsetMeta, ...meta] = head.meta
  const renderHeadMetaEntry = (
    entry: Record<string, HtmlAttributeValue>
  ): string => {
    if (typeof entry.title === 'string') {
      return `    <title>${escapeHtml(entry.title)}</title>`
    }

    return renderHtmlTag('meta', entry)
  }
  const note = (label: string) => `    <!-- wjdlz/NOTE: ${label} -->`
  const isMetaName = (
    entry: Record<string, HtmlAttributeValue>,
    names: string[]
  ) => typeof entry.name === 'string' && names.includes(entry.name)
  const webMeta = meta.filter(
    entry =>
      entry.title ||
      isMetaName(entry, ['viewport', 'author', 'keywords', 'description'])
  )
  const themeMeta = meta.filter(entry =>
    isMetaName(entry, ['theme-color', 'background-color'])
  )
  const mobileMeta = meta.filter(entry =>
    isMetaName(entry, ['mobile-web-app-capable'])
  )
  const appleMeta = meta.filter(
    entry => typeof entry.name === 'string' && entry.name.startsWith('apple-')
  )
  const microsoftMeta = meta.filter(entry =>
    isMetaName(entry, [
      'application-name',
      'msapplication-config',
      'msapplication-starturl'
    ])
  )
  const openGraphMeta = meta.filter(
    entry =>
      typeof entry.property === 'string' && entry.property.startsWith('og:')
  )
  const twitterMeta = meta.filter(
    entry => typeof entry.name === 'string' && entry.name.startsWith('twitter:')
  )
  const pwaLinks = head.links.filter(
    link =>
      link.rel === 'manifest' ||
      link.rel === 'icon' ||
      link.rel === 'shortcut icon' ||
      link.rel === 'mask-icon'
  )
  const appleLinks = head.links.filter(
    link => typeof link.rel === 'string' && link.rel.startsWith('apple-touch-')
  )
  const lines = [
    `    ${indexMetadataStartMarker}`,
    `    <!-- ${generatedNotice} -->`,
    note('WEB'),
    ...(charsetMeta ? [renderHeadMetaEntry(charsetMeta)] : []),
    renderHtmlTag('meta', {
      'http-equiv': 'X-UA-Compatible',
      content: 'IE=edge'
    }),
    ...webMeta.map(renderHeadMetaEntry),
    '',
    note('PWA::THEME'),
    ...themeMeta.map(renderHeadMetaEntry),
    ...pwaLinks.map(link => renderHtmlTag('link', link)),
    '',
    note('PWA::MOBILE'),
    ...mobileMeta.map(renderHeadMetaEntry),
    '',
    note('APPLE'),
    ...appleMeta.map(renderHeadMetaEntry),
    ...appleLinks.map(link => renderHtmlTag('link', link)),
    '',
    note('MICROSOFT'),
    ...microsoftMeta.map(renderHeadMetaEntry),
    '',
    note('META'),
    ...openGraphMeta.map(renderHeadMetaEntry),
    '',
    note('TWITTER'),
    ...twitterMeta.map(renderHeadMetaEntry),
    `    ${indexMetadataEndMarker}`
  ]

  return lines.join('\n')
}

const getPreservedIndexHeadContent = (headContent: string) =>
  headContent
    .split('\n')
    .filter(line => {
      const trimmedLine = line.trim()

      return (
        trimmedLine.startsWith('<base ') || trimmedLine.startsWith('<script ')
      )
    })
    .join('\n')

const syncIndexHtmlContent = (
  content: string,
  config: VxConfig,
  projectRoot = process.cwd()
) => {
  const metadataBlock = getIndexHtmlMetadataBlock(config, projectRoot)
  const headPattern = /(<head>\n)([\s\S]*?)(\n\s*<\/head>)/
  const headMatch = content.match(headPattern)

  if (!headMatch) {
    throw new Error('Unable to sync Vx metadata because index.html has no head')
  }

  const [, headStart, headContent, headEnd] = headMatch
  const existingBlockPattern = new RegExp(
    `${escapeRegex(`    ${indexMetadataStartMarker}`)}[\\s\\S]*?${escapeRegex(
      `    ${indexMetadataEndMarker}`
    )}`
  )
  const preservedHeadContent = getPreservedIndexHeadContent(
    headContent.replace(existingBlockPattern, '')
  )
  const nextHeadContent = [preservedHeadContent, metadataBlock]
    .filter(Boolean)
    .join('\n\n')

  return content.replace(
    headPattern,
    `${headStart}${nextHeadContent}${headEnd}`
  )
}

const getNextMetadata = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    metadataBase: metadata.url ? new URL(metadata.url) : undefined,
    title: metadata.title,
    description: metadata.description,
    applicationName: metadata.microsoft.applicationName,
    authors: metadata.author?.name
      ? [
          {
            name: metadata.author.name,
            url: metadata.author.url
          }
        ]
      : undefined,
    keywords: metadata.keywords,
    manifest: metadata.manifest,
    icons: {
      icon: [
        {
          url: metadata.icons.faviconLight,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: dark)'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ],
      shortcut: [
        {
          url: metadata.icons.faviconLight,
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          media: '(prefers-color-scheme: dark)'
        }
      ],
      apple: [{ url: metadata.apple.touchIcon }],
      other: [
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ]
    },
    appleWebApp: {
      title: metadata.apple.title,
      capable: metadata.apple.capable,
      startupImage: metadata.apple.startupImages
    },
    openGraph: {
      type: metadata.openGraph.type,
      title: metadata.openGraph.title,
      description: metadata.openGraph.description,
      images: [metadata.openGraph.image],
      url: metadata.openGraph.url
    },
    twitter: {
      creator: metadata.twitter.creator,
      site: metadata.twitter.site,
      title: metadata.twitter.title,
      description: metadata.twitter.description,
      images: [metadata.twitter.image],
      card: metadata.twitter.card
    },
    other: {
      'mobile-web-app-capable': metadata.mobileWebAppCapable ? 'yes' : 'no',
      'msapplication-config': metadata.microsoft.config,
      'msapplication-starturl': metadata.microsoft.startUrl,
      'twitter:url': metadata.twitter.url
    }
  }
}

const getNextViewport = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1.5,
    userScalable: true,
    themeColor: [
      {
        media: '(prefers-color-scheme: light)',
        color: metadata.theme.lightColor
      },
      {
        media: '(prefers-color-scheme: dark)',
        color: metadata.theme.darkColor
      }
    ]
  }
}

const getGeneratedMetadataModule = (
  config: VxConfig,
  projectRoot = process.cwd()
) => `// ${generatedNotice}

export const vxMetadata = ${stringifyTs(getRuntimeMetadata(config, projectRoot))} as const

export const vxCore = ${stringifyTs(config.core)} as const

export const vxDocs = ${stringifyTs(resolveDocsConfig(config.docs))} as const

export const vxI18n = ${
  config.i18n ? `${stringifyTs(config.i18n)} as const` : 'undefined'
}

export const tanstackHead = ${stringifyTs(getTanStackHead(config, projectRoot))}

export const nextMetadata = ${stringifyTs(getNextMetadata(config, projectRoot))}

export const nextViewport = ${stringifyTs(getNextViewport(config, projectRoot))}
`

export const loadVxAppConfig = (projectRoot = process.cwd()) => {
  const configFile = path.resolve(projectRoot, 'vx.app.json')

  if (!existsSync(configFile)) {
    throw new Error(`Missing vx.app.json at ${configFile}`)
  }

  return readJson<VxConfig>(configFile)
}

export const getMetadataFiles = (
  config: VxConfig,
  projectRoot = process.cwd()
): MetadataFile[] => {
  const { core, pwa } = config
  const publicDir = path.resolve(projectRoot, 'public')
  const indexFile = path.resolve(projectRoot, 'index.html')
  const envFile = path.resolve(projectRoot, '.env')
  const versionedAssetUrl = createVersionedAssetUrl(
    getProjectAssetBaseUrl(projectRoot),
    core.version
  )
  const manifest = {
    manifest_version: 1,
    version: core.version,
    id: core.id,
    name: core.name,
    short_name: core.shortName,
    description: lowerFirst(core.description),
    scope: pwa.scope,
    start_url: `${pwa.startUrl}?utm_source=homescreen&utm_medium=shortcut&pwa=true`,
    display: pwa.display,
    orientation: pwa.orientation,
    theme_color: config.branding.themeColor,
    background_color: config.branding.backgroundColor,
    categories: pwa.categories,
    icons: normalizeIcons(pwa.icons).map(icon => ({
      src: toAssetUrl(icon.src, versionedAssetUrl),
      sizes: icon.sizes,
      type: icon.type
    })),
    screenshots: pwa.screenshots.map(screenshot => ({
      src: toAssetUrl(screenshot.src, versionedAssetUrl),
      type: screenshot.type,
      sizes: screenshot.sizes
    })),
    shortcuts: pwa.shortcuts.map(shortcut => ({
      name: shortcut.name,
      short_name: shortcut.shortName,
      url: `${shortcut.url}?utm_source=jumplist&utm_medium=shortcut&pwa=true`,
      icons: normalizeIcons(shortcut.icons).map(icon => ({
        src: toAssetUrl(icon.src, versionedAssetUrl),
        sizes: icon.sizes,
        type: icon.type
      }))
    }))
  }
  const browserConfig = `<?xml version="1.0" encoding="utf-8" ?>
<!-- ${generatedNotice} -->
<browserconfig>
  <msapplication>
    <tile>
      <square70x70logo
        src="${versionedAssetUrl('icons/icon-square-70x70.png')}" />
      <square150x150logo
        src="${versionedAssetUrl('icons/icon-square-150x150.png')}" />
      <wide310x150logo
        src="${versionedAssetUrl('icons/icon-square-310x150.png')}" />
      <square310x310logo
        src="${versionedAssetUrl('icons/icon-square-310x310.png')}" />
      <tilecolor>transparent</tilecolor>
    </tile>
  </msapplication>
</browserconfig>
`
  const offlinePage = `<!doctype html>
<!-- ${generatedNotice} -->
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=1, shrink-to-fit=no" />
    <meta name="author" content="${core.publisher.name}" />
    <title>Offline | ${core.name}</title>
  </head>

  <body>
    <div class="offline-container">
      <img
        src="${getStaticAssetUrl('vassets/no-internet.svg', core.version)}"
        alt="offline"
        class="offline-image" />
      <div class="offline-header">Oops! You're offline</div>
      <div class="offline-text">
        Please check your connection and try again.
      </div>
      <div class="offline-button" onclick="handleHome()">Retry</div>
    </div>
  </body>

  <style>
    body {
      margin: 0px;
      font-family: 'Poppins', serif;
    }

    .offline-container {
      align-items: center;
      display: flex;
      flex-direction: column;
      gap: 20px;
      height: 100vh !important;
      justify-content: center;
      text-align: center;
      width: 100%;
    }

    .offline-header {
      font-size: 3rem;
      font-weight: 700;
    }

    .offline-text {
      font-size: 1.5rem;
    }

    .offline-button {
      border-radius: 50px;
      cursor: pointer;
      flex: 0 1 !important;
      padding: 15px 20px;
      font-size: 2rem;
      background-color: oklch(50.768% 0.23111 261.795);
    }

    .offline-button:hover {
      background-color: oklch(54.881% 0.24991 261.799 / 0.25);
    }

    @media (prefers-color-scheme: light) {
      body {
        background: oklch(100% 0.00011 271.152);
      }

      .offline-header {
        color: oklch(0% 0 0);
      }

      .offline-text {
        color: oklch(0% 0 0 / 0.5);
      }

      .offline-button {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-button:hover {
        color: oklch(0% 0 0);
      }
    }

    @media (prefers-color-scheme: dark) {
      body {
        background: oklch(23.929% 0.00003 271.152);
      }

      .offline-header {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-text {
        color: oklch(100% 0.00011 271.152 / 0.5);
      }

      .offline-button {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-button:hover {
        color: oklch(100% 0.00011 271.152);
      }
    }

    @media (min-width: 0px) and (max-width: 1024px) {
      .offline-image {
        width: 70%;
      }
    }

    @media only screen and (orientation: landscape) {
      .offline-image {
        width: 30%;
      }

      .offline-header {
        font-size: 2rem;
      }

      .offline-text,
      .offline-button {
        font-size: 1rem;
      }
    }
  </style>
  <script>
    function handleHome() {
      window.location.href = '/'
    }
  </script>
</html>
`

  return [
    {
      path: path.join(publicDir, 'manifest.webmanifest'),
      content: `${stringifyManifest(manifest)}\n`
    },
    {
      path: path.join(publicDir, 'browserconfig.xml'),
      content: browserConfig
    },
    {
      path: path.join(publicDir, 'robots.txt'),
      content: `# ${generatedNotice}\n# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nDisallow:\n`
    },
    {
      path: path.join(publicDir, 'sw.js'),
      content: `/* ${generatedNotice} */\n/* global importScripts */\nimportScripts('https://static.cdn.vezham.com/workers/sw.js?vx=${core.version}')\n`
    },
    {
      path: path.join(publicDir, 'offline.html'),
      content: offlinePage
    },
    {
      path: path.join(publicDir, 'api/hello.json'),
      content: `${JSON.stringify(
        {
          status: true,
          message: 'Hello from Vezham :)'
        },
        null,
        2
      )}\n`
    },
    ...(existsSync(indexFile)
      ? [
          {
            path: indexFile,
            content: syncIndexHtmlContent(
              readFileSync(indexFile, 'utf8'),
              config,
              projectRoot
            )
          }
        ]
      : []),
    {
      path: path.join(projectRoot, 'src/generated/vx.ts'),
      content: getGeneratedMetadataModule(config, projectRoot)
    },
    {
      path: envFile,
      content: syncEnvContent(
        existsSync(envFile) ? readFileSync(envFile, 'utf8') : '',
        getVxEnv(config)
      )
    }
  ]
}

export const generateMetadata = (options: GenerateMetadataOptions = {}) => {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd())
  const files = getMetadataFiles(loadVxAppConfig(projectRoot), projectRoot)

  for (const file of files) {
    const outputPath = options.publicDir
      ? path.join(
          path.resolve(options.publicDir),
          path.relative(path.join(projectRoot, 'public'), file.path)
        )
      : file.path

    writeMetadataFile({
      ...file,
      path: outputPath
    })
  }

  return files.map(file => file.path)
}

export const watchMetadata = (options: GenerateMetadataOptions = {}) => {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd())
  const configFile = path.join(projectRoot, 'vx.app.json')
  const regenerate = () => {
    const files = generateMetadata(options)

    console.log(`Generated ${files.length} metadata files from ${configFile}`)
  }

  regenerate()

  return watch(configFile, { persistent: true }, regenerate)
}
