import {
  existsSync,
  mkdirSync,
  readFileSync,
  watch,
  writeFileSync
} from 'node:fs'
import path from 'node:path'

type VxConfig = {
  id: string
  name: string
  shortName?: string
  version: string
  description?: string
  url?: string
  publisher?: {
    name?: string
    url?: string
  }
  branding?: {
    themeColor?: string
    backgroundColor?: string
  }
  pwa?: {
    display?: string
    orientation?: string
    scope?: string
    startUrl?: string
  }
  metadata?: VxMetadataConfig
}

type VxMetadataConfig = {
  title?: string
  keywords?: string[]
  theme?: {
    lightColor?: string
    darkColor?: string
    lightBackgroundColor?: string
    darkBackgroundColor?: string
  }
  apple?: {
    mobileWebAppCapable?: boolean
    webAppCapable?: boolean
    touchIcon?: string
    startupImages?: VxStartupImage[]
  }
  microsoft?: {
    startUrl?: string
  }
  openGraph?: {
    type?: string
    image?: string
  }
  twitter?: {
    creator?: string
    site?: string
    card?: string
    image?: string
  }
}

type VxStartupImage = {
  colorScheme?: 'light' | 'dark'
  width?: number
  height?: number
  pixelRatio?: number
  path?: string
  media?: string
  src?: string
}

export type GenerateMetadataOptions = {
  projectRoot?: string
  publicDir?: string
}

type MetadataFile = {
  path: string
  content: string
}

const generatedIconSizes = [48, 72, 96, 128, 192, 384, 512, 1024]
const generatedNotice = 'Generated by VX metadata. DO NOT EDIT.'

const readJson = <T>(file: string): T =>
  JSON.parse(readFileSync(file, 'utf8')) as T

const lowerFirst = (value: string) =>
  value ? `${value.charAt(0).toLowerCase()}${value.slice(1)}` : value

const normalizePath = (value: string) => value.split(path.sep).join('/')

const getProjectAssetBaseUrl = (projectRoot: string) =>
  `https://static.cdn.vezham.com/${normalizePath(path.relative(process.cwd(), projectRoot))}`

const createVersionedAssetUrl = (baseUrl: string, version: string) => {
  const versionParam = `vx=${encodeURIComponent(version)}`

  return (assetPath: string) =>
    `${baseUrl.replace(/\/$/, '')}/${assetPath.replace(/^\//, '')}?${versionParam}`
}

const getStaticAssetUrl = (assetPath: string, version: string) =>
  `https://static.cdn.vezham.com/${assetPath.replace(/^\//, '')}?vx=${encodeURIComponent(version)}`

const toAssetUrl = (
  assetPath: string,
  versionedAssetUrl: (assetPath: string) => string
) =>
  /^https?:\/\//.test(assetPath) || assetPath.startsWith('/')
    ? assetPath
    : versionedAssetUrl(assetPath)

const getStartupImageMedia = (image: VxStartupImage) => {
  if (image.media) {
    return image.media
  }

  const colorScheme = image.colorScheme
    ? `(prefers-color-scheme: ${image.colorScheme})`
    : undefined
  const width = image.width ? `(device-width: ${image.width}px)` : undefined
  const height = image.height ? `(device-height: ${image.height}px)` : undefined
  const pixelRatio = image.pixelRatio
    ? `(-webkit-device-pixel-ratio: ${image.pixelRatio})`
    : undefined

  return [colorScheme, width, height, pixelRatio].filter(Boolean).join(' and ')
}

const writeMetadataFile = ({ path: file, content }: MetadataFile) => {
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, content)
}

const stringifyManifest = (manifest: Record<string, unknown>) =>
  JSON.stringify(manifest, null, 2).replace(
    '"categories": [\n    "productivity",\n    "personalization",\n    "utilities"\n  ]',
    '"categories": ["productivity", "personalization", "utilities"]'
  )

const stringifyTs = (value: unknown) => JSON.stringify(value, null, 2)

const getRuntimeMetadata = (config: VxConfig, projectRoot = process.cwd()) => {
  const versionedAssetUrl = createVersionedAssetUrl(
    getProjectAssetBaseUrl(projectRoot),
    config.version
  )
  const metadata = config.metadata ?? {}
  const title = metadata.title ?? `Home | ${config.name}`
  const description = lowerFirst(config.description ?? '')
  const lightThemeColor = metadata.theme?.lightColor ?? 'white'
  const darkThemeColor = metadata.theme?.darkColor ?? 'black'
  const lightBackgroundColor =
    metadata.theme?.lightBackgroundColor ?? lightThemeColor
  const darkBackgroundColor =
    metadata.theme?.darkBackgroundColor ?? darkThemeColor
  const faviconLight = versionedAssetUrl('favicon-light.png')
  const faviconDark = versionedAssetUrl('favicon-dark.png')
  const maskIcon = versionedAssetUrl('safari-pinned-tab.svg')
  const appleTouchIcon = versionedAssetUrl(
    metadata.apple?.touchIcon ?? 'icons/icon-512x512.png'
  )
  const openGraphImage = toAssetUrl(
    metadata.openGraph?.image ?? 'icons/icon-512x512.png',
    versionedAssetUrl
  )
  const twitterImage = toAssetUrl(
    metadata.twitter?.image ??
      metadata.openGraph?.image ??
      'icons/icon-512x512.png',
    versionedAssetUrl
  )
  const startupImages =
    metadata.apple?.startupImages?.map(image => ({
      media: getStartupImageMedia(image),
      url: toAssetUrl(image.path ?? image.src ?? '', versionedAssetUrl)
    })) ?? []

  return {
    title,
    description,
    url: config.url,
    manifest: '/manifest.webmanifest',
    browserConfig: '/browserconfig.xml',
    startUrl: metadata.microsoft?.startUrl ?? config.pwa?.startUrl ?? '/',
    author: config.publisher,
    keywords: metadata.keywords ?? [config.name],
    theme: {
      lightColor: lightThemeColor,
      darkColor: darkThemeColor,
      lightBackgroundColor,
      darkBackgroundColor
    },
    mobileWebAppCapable: metadata.apple?.mobileWebAppCapable ?? true,
    apple: {
      title: config.name,
      capable: metadata.apple?.webAppCapable ?? true,
      touchIcon: appleTouchIcon,
      startupImages
    },
    icons: {
      faviconLight,
      faviconDark,
      maskIcon
    },
    microsoft: {
      applicationName: config.name,
      config: '/browserconfig.xml',
      startUrl: metadata.microsoft?.startUrl ?? '/'
    },
    openGraph: {
      type: metadata.openGraph?.type ?? 'website',
      title: config.name,
      description,
      image: openGraphImage,
      url: config.url
    },
    twitter: {
      creator: metadata.twitter?.creator ?? '@vezham',
      site: metadata.twitter?.site ?? '@vezham',
      title: config.name,
      description,
      image: twitterImage,
      card: metadata.twitter?.card ?? 'summary_large_image'
    }
  }
}

const getTanStackHead = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    meta: [
      { charSet: 'utf-8' },
      {
        name: 'viewport',
        content:
          'width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=1, shrink-to-fit=no'
      },
      { name: 'author', content: metadata.author?.name ?? '' },
      { name: 'keywords', content: metadata.keywords.join(', ') },
      { title: metadata.title },
      { name: 'description', content: metadata.description },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightColor
      },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightBackgroundColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkBackgroundColor
      },
      {
        name: 'mobile-web-app-capable',
        content: metadata.mobileWebAppCapable ? 'yes' : 'no'
      },
      { name: 'apple-mobile-web-app-title', content: metadata.apple.title },
      {
        name: 'apple-mobile-web-app-capable',
        content: metadata.apple.capable ? 'yes' : 'no'
      },
      {
        name: 'application-name',
        content: metadata.microsoft.applicationName
      },
      {
        name: 'msapplication-config',
        content: metadata.microsoft.config
      },
      {
        name: 'msapplication-starturl',
        content: metadata.microsoft.startUrl
      },
      { property: 'og:type', content: metadata.openGraph.type },
      { property: 'og:title', content: metadata.openGraph.title },
      { property: 'og:description', content: metadata.openGraph.description },
      { property: 'og:image', content: metadata.openGraph.image },
      { property: 'og:url', content: metadata.openGraph.url },
      { property: 'twitter:creator', content: metadata.twitter.creator },
      { property: 'twitter:site', content: metadata.twitter.site },
      { property: 'twitter:title', content: metadata.twitter.title },
      {
        property: 'twitter:description',
        content: metadata.twitter.description
      },
      { property: 'twitter:image', content: metadata.twitter.image },
      { property: 'twitter:card', content: metadata.twitter.card }
    ],
    links: [
      { rel: 'manifest', href: metadata.manifest },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'apple-touch-icon',
        href: metadata.apple.touchIcon
      },
      ...metadata.apple.startupImages.map(image => ({
        rel: 'apple-touch-startup-image',
        media: image.media,
        href: image.url
      }))
    ]
  }
}

const getNextMetadata = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    metadataBase: metadata.url ? new URL(metadata.url) : undefined,
    title: metadata.title,
    description: metadata.description,
    applicationName: metadata.microsoft.applicationName,
    authors: metadata.author?.name
      ? [
          {
            name: metadata.author.name,
            url: metadata.author.url
          }
        ]
      : undefined,
    keywords: metadata.keywords,
    manifest: metadata.manifest,
    icons: {
      icon: [
        {
          url: metadata.icons.faviconLight,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: dark)'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ],
      shortcut: [
        {
          url: metadata.icons.faviconLight,
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          media: '(prefers-color-scheme: dark)'
        }
      ],
      apple: [{ url: metadata.apple.touchIcon }],
      other: [
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ]
    },
    appleWebApp: {
      title: metadata.apple.title,
      capable: metadata.apple.capable,
      startupImage: metadata.apple.startupImages
    },
    openGraph: {
      type: metadata.openGraph.type,
      title: metadata.openGraph.title,
      description: metadata.openGraph.description,
      images: [metadata.openGraph.image],
      url: metadata.openGraph.url
    },
    twitter: {
      creator: metadata.twitter.creator,
      site: metadata.twitter.site,
      title: metadata.twitter.title,
      description: metadata.twitter.description,
      images: [metadata.twitter.image],
      card: metadata.twitter.card
    },
    other: {
      'mobile-web-app-capable': metadata.mobileWebAppCapable ? 'yes' : 'no',
      'msapplication-config': metadata.microsoft.config,
      'msapplication-starturl': metadata.microsoft.startUrl
    }
  }
}

const getNextViewport = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1.5,
    userScalable: true,
    themeColor: [
      {
        media: '(prefers-color-scheme: light)',
        color: metadata.theme.lightColor
      },
      {
        media: '(prefers-color-scheme: dark)',
        color: metadata.theme.darkColor
      }
    ]
  }
}

const getGeneratedMetadataModule = (
  config: VxConfig,
  projectRoot = process.cwd()
) => `// ${generatedNotice}

export const vxMetadata = ${stringifyTs(getRuntimeMetadata(config, projectRoot))} as const

export const tanstackHead = ${stringifyTs(getTanStackHead(config, projectRoot))}

export const nextMetadata = ${stringifyTs(getNextMetadata(config, projectRoot))}

export const nextViewport = ${stringifyTs(getNextViewport(config, projectRoot))}
`

export const loadVxConfig = (projectRoot = process.cwd()) => {
  const configFile = path.resolve(projectRoot, 'vx.config.json')

  if (!existsSync(configFile)) {
    throw new Error(`Missing vx.config.json at ${configFile}`)
  }

  return readJson<VxConfig>(configFile)
}

export const getMetadataFiles = (
  config: VxConfig,
  projectRoot = process.cwd()
): MetadataFile[] => {
  const publicDir = path.resolve(projectRoot, 'public')
  const versionedAssetUrl = createVersionedAssetUrl(
    getProjectAssetBaseUrl(projectRoot),
    config.version
  )
  const startUrl = config.pwa?.startUrl ?? '/'
  const themeColor = config.branding?.themeColor ?? '#000000'
  const backgroundColor = config.branding?.backgroundColor ?? '#ffffff'
  const manifest = {
    manifest_version: 1,
    version: config.version,
    id: config.id,
    name: config.name,
    short_name: config.shortName ?? config.name,
    description: lowerFirst(config.description ?? ''),
    scope: config.pwa?.scope ?? '.',
    start_url: `${startUrl}?utm_source=homescreen&utm_medium=shortcut&pwa=true`,
    display: config.pwa?.display ?? 'standalone',
    orientation: config.pwa?.orientation ?? 'any',
    theme_color: themeColor,
    background_color: backgroundColor,
    categories: ['productivity', 'personalization', 'utilities'],
    icons: generatedIconSizes.map(size => ({
      src: versionedAssetUrl(`icons/icon-${size}x${size}.png`),
      sizes: `${size}x${size}`,
      type: 'image/png'
    })),
    screenshots: [
      {
        src: versionedAssetUrl('screenshots/home-512x512.png'),
        type: 'image/png',
        sizes: '512x512'
      }
    ],
    shortcuts: [
      {
        name: 'Home',
        short_name: 'Home',
        url: `${startUrl}?utm_source=jumplist&utm_medium=shortcut&pwa=true`,
        icons: [
          {
            src: versionedAssetUrl('shortcuts/icon-home-192x192.png'),
            type: 'image/png',
            sizes: '192x192'
          }
        ]
      }
    ]
  }
  const browserConfig = `<?xml version="1.0" encoding="utf-8" ?>
<!-- ${generatedNotice} -->
<browserconfig>
  <msapplication>
    <tile>
      <square70x70logo
        src="${versionedAssetUrl('icons/icon-square-70x70.png')}" />
      <square150x150logo
        src="${versionedAssetUrl('icons/icon-square-150x150.png')}" />
      <wide310x150logo
        src="${versionedAssetUrl('icons/icon-square-310x150.png')}" />
      <square310x310logo
        src="${versionedAssetUrl('icons/icon-square-310x310.png')}" />
      <tilecolor>transparent</tilecolor>
    </tile>
  </msapplication>
</browserconfig>
`
  const offlinePage = `<!doctype html>
<!-- ${generatedNotice} -->
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=1, shrink-to-fit=no" />
    <meta name="author" content="${config.publisher?.name ?? ''}" />
    <title>Offline | ${config.name}</title>
  </head>

  <body>
    <div class="offline-container">
      <img
        src="${getStaticAssetUrl('vassets/no-internet.svg', config.version)}"
        alt="offline"
        class="offline-image" />
      <div class="offline-header">Oops! You're offline</div>
      <div class="offline-text">
        Please check your connection and try again.
      </div>
      <div class="offline-button" onclick="handleHome()">Retry</div>
    </div>
  </body>

  <style>
    body {
      margin: 0px;
      font-family: 'Poppins', serif;
    }

    .offline-container {
      align-items: center;
      display: flex;
      flex-direction: column;
      gap: 20px;
      height: 100vh !important;
      justify-content: center;
      text-align: center;
      width: 100%;
    }

    .offline-header {
      font-size: 3rem;
      font-weight: 700;
    }

    .offline-text {
      font-size: 1.5rem;
    }

    .offline-button {
      border-radius: 50px;
      cursor: pointer;
      flex: 0 1 !important;
      padding: 15px 20px;
      font-size: 2rem;
      background-color: oklch(50.768% 0.23111 261.795);
    }

    .offline-button:hover {
      background-color: oklch(54.881% 0.24991 261.799 / 0.25);
    }

    @media (prefers-color-scheme: light) {
      body {
        background: oklch(100% 0.00011 271.152);
      }

      .offline-header {
        color: oklch(0% 0 0);
      }

      .offline-text {
        color: oklch(0% 0 0 / 0.5);
      }

      .offline-button {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-button:hover {
        color: oklch(0% 0 0);
      }
    }

    @media (prefers-color-scheme: dark) {
      body {
        background: oklch(23.929% 0.00003 271.152);
      }

      .offline-header {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-text {
        color: oklch(100% 0.00011 271.152 / 0.5);
      }

      .offline-button {
        color: oklch(100% 0.00011 271.152);
      }

      .offline-button:hover {
        color: oklch(100% 0.00011 271.152);
      }
    }

    @media (min-width: 0px) and (max-width: 1024px) {
      .offline-image {
        width: 70%;
      }
    }

    @media only screen and (orientation: landscape) {
      .offline-image {
        width: 30%;
      }

      .offline-header {
        font-size: 2rem;
      }

      .offline-text,
      .offline-button {
        font-size: 1rem;
      }
    }
  </style>
  <script>
    function handleHome() {
      window.location.href = '/'
    }
  </script>
</html>
`

  return [
    {
      path: path.join(publicDir, 'manifest.webmanifest'),
      content: `${stringifyManifest(manifest)}\n`
    },
    {
      path: path.join(publicDir, 'browserconfig.xml'),
      content: browserConfig
    },
    {
      path: path.join(publicDir, 'robots.txt'),
      content: `# ${generatedNotice}\n# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nDisallow:\n`
    },
    {
      path: path.join(publicDir, 'sw.js'),
      content: `/* ${generatedNotice} */\n/* global importScripts */\nimportScripts('https://static.cdn.vezham.com/workers/sw.js?vx=${config.version}')\n`
    },
    {
      path: path.join(publicDir, 'offline.html'),
      content: offlinePage
    },
    {
      path: path.join(publicDir, 'api/hello.json'),
      content: `${JSON.stringify(
        {
          status: true,
          message: 'Hello from Vezham :)'
        },
        null,
        2
      )}\n`
    },
    {
      path: path.join(projectRoot, 'src/generated/vx.ts'),
      content: getGeneratedMetadataModule(config, projectRoot)
    }
  ]
}

export const generateMetadata = (options: GenerateMetadataOptions = {}) => {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd())
  const files = getMetadataFiles(loadVxConfig(projectRoot), projectRoot)

  for (const file of files) {
    const outputPath = options.publicDir
      ? path.join(
          path.resolve(options.publicDir),
          path.relative(path.join(projectRoot, 'public'), file.path)
        )
      : file.path

    writeMetadataFile({
      ...file,
      path: outputPath
    })
  }

  return files.map(file => file.path)
}

export const watchMetadata = (options: GenerateMetadataOptions = {}) => {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd())
  const configFile = path.join(projectRoot, 'vx.config.json')
  const regenerate = () => {
    const files = generateMetadata(options)

    console.log(`Generated ${files.length} metadata files from ${configFile}`)
  }

  regenerate()

  return watch(configFile, { persistent: true }, regenerate)
}
