import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { resolveI18n } from '../i18n.ts'
import { resolveDocsConfig } from '../presets/docs/config.ts'
import { getNextMetadata, getNextViewport } from './next.ts'
import { getRuntimeMetadata } from './runtime.ts'
import { getTanStackHead } from './tanstack.ts'
import { type VxConfig } from './types.ts'

export const generatedNotice = 'Generated by Vx metadata. DO NOT EDIT.'

export const stringifyManifest = (manifest: Record<string, unknown>) =>
  JSON.stringify(manifest, null, 2).replace(
    '"categories": [\n    "productivity",\n    "personalization",\n    "utilities"\n  ]',
    '"categories": ["productivity", "personalization", "utilities"]'
  )

const stringifyTs = (value: unknown) => JSON.stringify(value, null, 2)

export const escapeHtml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')

const metadataTemplatesDir = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'templates'
)

export const renderMetadataTemplate = (
  name: string,
  values: Record<string, string>
) =>
  readFileSync(path.join(metadataTemplatesDir, name), 'utf8')
    .replace(/^[ \t]*<!-- prettier-ignore -->\r?\n/gm, '')
    .replaceAll(/\{\{(\w+)\}\}/g, (_, key: string) => {
      const value = values[key]

      if (value === undefined) {
        throw new Error(`Missing metadata template value: ${key}`)
      }

      return escapeHtml(value)
    })

export const getGeneratedMetadataModule = (
  config: VxConfig,
  projectRoot = process.cwd()
) => `// ${generatedNotice}

export const vxMetadata = ${stringifyTs(getRuntimeMetadata(config, projectRoot))} as const

export const vxCore = ${stringifyTs(config.core)} as const

${config.framework === 'tanstack-docs' ? `export const vxDocs = ${stringifyTs(resolveDocsConfig(config.docs))} as const` : ''}

export const vxI18n = ${stringifyTs(resolveI18n(config.i18n))} as const

export type Locale = (typeof vxI18n.languages)[number]
${
  config.framework === 'next'
    ? `
export const nextMetadata = ${stringifyTs(getNextMetadata(config, projectRoot))}

export const nextViewport = ${stringifyTs(getNextViewport(config, projectRoot))}`
    : config.framework === 'tanstack' || config.framework === 'tanstack-docs'
      ? `
export const tanstackHead = ${stringifyTs(getTanStackHead(config, projectRoot))}`
      : ''
}`
