import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { resolveI18n } from '../i18n.ts'
import { resolveDocsConfig } from '../presets/docs/config.ts'
import { getRuntimeMetadata } from './runtime.ts'
import { type VxConfig } from './types.ts'

type HtmlAttributeValue = boolean | string | undefined

export const generatedNotice = 'Generated by Vx metadata. DO NOT EDIT.'

const indexMetadataStartMarker = '<!-- VX_METADATA_START -->'

const indexMetadataEndMarker = '<!-- VX_METADATA_END -->'

export const stringifyManifest = (manifest: Record<string, unknown>) =>
  JSON.stringify(manifest, null, 2).replace(
    '"categories": [\n    "productivity",\n    "personalization",\n    "utilities"\n  ]',
    '"categories": ["productivity", "personalization", "utilities"]'
  )

const stringifyTs = (value: unknown) => JSON.stringify(value, null, 2)

const escapeHtml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')

const metadataTemplatesDir = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'templates'
)

export const renderMetadataTemplate = (
  name: string,
  values: Record<string, string>
) =>
  readFileSync(path.join(metadataTemplatesDir, name), 'utf8')
    .replace(/^[ \t]*<!-- prettier-ignore -->\r?\n/gm, '')
    .replaceAll(/\{\{(\w+)\}\}/g, (_, key: string) => {
      const value = values[key]

      if (value === undefined) {
        throw new Error(`Missing metadata template value: ${key}`)
      }

      return escapeHtml(value)
    })

const isDefined = <T>(value: T | undefined): value is T => value !== undefined

const normalizeHtmlAttributeName = (name: string) =>
  name === 'charSet' ? 'charset' : name

const renderHtmlAttribute = ([name, value]: [string, HtmlAttributeValue]) => {
  if (value === undefined) {
    return undefined
  }

  if (value === true) {
    return name
  }

  if (value === false) {
    return undefined
  }

  return `${normalizeHtmlAttributeName(name)}="${escapeHtml(value)}"`
}

const renderHtmlTag = (
  tag: string,
  attributes: Record<string, HtmlAttributeValue>,
  indent = '    '
) => {
  const renderedAttributes = Object.entries(attributes)
    .map(renderHtmlAttribute)
    .filter(isDefined)
  const inlineTag = `${indent}<${tag} ${renderedAttributes.join(' ')} />`

  if (inlineTag.length <= 80) {
    return inlineTag
  }

  return `${indent}<${tag}\n${renderedAttributes
    .map(attribute => `${indent}  ${attribute}`)
    .join('\n')} />`
}

const escapeRegex = (value: string) =>
  value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const getTanStackHead = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    meta: [
      { charSet: 'utf-8' },
      {
        name: 'viewport',
        content:
          'width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=1, shrink-to-fit=no'
      },
      { name: 'author', content: metadata.author?.name ?? '' },
      { name: 'keywords', content: metadata.keywords.join(', ') },
      { title: metadata.title },
      { name: 'description', content: metadata.description },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightColor
      },
      {
        name: 'theme-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: light)',
        content: metadata.theme.lightBackgroundColor
      },
      {
        name: 'background-color',
        media: '(prefers-color-scheme: dark)',
        content: metadata.theme.darkBackgroundColor
      },
      {
        name: 'mobile-web-app-capable',
        content: metadata.mobileWebAppCapable ? 'yes' : 'no'
      },
      { name: 'apple-mobile-web-app-title', content: metadata.apple.title },
      {
        name: 'apple-mobile-web-app-capable',
        content: metadata.apple.capable ? 'yes' : 'no'
      },
      {
        name: 'application-name',
        content: metadata.microsoft.applicationName
      },
      {
        name: 'msapplication-config',
        content: metadata.microsoft.config
      },
      {
        name: 'msapplication-starturl',
        content: metadata.microsoft.startUrl
      },
      { property: 'og:type', content: metadata.openGraph.type },
      { property: 'og:title', content: metadata.openGraph.title },
      { property: 'og:description', content: metadata.openGraph.description },
      { property: 'og:image', content: metadata.openGraph.image },
      { property: 'og:url', content: metadata.openGraph.url },
      { name: 'twitter:creator', content: metadata.twitter.creator },
      { name: 'twitter:site', content: metadata.twitter.site },
      { name: 'twitter:title', content: metadata.twitter.title },
      {
        name: 'twitter:description',
        content: metadata.twitter.description
      },
      { name: 'twitter:image', content: metadata.twitter.image },
      { name: 'twitter:url', content: metadata.twitter.url },
      { name: 'twitter:card', content: metadata.twitter.card }
    ],
    links: [
      { rel: 'manifest', href: metadata.manifest },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'icon',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.faviconLight
      },
      {
        rel: 'shortcut icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.faviconDark
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: light)',
        href: metadata.icons.maskIcon,
        color: 'black'
      },
      {
        rel: 'mask-icon',
        media: '(prefers-color-scheme: dark)',
        href: metadata.icons.maskIcon,
        color: 'white'
      },
      {
        rel: 'apple-touch-icon',
        href: metadata.apple.touchIcon
      },
      ...metadata.apple.startupImages.map(image => ({
        rel: 'apple-touch-startup-image',
        media: image.media,
        href: image.url
      }))
    ]
  }
}

const getIndexHtmlMetadataBlock = (
  config: VxConfig,
  projectRoot = process.cwd()
) => {
  const head = getTanStackHead(config, projectRoot)
  const [charsetMeta, ...meta] = head.meta
  const renderHeadMetaEntry = (
    entry: Record<string, HtmlAttributeValue>
  ): string => {
    if (typeof entry.title === 'string') {
      return `    <title>${escapeHtml(entry.title)}</title>`
    }

    return renderHtmlTag('meta', entry)
  }
  const note = (label: string) => `    <!-- wjdlz/NOTE: ${label} -->`
  const isMetaName = (
    entry: Record<string, HtmlAttributeValue>,
    names: string[]
  ) => typeof entry.name === 'string' && names.includes(entry.name)
  const webMeta = meta.filter(
    entry =>
      entry.title ||
      isMetaName(entry, ['viewport', 'author', 'keywords', 'description'])
  )
  const themeMeta = meta.filter(entry =>
    isMetaName(entry, ['theme-color', 'background-color'])
  )
  const mobileMeta = meta.filter(entry =>
    isMetaName(entry, ['mobile-web-app-capable'])
  )
  const appleMeta = meta.filter(
    entry => typeof entry.name === 'string' && entry.name.startsWith('apple-')
  )
  const microsoftMeta = meta.filter(entry =>
    isMetaName(entry, [
      'application-name',
      'msapplication-config',
      'msapplication-starturl'
    ])
  )
  const openGraphMeta = meta.filter(
    entry =>
      typeof entry.property === 'string' && entry.property.startsWith('og:')
  )
  const twitterMeta = meta.filter(
    entry => typeof entry.name === 'string' && entry.name.startsWith('twitter:')
  )
  const pwaLinks = head.links.filter(
    link =>
      link.rel === 'manifest' ||
      link.rel === 'icon' ||
      link.rel === 'shortcut icon' ||
      link.rel === 'mask-icon'
  )
  const appleLinks = head.links.filter(
    link => typeof link.rel === 'string' && link.rel.startsWith('apple-touch-')
  )
  const lines = [
    `    ${indexMetadataStartMarker}`,
    `    <!-- ${generatedNotice} -->`,
    note('WEB'),
    ...(charsetMeta ? [renderHeadMetaEntry(charsetMeta)] : []),
    renderHtmlTag('meta', {
      'http-equiv': 'X-UA-Compatible',
      content: 'IE=edge'
    }),
    ...webMeta.map(renderHeadMetaEntry),
    '',
    note('PWA::THEME'),
    ...themeMeta.map(renderHeadMetaEntry),
    ...pwaLinks.map(link => renderHtmlTag('link', link)),
    '',
    note('PWA::MOBILE'),
    ...mobileMeta.map(renderHeadMetaEntry),
    '',
    note('APPLE'),
    ...appleMeta.map(renderHeadMetaEntry),
    ...appleLinks.map(link => renderHtmlTag('link', link)),
    '',
    note('MICROSOFT'),
    ...microsoftMeta.map(renderHeadMetaEntry),
    '',
    note('META'),
    ...openGraphMeta.map(renderHeadMetaEntry),
    '',
    note('TWITTER'),
    ...twitterMeta.map(renderHeadMetaEntry),
    `    ${indexMetadataEndMarker}`
  ]

  return lines.join('\n')
}

const getPreservedIndexHeadContent = (headContent: string) =>
  headContent
    .split('\n')
    .filter(line => {
      const trimmedLine = line.trim()

      return (
        trimmedLine.startsWith('<base ') || trimmedLine.startsWith('<script ')
      )
    })
    .join('\n')

export const syncIndexHtmlContent = (
  content: string,
  config: VxConfig,
  projectRoot = process.cwd()
) => {
  const metadataBlock = getIndexHtmlMetadataBlock(config, projectRoot)
  const headPattern = /(<head>\n)([\s\S]*?)(\n\s*<\/head>)/
  const headMatch = content.match(headPattern)

  if (!headMatch) {
    throw new Error('Unable to sync Vx metadata because index.html has no head')
  }

  const [, headStart, headContent, headEnd] = headMatch
  const existingBlockPattern = new RegExp(
    `${escapeRegex(`    ${indexMetadataStartMarker}`)}[\\s\\S]*?${escapeRegex(
      `    ${indexMetadataEndMarker}`
    )}`
  )
  const preservedHeadContent = getPreservedIndexHeadContent(
    headContent.replace(existingBlockPattern, '')
  )
  const nextHeadContent = [preservedHeadContent, metadataBlock]
    .filter(Boolean)
    .join('\n\n')

  return content.replace(
    headPattern,
    `${headStart}${nextHeadContent}${headEnd}`
  )
}

const getNextMetadata = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    metadataBase: metadata.url ? new URL(metadata.url) : undefined,
    title: metadata.title,
    description: metadata.description,
    applicationName: metadata.microsoft.applicationName,
    authors: metadata.author?.name
      ? [
          {
            name: metadata.author.name,
            url: metadata.author.url
          }
        ]
      : undefined,
    keywords: metadata.keywords,
    manifest: metadata.manifest,
    icons: {
      icon: [
        {
          url: metadata.icons.faviconLight,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          type: 'image/x-icon',
          media: '(prefers-color-scheme: dark)'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          url: metadata.icons.maskIcon,
          type: 'image/svg+xml',
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ],
      shortcut: [
        {
          url: metadata.icons.faviconLight,
          media: '(prefers-color-scheme: light)'
        },
        {
          url: metadata.icons.faviconDark,
          media: '(prefers-color-scheme: dark)'
        }
      ],
      apple: [{ url: metadata.apple.touchIcon }],
      other: [
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: light)',
          color: 'black'
        },
        {
          rel: 'mask-icon',
          url: metadata.icons.maskIcon,
          media: '(prefers-color-scheme: dark)',
          color: 'white'
        }
      ]
    },
    appleWebApp: {
      title: metadata.apple.title,
      capable: metadata.apple.capable,
      startupImage: metadata.apple.startupImages
    },
    openGraph: {
      type: metadata.openGraph.type,
      title: metadata.openGraph.title,
      description: metadata.openGraph.description,
      images: [metadata.openGraph.image],
      url: metadata.openGraph.url
    },
    twitter: {
      creator: metadata.twitter.creator,
      site: metadata.twitter.site,
      title: metadata.twitter.title,
      description: metadata.twitter.description,
      images: [metadata.twitter.image],
      card: metadata.twitter.card
    },
    other: {
      'mobile-web-app-capable': metadata.mobileWebAppCapable ? 'yes' : 'no',
      'msapplication-config': metadata.microsoft.config,
      'msapplication-starturl': metadata.microsoft.startUrl,
      'twitter:url': metadata.twitter.url
    }
  }
}

const getNextViewport = (config: VxConfig, projectRoot = process.cwd()) => {
  const metadata = getRuntimeMetadata(config, projectRoot)

  return {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1.5,
    userScalable: true,
    themeColor: [
      {
        media: '(prefers-color-scheme: light)',
        color: metadata.theme.lightColor
      },
      {
        media: '(prefers-color-scheme: dark)',
        color: metadata.theme.darkColor
      }
    ]
  }
}

export const getGeneratedMetadataModule = (
  config: VxConfig,
  projectRoot = process.cwd()
) => `// ${generatedNotice}

export const vxMetadata = ${stringifyTs(getRuntimeMetadata(config, projectRoot))} as const

export const vxCore = ${stringifyTs(config.core)} as const

${config.framework === 'tanstack-docs' ? `export const vxDocs = ${stringifyTs(resolveDocsConfig(config.docs))} as const` : ''}

export const vxI18n = ${stringifyTs(resolveI18n(config.i18n))} as const

export type Locale = (typeof vxI18n.languages)[number]
${
  config.framework === 'next'
    ? `
export const nextMetadata = ${stringifyTs(getNextMetadata(config, projectRoot))}

export const nextViewport = ${stringifyTs(getNextViewport(config, projectRoot))}`
    : config.framework === 'tanstack' || config.framework === 'tanstack-docs'
      ? `
export const tanstackHead = ${stringifyTs(getTanStackHead(config, projectRoot))}`
      : ''
}`
