/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const homeRouteLazyRouteImport = createFileRoute('/(home)')()
const homeIndexLazyRouteImport = createFileRoute('/(home)/')()
const homeTeamsRouteLazyRouteImport = createFileRoute('/(home)/teams')()
const homeSharedRouteLazyRouteImport = createFileRoute('/(home)/shared')()
const homeSettingsRouteLazyRouteImport = createFileRoute('/(home)/settings')()
const homeTrashIndexLazyRouteImport = createFileRoute('/(home)/trash/')()
const homeTeamsIndexLazyRouteImport = createFileRoute('/(home)/teams/')()
const homeSharedIndexLazyRouteImport = createFileRoute('/(home)/shared/')()
const homeSettingsIndexLazyRouteImport = createFileRoute('/(home)/settings/')()
const homePinnedIndexLazyRouteImport = createFileRoute('/(home)/pinned/')()
const homeNotificationsIndexLazyRouteImport = createFileRoute(
  '/(home)/notifications/',
)()
const homeFoldersIndexLazyRouteImport = createFileRoute('/(home)/folders/')()
const homeCtaIndexLazyRouteImport = createFileRoute('/(home)/cta/')()
const homeArchivedIndexLazyRouteImport = createFileRoute('/(home)/archived/')()
const homeAllIndexLazyRouteImport = createFileRoute('/(home)/all/')()
const homeTeamsRolesIndexLazyRouteImport = createFileRoute(
  '/(home)/teams/roles/',
)()
const homeTeamsPermissionsIndexLazyRouteImport = createFileRoute(
  '/(home)/teams/permissions/',
)()
const homeTeamsOverviewIndexLazyRouteImport = createFileRoute(
  '/(home)/teams/overview/',
)()
const homeTeamsMembersIndexLazyRouteImport = createFileRoute(
  '/(home)/teams/members/',
)()
const homeSharedSharedWithMeIndexLazyRouteImport = createFileRoute(
  '/(home)/shared/shared-with-me/',
)()
const homeSharedSharedByMeIndexLazyRouteImport = createFileRoute(
  '/(home)/shared/shared-by-me/',
)()
const homeSettingsWorkspaceIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/workspace/',
)()
const homeSettingsTimezoneIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/timezone/',
)()
const homeSettingsSecurityIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/security/',
)()
const homeSettingsIntegrationsIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/integrations/',
)()
const homeSettingsBillingIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/billing/',
)()
const homeSettingsAutomationsIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/automations/',
)()
const homeFoldersFolderIdIndexLazyRouteImport = createFileRoute(
  '/(home)/folders/$folderId/',
)()
const homeCtaHelpSupportIndexLazyRouteImport = createFileRoute(
  '/(home)/cta/help-support/',
)()

const homeRouteLazyRoute = homeRouteLazyRouteImport
  .update({
    id: '/(home)',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(home)/route.lazy').then((d) => d.Route))
const homeIndexLazyRoute = homeIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy').then((d) => d.Route))
const homeTeamsRouteLazyRoute = homeTeamsRouteLazyRouteImport
  .update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/teams/route.lazy').then((d) => d.Route))
const homeSharedRouteLazyRoute = homeSharedRouteLazyRouteImport
  .update({
    id: '/shared',
    path: '/shared',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/shared/route.lazy').then((d) => d.Route))
const homeSettingsRouteLazyRoute = homeSettingsRouteLazyRouteImport
  .update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/settings/route.lazy').then((d) => d.Route),
  )
const homeTrashIndexLazyRoute = homeTrashIndexLazyRouteImport
  .update({
    id: '/trash/',
    path: '/trash/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/trash/index.lazy').then((d) => d.Route))
const homeTeamsIndexLazyRoute = homeTeamsIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeTeamsRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/teams/index.lazy').then((d) => d.Route))
const homeSharedIndexLazyRoute = homeSharedIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeSharedRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/shared/index.lazy').then((d) => d.Route))
const homeSettingsIndexLazyRoute = homeSettingsIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeSettingsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/settings/index.lazy').then((d) => d.Route),
  )
const homePinnedIndexLazyRoute = homePinnedIndexLazyRouteImport
  .update({
    id: '/pinned/',
    path: '/pinned/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/pinned/index.lazy').then((d) => d.Route))
const homeNotificationsIndexLazyRoute = homeNotificationsIndexLazyRouteImport
  .update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/notifications/index.lazy').then((d) => d.Route),
  )
const homeFoldersIndexLazyRoute = homeFoldersIndexLazyRouteImport
  .update({
    id: '/folders/',
    path: '/folders/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/folders/index.lazy').then((d) => d.Route))
const homeCtaIndexLazyRoute = homeCtaIndexLazyRouteImport
  .update({
    id: '/cta/',
    path: '/cta/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/cta/index.lazy').then((d) => d.Route))
const homeArchivedIndexLazyRoute = homeArchivedIndexLazyRouteImport
  .update({
    id: '/archived/',
    path: '/archived/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/archived/index.lazy').then((d) => d.Route),
  )
const homeAllIndexLazyRoute = homeAllIndexLazyRouteImport
  .update({
    id: '/all/',
    path: '/all/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/all/index.lazy').then((d) => d.Route))
const homeTeamsRolesIndexLazyRoute = homeTeamsRolesIndexLazyRouteImport
  .update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => homeTeamsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/teams/roles/index.lazy').then((d) => d.Route),
  )
const homeTeamsPermissionsIndexLazyRoute =
  homeTeamsPermissionsIndexLazyRouteImport
    .update({
      id: '/permissions/',
      path: '/permissions/',
      getParentRoute: () => homeTeamsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/teams/permissions/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeTeamsOverviewIndexLazyRoute = homeTeamsOverviewIndexLazyRouteImport
  .update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => homeTeamsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/teams/overview/index.lazy').then((d) => d.Route),
  )
const homeTeamsMembersIndexLazyRoute = homeTeamsMembersIndexLazyRouteImport
  .update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => homeTeamsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/teams/members/index.lazy').then((d) => d.Route),
  )
const homeSharedSharedWithMeIndexLazyRoute =
  homeSharedSharedWithMeIndexLazyRouteImport
    .update({
      id: '/shared-with-me/',
      path: '/shared-with-me/',
      getParentRoute: () => homeSharedRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/shared/shared-with-me/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSharedSharedByMeIndexLazyRoute =
  homeSharedSharedByMeIndexLazyRouteImport
    .update({
      id: '/shared-by-me/',
      path: '/shared-by-me/',
      getParentRoute: () => homeSharedRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/shared/shared-by-me/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsWorkspaceIndexLazyRoute =
  homeSettingsWorkspaceIndexLazyRouteImport
    .update({
      id: '/workspace/',
      path: '/workspace/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/workspace/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsTimezoneIndexLazyRoute =
  homeSettingsTimezoneIndexLazyRouteImport
    .update({
      id: '/timezone/',
      path: '/timezone/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/timezone/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsSecurityIndexLazyRoute =
  homeSettingsSecurityIndexLazyRouteImport
    .update({
      id: '/security/',
      path: '/security/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/security/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsIntegrationsIndexLazyRoute =
  homeSettingsIntegrationsIndexLazyRouteImport
    .update({
      id: '/integrations/',
      path: '/integrations/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/integrations/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsBillingIndexLazyRoute =
  homeSettingsBillingIndexLazyRouteImport
    .update({
      id: '/billing/',
      path: '/billing/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/billing/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsAutomationsIndexLazyRoute =
  homeSettingsAutomationsIndexLazyRouteImport
    .update({
      id: '/automations/',
      path: '/automations/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/automations/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeFoldersFolderIdIndexLazyRoute =
  homeFoldersFolderIdIndexLazyRouteImport
    .update({
      id: '/folders/$folderId/',
      path: '/folders/$folderId/',
      getParentRoute: () => homeRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/folders/$folderId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeCtaHelpSupportIndexLazyRoute = homeCtaHelpSupportIndexLazyRouteImport
  .update({
    id: '/cta/help-support/',
    path: '/cta/help-support/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/cta/help-support/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof homeIndexLazyRoute
  '/settings': typeof homeSettingsRouteLazyRouteWithChildren
  '/shared': typeof homeSharedRouteLazyRouteWithChildren
  '/teams': typeof homeTeamsRouteLazyRouteWithChildren
  '/all': typeof homeAllIndexLazyRoute
  '/archived': typeof homeArchivedIndexLazyRoute
  '/cta': typeof homeCtaIndexLazyRoute
  '/folders': typeof homeFoldersIndexLazyRoute
  '/notifications': typeof homeNotificationsIndexLazyRoute
  '/pinned': typeof homePinnedIndexLazyRoute
  '/settings/': typeof homeSettingsIndexLazyRoute
  '/shared/': typeof homeSharedIndexLazyRoute
  '/teams/': typeof homeTeamsIndexLazyRoute
  '/trash': typeof homeTrashIndexLazyRoute
  '/cta/help-support': typeof homeCtaHelpSupportIndexLazyRoute
  '/folders/$folderId': typeof homeFoldersFolderIdIndexLazyRoute
  '/settings/automations': typeof homeSettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof homeSettingsBillingIndexLazyRoute
  '/settings/integrations': typeof homeSettingsIntegrationsIndexLazyRoute
  '/settings/security': typeof homeSettingsSecurityIndexLazyRoute
  '/settings/timezone': typeof homeSettingsTimezoneIndexLazyRoute
  '/settings/workspace': typeof homeSettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me': typeof homeSharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me': typeof homeSharedSharedWithMeIndexLazyRoute
  '/teams/members': typeof homeTeamsMembersIndexLazyRoute
  '/teams/overview': typeof homeTeamsOverviewIndexLazyRoute
  '/teams/permissions': typeof homeTeamsPermissionsIndexLazyRoute
  '/teams/roles': typeof homeTeamsRolesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexLazyRoute
  '/all': typeof homeAllIndexLazyRoute
  '/archived': typeof homeArchivedIndexLazyRoute
  '/cta': typeof homeCtaIndexLazyRoute
  '/folders': typeof homeFoldersIndexLazyRoute
  '/notifications': typeof homeNotificationsIndexLazyRoute
  '/pinned': typeof homePinnedIndexLazyRoute
  '/settings': typeof homeSettingsIndexLazyRoute
  '/shared': typeof homeSharedIndexLazyRoute
  '/teams': typeof homeTeamsIndexLazyRoute
  '/trash': typeof homeTrashIndexLazyRoute
  '/cta/help-support': typeof homeCtaHelpSupportIndexLazyRoute
  '/folders/$folderId': typeof homeFoldersFolderIdIndexLazyRoute
  '/settings/automations': typeof homeSettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof homeSettingsBillingIndexLazyRoute
  '/settings/integrations': typeof homeSettingsIntegrationsIndexLazyRoute
  '/settings/security': typeof homeSettingsSecurityIndexLazyRoute
  '/settings/timezone': typeof homeSettingsTimezoneIndexLazyRoute
  '/settings/workspace': typeof homeSettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me': typeof homeSharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me': typeof homeSharedSharedWithMeIndexLazyRoute
  '/teams/members': typeof homeTeamsMembersIndexLazyRoute
  '/teams/overview': typeof homeTeamsOverviewIndexLazyRoute
  '/teams/permissions': typeof homeTeamsPermissionsIndexLazyRoute
  '/teams/roles': typeof homeTeamsRolesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteLazyRouteWithChildren
  '/(home)/settings': typeof homeSettingsRouteLazyRouteWithChildren
  '/(home)/shared': typeof homeSharedRouteLazyRouteWithChildren
  '/(home)/teams': typeof homeTeamsRouteLazyRouteWithChildren
  '/(home)/': typeof homeIndexLazyRoute
  '/(home)/all/': typeof homeAllIndexLazyRoute
  '/(home)/archived/': typeof homeArchivedIndexLazyRoute
  '/(home)/cta/': typeof homeCtaIndexLazyRoute
  '/(home)/folders/': typeof homeFoldersIndexLazyRoute
  '/(home)/notifications/': typeof homeNotificationsIndexLazyRoute
  '/(home)/pinned/': typeof homePinnedIndexLazyRoute
  '/(home)/settings/': typeof homeSettingsIndexLazyRoute
  '/(home)/shared/': typeof homeSharedIndexLazyRoute
  '/(home)/teams/': typeof homeTeamsIndexLazyRoute
  '/(home)/trash/': typeof homeTrashIndexLazyRoute
  '/(home)/cta/help-support/': typeof homeCtaHelpSupportIndexLazyRoute
  '/(home)/folders/$folderId/': typeof homeFoldersFolderIdIndexLazyRoute
  '/(home)/settings/automations/': typeof homeSettingsAutomationsIndexLazyRoute
  '/(home)/settings/billing/': typeof homeSettingsBillingIndexLazyRoute
  '/(home)/settings/integrations/': typeof homeSettingsIntegrationsIndexLazyRoute
  '/(home)/settings/security/': typeof homeSettingsSecurityIndexLazyRoute
  '/(home)/settings/timezone/': typeof homeSettingsTimezoneIndexLazyRoute
  '/(home)/settings/workspace/': typeof homeSettingsWorkspaceIndexLazyRoute
  '/(home)/shared/shared-by-me/': typeof homeSharedSharedByMeIndexLazyRoute
  '/(home)/shared/shared-with-me/': typeof homeSharedSharedWithMeIndexLazyRoute
  '/(home)/teams/members/': typeof homeTeamsMembersIndexLazyRoute
  '/(home)/teams/overview/': typeof homeTeamsOverviewIndexLazyRoute
  '/(home)/teams/permissions/': typeof homeTeamsPermissionsIndexLazyRoute
  '/(home)/teams/roles/': typeof homeTeamsRolesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/all'
    | '/archived'
    | '/cta'
    | '/folders'
    | '/notifications'
    | '/pinned'
    | '/settings/'
    | '/shared/'
    | '/teams/'
    | '/trash'
    | '/cta/help-support'
    | '/folders/$folderId'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/security'
    | '/settings/timezone'
    | '/settings/workspace'
    | '/shared/shared-by-me'
    | '/shared/shared-with-me'
    | '/teams/members'
    | '/teams/overview'
    | '/teams/permissions'
    | '/teams/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/archived'
    | '/cta'
    | '/folders'
    | '/notifications'
    | '/pinned'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/trash'
    | '/cta/help-support'
    | '/folders/$folderId'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/security'
    | '/settings/timezone'
    | '/settings/workspace'
    | '/shared/shared-by-me'
    | '/shared/shared-with-me'
    | '/teams/members'
    | '/teams/overview'
    | '/teams/permissions'
    | '/teams/roles'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/settings'
    | '/(home)/shared'
    | '/(home)/teams'
    | '/(home)/'
    | '/(home)/all/'
    | '/(home)/archived/'
    | '/(home)/cta/'
    | '/(home)/folders/'
    | '/(home)/notifications/'
    | '/(home)/pinned/'
    | '/(home)/settings/'
    | '/(home)/shared/'
    | '/(home)/teams/'
    | '/(home)/trash/'
    | '/(home)/cta/help-support/'
    | '/(home)/folders/$folderId/'
    | '/(home)/settings/automations/'
    | '/(home)/settings/billing/'
    | '/(home)/settings/integrations/'
    | '/(home)/settings/security/'
    | '/(home)/settings/timezone/'
    | '/(home)/settings/workspace/'
    | '/(home)/shared/shared-by-me/'
    | '/(home)/shared/shared-with-me/'
    | '/(home)/teams/members/'
    | '/(home)/teams/overview/'
    | '/(home)/teams/permissions/'
    | '/(home)/teams/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteLazyRoute: typeof homeRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/teams': {
      id: '/(home)/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof homeTeamsRouteLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/shared': {
      id: '/(home)/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof homeSharedRouteLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/settings': {
      id: '/(home)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof homeSettingsRouteLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/trash/': {
      id: '/(home)/trash/'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof homeTrashIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/teams/': {
      id: '/(home)/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof homeTeamsIndexLazyRouteImport
      parentRoute: typeof homeTeamsRouteLazyRoute
    }
    '/(home)/shared/': {
      id: '/(home)/shared/'
      path: '/'
      fullPath: '/shared/'
      preLoaderRoute: typeof homeSharedIndexLazyRouteImport
      parentRoute: typeof homeSharedRouteLazyRoute
    }
    '/(home)/settings/': {
      id: '/(home)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof homeSettingsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/pinned/': {
      id: '/(home)/pinned/'
      path: '/pinned'
      fullPath: '/pinned'
      preLoaderRoute: typeof homePinnedIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/notifications/': {
      id: '/(home)/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof homeNotificationsIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/folders/': {
      id: '/(home)/folders/'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof homeFoldersIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/cta/': {
      id: '/(home)/cta/'
      path: '/cta'
      fullPath: '/cta'
      preLoaderRoute: typeof homeCtaIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/archived/': {
      id: '/(home)/archived/'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof homeArchivedIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/all/': {
      id: '/(home)/all/'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof homeAllIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/teams/roles/': {
      id: '/(home)/teams/roles/'
      path: '/roles'
      fullPath: '/teams/roles'
      preLoaderRoute: typeof homeTeamsRolesIndexLazyRouteImport
      parentRoute: typeof homeTeamsRouteLazyRoute
    }
    '/(home)/teams/permissions/': {
      id: '/(home)/teams/permissions/'
      path: '/permissions'
      fullPath: '/teams/permissions'
      preLoaderRoute: typeof homeTeamsPermissionsIndexLazyRouteImport
      parentRoute: typeof homeTeamsRouteLazyRoute
    }
    '/(home)/teams/overview/': {
      id: '/(home)/teams/overview/'
      path: '/overview'
      fullPath: '/teams/overview'
      preLoaderRoute: typeof homeTeamsOverviewIndexLazyRouteImport
      parentRoute: typeof homeTeamsRouteLazyRoute
    }
    '/(home)/teams/members/': {
      id: '/(home)/teams/members/'
      path: '/members'
      fullPath: '/teams/members'
      preLoaderRoute: typeof homeTeamsMembersIndexLazyRouteImport
      parentRoute: typeof homeTeamsRouteLazyRoute
    }
    '/(home)/shared/shared-with-me/': {
      id: '/(home)/shared/shared-with-me/'
      path: '/shared-with-me'
      fullPath: '/shared/shared-with-me'
      preLoaderRoute: typeof homeSharedSharedWithMeIndexLazyRouteImport
      parentRoute: typeof homeSharedRouteLazyRoute
    }
    '/(home)/shared/shared-by-me/': {
      id: '/(home)/shared/shared-by-me/'
      path: '/shared-by-me'
      fullPath: '/shared/shared-by-me'
      preLoaderRoute: typeof homeSharedSharedByMeIndexLazyRouteImport
      parentRoute: typeof homeSharedRouteLazyRoute
    }
    '/(home)/settings/workspace/': {
      id: '/(home)/settings/workspace/'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof homeSettingsWorkspaceIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/timezone/': {
      id: '/(home)/settings/timezone/'
      path: '/timezone'
      fullPath: '/settings/timezone'
      preLoaderRoute: typeof homeSettingsTimezoneIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/security/': {
      id: '/(home)/settings/security/'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof homeSettingsSecurityIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/integrations/': {
      id: '/(home)/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof homeSettingsIntegrationsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/billing/': {
      id: '/(home)/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof homeSettingsBillingIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/automations/': {
      id: '/(home)/settings/automations/'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof homeSettingsAutomationsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/folders/$folderId/': {
      id: '/(home)/folders/$folderId/'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof homeFoldersFolderIdIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/cta/help-support/': {
      id: '/(home)/cta/help-support/'
      path: '/cta/help-support'
      fullPath: '/cta/help-support'
      preLoaderRoute: typeof homeCtaHelpSupportIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
  }
}

interface homeSettingsRouteLazyRouteChildren {
  homeSettingsIndexLazyRoute: typeof homeSettingsIndexLazyRoute
  homeSettingsAutomationsIndexLazyRoute: typeof homeSettingsAutomationsIndexLazyRoute
  homeSettingsBillingIndexLazyRoute: typeof homeSettingsBillingIndexLazyRoute
  homeSettingsIntegrationsIndexLazyRoute: typeof homeSettingsIntegrationsIndexLazyRoute
  homeSettingsSecurityIndexLazyRoute: typeof homeSettingsSecurityIndexLazyRoute
  homeSettingsTimezoneIndexLazyRoute: typeof homeSettingsTimezoneIndexLazyRoute
  homeSettingsWorkspaceIndexLazyRoute: typeof homeSettingsWorkspaceIndexLazyRoute
}

const homeSettingsRouteLazyRouteChildren: homeSettingsRouteLazyRouteChildren = {
  homeSettingsIndexLazyRoute: homeSettingsIndexLazyRoute,
  homeSettingsAutomationsIndexLazyRoute: homeSettingsAutomationsIndexLazyRoute,
  homeSettingsBillingIndexLazyRoute: homeSettingsBillingIndexLazyRoute,
  homeSettingsIntegrationsIndexLazyRoute:
    homeSettingsIntegrationsIndexLazyRoute,
  homeSettingsSecurityIndexLazyRoute: homeSettingsSecurityIndexLazyRoute,
  homeSettingsTimezoneIndexLazyRoute: homeSettingsTimezoneIndexLazyRoute,
  homeSettingsWorkspaceIndexLazyRoute: homeSettingsWorkspaceIndexLazyRoute,
}

const homeSettingsRouteLazyRouteWithChildren =
  homeSettingsRouteLazyRoute._addFileChildren(
    homeSettingsRouteLazyRouteChildren,
  )

interface homeSharedRouteLazyRouteChildren {
  homeSharedIndexLazyRoute: typeof homeSharedIndexLazyRoute
  homeSharedSharedByMeIndexLazyRoute: typeof homeSharedSharedByMeIndexLazyRoute
  homeSharedSharedWithMeIndexLazyRoute: typeof homeSharedSharedWithMeIndexLazyRoute
}

const homeSharedRouteLazyRouteChildren: homeSharedRouteLazyRouteChildren = {
  homeSharedIndexLazyRoute: homeSharedIndexLazyRoute,
  homeSharedSharedByMeIndexLazyRoute: homeSharedSharedByMeIndexLazyRoute,
  homeSharedSharedWithMeIndexLazyRoute: homeSharedSharedWithMeIndexLazyRoute,
}

const homeSharedRouteLazyRouteWithChildren =
  homeSharedRouteLazyRoute._addFileChildren(homeSharedRouteLazyRouteChildren)

interface homeTeamsRouteLazyRouteChildren {
  homeTeamsIndexLazyRoute: typeof homeTeamsIndexLazyRoute
  homeTeamsMembersIndexLazyRoute: typeof homeTeamsMembersIndexLazyRoute
  homeTeamsOverviewIndexLazyRoute: typeof homeTeamsOverviewIndexLazyRoute
  homeTeamsPermissionsIndexLazyRoute: typeof homeTeamsPermissionsIndexLazyRoute
  homeTeamsRolesIndexLazyRoute: typeof homeTeamsRolesIndexLazyRoute
}

const homeTeamsRouteLazyRouteChildren: homeTeamsRouteLazyRouteChildren = {
  homeTeamsIndexLazyRoute: homeTeamsIndexLazyRoute,
  homeTeamsMembersIndexLazyRoute: homeTeamsMembersIndexLazyRoute,
  homeTeamsOverviewIndexLazyRoute: homeTeamsOverviewIndexLazyRoute,
  homeTeamsPermissionsIndexLazyRoute: homeTeamsPermissionsIndexLazyRoute,
  homeTeamsRolesIndexLazyRoute: homeTeamsRolesIndexLazyRoute,
}

const homeTeamsRouteLazyRouteWithChildren =
  homeTeamsRouteLazyRoute._addFileChildren(homeTeamsRouteLazyRouteChildren)

interface homeRouteLazyRouteChildren {
  homeSettingsRouteLazyRoute: typeof homeSettingsRouteLazyRouteWithChildren
  homeSharedRouteLazyRoute: typeof homeSharedRouteLazyRouteWithChildren
  homeTeamsRouteLazyRoute: typeof homeTeamsRouteLazyRouteWithChildren
  homeIndexLazyRoute: typeof homeIndexLazyRoute
  homeAllIndexLazyRoute: typeof homeAllIndexLazyRoute
  homeArchivedIndexLazyRoute: typeof homeArchivedIndexLazyRoute
  homeCtaIndexLazyRoute: typeof homeCtaIndexLazyRoute
  homeFoldersIndexLazyRoute: typeof homeFoldersIndexLazyRoute
  homeNotificationsIndexLazyRoute: typeof homeNotificationsIndexLazyRoute
  homePinnedIndexLazyRoute: typeof homePinnedIndexLazyRoute
  homeTrashIndexLazyRoute: typeof homeTrashIndexLazyRoute
  homeCtaHelpSupportIndexLazyRoute: typeof homeCtaHelpSupportIndexLazyRoute
  homeFoldersFolderIdIndexLazyRoute: typeof homeFoldersFolderIdIndexLazyRoute
}

const homeRouteLazyRouteChildren: homeRouteLazyRouteChildren = {
  homeSettingsRouteLazyRoute: homeSettingsRouteLazyRouteWithChildren,
  homeSharedRouteLazyRoute: homeSharedRouteLazyRouteWithChildren,
  homeTeamsRouteLazyRoute: homeTeamsRouteLazyRouteWithChildren,
  homeIndexLazyRoute: homeIndexLazyRoute,
  homeAllIndexLazyRoute: homeAllIndexLazyRoute,
  homeArchivedIndexLazyRoute: homeArchivedIndexLazyRoute,
  homeCtaIndexLazyRoute: homeCtaIndexLazyRoute,
  homeFoldersIndexLazyRoute: homeFoldersIndexLazyRoute,
  homeNotificationsIndexLazyRoute: homeNotificationsIndexLazyRoute,
  homePinnedIndexLazyRoute: homePinnedIndexLazyRoute,
  homeTrashIndexLazyRoute: homeTrashIndexLazyRoute,
  homeCtaHelpSupportIndexLazyRoute: homeCtaHelpSupportIndexLazyRoute,
  homeFoldersFolderIdIndexLazyRoute: homeFoldersFolderIdIndexLazyRoute,
}

const homeRouteLazyRouteWithChildren = homeRouteLazyRoute._addFileChildren(
  homeRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteLazyRoute: homeRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
