/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TeamsRouteLazyRouteImport = createFileRoute('/teams')()
const SharedRouteLazyRouteImport = createFileRoute('/shared')()
const SettingsRouteLazyRouteImport = createFileRoute('/settings')()
const IndexLazyRouteImport = createFileRoute('/')()
const TrashIndexLazyRouteImport = createFileRoute('/trash/')()
const TeamsIndexLazyRouteImport = createFileRoute('/teams/')()
const SharedIndexLazyRouteImport = createFileRoute('/shared/')()
const SettingsIndexLazyRouteImport = createFileRoute('/settings/')()
const PinnedIndexLazyRouteImport = createFileRoute('/pinned/')()
const NotificationsIndexLazyRouteImport = createFileRoute('/notifications/')()
const FoldersIndexLazyRouteImport = createFileRoute('/folders/')()
const CtaIndexLazyRouteImport = createFileRoute('/cta/')()
const ArchivedIndexLazyRouteImport = createFileRoute('/archived/')()
const AllIndexLazyRouteImport = createFileRoute('/all/')()
const TeamsRolesIndexLazyRouteImport = createFileRoute('/teams/roles/')()
const TeamsPermissionsIndexLazyRouteImport = createFileRoute(
  '/teams/permissions/',
)()
const TeamsOverviewIndexLazyRouteImport = createFileRoute('/teams/overview/')()
const TeamsMembersIndexLazyRouteImport = createFileRoute('/teams/members/')()
const SharedSharedWithMeIndexLazyRouteImport = createFileRoute(
  '/shared/shared-with-me/',
)()
const SharedSharedByMeIndexLazyRouteImport = createFileRoute(
  '/shared/shared-by-me/',
)()
const SettingsWorkspaceIndexLazyRouteImport = createFileRoute(
  '/settings/workspace/',
)()
const SettingsTimezoneIndexLazyRouteImport = createFileRoute(
  '/settings/timezone/',
)()
const SettingsSecurityIndexLazyRouteImport = createFileRoute(
  '/settings/security/',
)()
const SettingsIntegrationsIndexLazyRouteImport = createFileRoute(
  '/settings/integrations/',
)()
const SettingsBillingIndexLazyRouteImport =
  createFileRoute('/settings/billing/')()
const SettingsAutomationsIndexLazyRouteImport = createFileRoute(
  '/settings/automations/',
)()
const FoldersSubfoldersIndexLazyRouteImport = createFileRoute(
  '/folders/subfolders/',
)()
const FoldersFolderIdIndexLazyRouteImport = createFileRoute(
  '/folders/$folderId/',
)()
const CtaHelpSupportIndexLazyRouteImport =
  createFileRoute('/cta/help-support/')()
const FoldersSubfoldersSubfolderIdIndexLazyRouteImport = createFileRoute(
  '/folders/subfolders/$subfolderId/',
)()

const TeamsRouteLazyRoute = TeamsRouteLazyRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams/route.lazy').then((d) => d.Route))
const SharedRouteLazyRoute = SharedRouteLazyRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/shared/route.lazy').then((d) => d.Route))
const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TrashIndexLazyRoute = TrashIndexLazyRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trash/index.lazy').then((d) => d.Route))
const TeamsIndexLazyRoute = TeamsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() => import('./routes/teams/index.lazy').then((d) => d.Route))
const SharedIndexLazyRoute = SharedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRouteLazyRoute,
} as any).lazy(() => import('./routes/shared/index.lazy').then((d) => d.Route))
const SettingsIndexLazyRoute = SettingsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/index.lazy').then((d) => d.Route),
)
const PinnedIndexLazyRoute = PinnedIndexLazyRouteImport.update({
  id: '/pinned/',
  path: '/pinned/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pinned/index.lazy').then((d) => d.Route))
const NotificationsIndexLazyRoute = NotificationsIndexLazyRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/notifications/index.lazy').then((d) => d.Route),
)
const FoldersIndexLazyRoute = FoldersIndexLazyRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/folders/index.lazy').then((d) => d.Route))
const CtaIndexLazyRoute = CtaIndexLazyRouteImport.update({
  id: '/cta/',
  path: '/cta/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cta/index.lazy').then((d) => d.Route))
const ArchivedIndexLazyRoute = ArchivedIndexLazyRouteImport.update({
  id: '/archived/',
  path: '/archived/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/archived/index.lazy').then((d) => d.Route),
)
const AllIndexLazyRoute = AllIndexLazyRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/all/index.lazy').then((d) => d.Route))
const TeamsRolesIndexLazyRoute = TeamsRolesIndexLazyRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/roles/index.lazy').then((d) => d.Route),
)
const TeamsPermissionsIndexLazyRoute =
  TeamsPermissionsIndexLazyRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => TeamsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/teams/permissions/index.lazy').then((d) => d.Route),
  )
const TeamsOverviewIndexLazyRoute = TeamsOverviewIndexLazyRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/overview/index.lazy').then((d) => d.Route),
)
const TeamsMembersIndexLazyRoute = TeamsMembersIndexLazyRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/members/index.lazy').then((d) => d.Route),
)
const SharedSharedWithMeIndexLazyRoute =
  SharedSharedWithMeIndexLazyRouteImport.update({
    id: '/shared-with-me/',
    path: '/shared-with-me/',
    getParentRoute: () => SharedRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/shared/shared-with-me/index.lazy').then((d) => d.Route),
  )
const SharedSharedByMeIndexLazyRoute =
  SharedSharedByMeIndexLazyRouteImport.update({
    id: '/shared-by-me/',
    path: '/shared-by-me/',
    getParentRoute: () => SharedRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/shared/shared-by-me/index.lazy').then((d) => d.Route),
  )
const SettingsWorkspaceIndexLazyRoute =
  SettingsWorkspaceIndexLazyRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/workspace/index.lazy').then((d) => d.Route),
  )
const SettingsTimezoneIndexLazyRoute =
  SettingsTimezoneIndexLazyRouteImport.update({
    id: '/timezone/',
    path: '/timezone/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/timezone/index.lazy').then((d) => d.Route),
  )
const SettingsSecurityIndexLazyRoute =
  SettingsSecurityIndexLazyRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/security/index.lazy').then((d) => d.Route),
  )
const SettingsIntegrationsIndexLazyRoute =
  SettingsIntegrationsIndexLazyRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/integrations/index.lazy').then((d) => d.Route),
  )
const SettingsBillingIndexLazyRoute =
  SettingsBillingIndexLazyRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/billing/index.lazy').then((d) => d.Route),
  )
const SettingsAutomationsIndexLazyRoute =
  SettingsAutomationsIndexLazyRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/automations/index.lazy').then((d) => d.Route),
  )
const FoldersSubfoldersIndexLazyRoute =
  FoldersSubfoldersIndexLazyRouteImport.update({
    id: '/folders/subfolders/',
    path: '/folders/subfolders/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/folders/subfolders/index.lazy').then((d) => d.Route),
  )
const FoldersFolderIdIndexLazyRoute =
  FoldersFolderIdIndexLazyRouteImport.update({
    id: '/folders/$folderId/',
    path: '/folders/$folderId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/folders/$folderId/index.lazy').then((d) => d.Route),
  )
const CtaHelpSupportIndexLazyRoute = CtaHelpSupportIndexLazyRouteImport.update({
  id: '/cta/help-support/',
  path: '/cta/help-support/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/cta/help-support/index.lazy').then((d) => d.Route),
)
const FoldersSubfoldersSubfolderIdIndexLazyRoute =
  FoldersSubfoldersSubfolderIdIndexLazyRouteImport.update({
    id: '/folders/subfolders/$subfolderId/',
    path: '/folders/subfolders/$subfolderId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/folders/subfolders/$subfolderId/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/shared': typeof SharedRouteLazyRouteWithChildren
  '/teams': typeof TeamsRouteLazyRouteWithChildren
  '/all/': typeof AllIndexLazyRoute
  '/archived/': typeof ArchivedIndexLazyRoute
  '/cta/': typeof CtaIndexLazyRoute
  '/folders/': typeof FoldersIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/pinned/': typeof PinnedIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/shared/': typeof SharedIndexLazyRoute
  '/teams/': typeof TeamsIndexLazyRoute
  '/trash/': typeof TrashIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/folders/$folderId/': typeof FoldersFolderIdIndexLazyRoute
  '/folders/subfolders/': typeof FoldersSubfoldersIndexLazyRoute
  '/settings/automations/': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing/': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security/': typeof SettingsSecurityIndexLazyRoute
  '/settings/timezone/': typeof SettingsTimezoneIndexLazyRoute
  '/settings/workspace/': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me/': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me/': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members/': typeof TeamsMembersIndexLazyRoute
  '/teams/overview/': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions/': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles/': typeof TeamsRolesIndexLazyRoute
  '/folders/subfolders/$subfolderId/': typeof FoldersSubfoldersSubfolderIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/all': typeof AllIndexLazyRoute
  '/archived': typeof ArchivedIndexLazyRoute
  '/cta': typeof CtaIndexLazyRoute
  '/folders': typeof FoldersIndexLazyRoute
  '/notifications': typeof NotificationsIndexLazyRoute
  '/pinned': typeof PinnedIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
  '/shared': typeof SharedIndexLazyRoute
  '/teams': typeof TeamsIndexLazyRoute
  '/trash': typeof TrashIndexLazyRoute
  '/cta/help-support': typeof CtaHelpSupportIndexLazyRoute
  '/folders/$folderId': typeof FoldersFolderIdIndexLazyRoute
  '/folders/subfolders': typeof FoldersSubfoldersIndexLazyRoute
  '/settings/automations': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security': typeof SettingsSecurityIndexLazyRoute
  '/settings/timezone': typeof SettingsTimezoneIndexLazyRoute
  '/settings/workspace': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members': typeof TeamsMembersIndexLazyRoute
  '/teams/overview': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles': typeof TeamsRolesIndexLazyRoute
  '/folders/subfolders/$subfolderId': typeof FoldersSubfoldersSubfolderIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/shared': typeof SharedRouteLazyRouteWithChildren
  '/teams': typeof TeamsRouteLazyRouteWithChildren
  '/all/': typeof AllIndexLazyRoute
  '/archived/': typeof ArchivedIndexLazyRoute
  '/cta/': typeof CtaIndexLazyRoute
  '/folders/': typeof FoldersIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/pinned/': typeof PinnedIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/shared/': typeof SharedIndexLazyRoute
  '/teams/': typeof TeamsIndexLazyRoute
  '/trash/': typeof TrashIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/folders/$folderId/': typeof FoldersFolderIdIndexLazyRoute
  '/folders/subfolders/': typeof FoldersSubfoldersIndexLazyRoute
  '/settings/automations/': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing/': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security/': typeof SettingsSecurityIndexLazyRoute
  '/settings/timezone/': typeof SettingsTimezoneIndexLazyRoute
  '/settings/workspace/': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me/': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me/': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members/': typeof TeamsMembersIndexLazyRoute
  '/teams/overview/': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions/': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles/': typeof TeamsRolesIndexLazyRoute
  '/folders/subfolders/$subfolderId/': typeof FoldersSubfoldersSubfolderIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/all/'
    | '/archived/'
    | '/cta/'
    | '/folders/'
    | '/notifications/'
    | '/pinned/'
    | '/settings/'
    | '/shared/'
    | '/teams/'
    | '/trash/'
    | '/cta/help-support/'
    | '/folders/$folderId/'
    | '/folders/subfolders/'
    | '/settings/automations/'
    | '/settings/billing/'
    | '/settings/integrations/'
    | '/settings/security/'
    | '/settings/timezone/'
    | '/settings/workspace/'
    | '/shared/shared-by-me/'
    | '/shared/shared-with-me/'
    | '/teams/members/'
    | '/teams/overview/'
    | '/teams/permissions/'
    | '/teams/roles/'
    | '/folders/subfolders/$subfolderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/archived'
    | '/cta'
    | '/folders'
    | '/notifications'
    | '/pinned'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/trash'
    | '/cta/help-support'
    | '/folders/$folderId'
    | '/folders/subfolders'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/security'
    | '/settings/timezone'
    | '/settings/workspace'
    | '/shared/shared-by-me'
    | '/shared/shared-with-me'
    | '/teams/members'
    | '/teams/overview'
    | '/teams/permissions'
    | '/teams/roles'
    | '/folders/subfolders/$subfolderId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/all/'
    | '/archived/'
    | '/cta/'
    | '/folders/'
    | '/notifications/'
    | '/pinned/'
    | '/settings/'
    | '/shared/'
    | '/teams/'
    | '/trash/'
    | '/cta/help-support/'
    | '/folders/$folderId/'
    | '/folders/subfolders/'
    | '/settings/automations/'
    | '/settings/billing/'
    | '/settings/integrations/'
    | '/settings/security/'
    | '/settings/timezone/'
    | '/settings/workspace/'
    | '/shared/shared-by-me/'
    | '/shared/shared-with-me/'
    | '/teams/members/'
    | '/teams/overview/'
    | '/teams/permissions/'
    | '/teams/roles/'
    | '/folders/subfolders/$subfolderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  SharedRouteLazyRoute: typeof SharedRouteLazyRouteWithChildren
  TeamsRouteLazyRoute: typeof TeamsRouteLazyRouteWithChildren
  AllIndexLazyRoute: typeof AllIndexLazyRoute
  ArchivedIndexLazyRoute: typeof ArchivedIndexLazyRoute
  CtaIndexLazyRoute: typeof CtaIndexLazyRoute
  FoldersIndexLazyRoute: typeof FoldersIndexLazyRoute
  NotificationsIndexLazyRoute: typeof NotificationsIndexLazyRoute
  PinnedIndexLazyRoute: typeof PinnedIndexLazyRoute
  TrashIndexLazyRoute: typeof TrashIndexLazyRoute
  CtaHelpSupportIndexLazyRoute: typeof CtaHelpSupportIndexLazyRoute
  FoldersFolderIdIndexLazyRoute: typeof FoldersFolderIdIndexLazyRoute
  FoldersSubfoldersIndexLazyRoute: typeof FoldersSubfoldersIndexLazyRoute
  FoldersSubfoldersSubfolderIdIndexLazyRoute: typeof FoldersSubfoldersSubfolderIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash/': {
      id: '/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof TrashIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/shared/': {
      id: '/shared/'
      path: '/'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/pinned/': {
      id: '/pinned/'
      path: '/pinned'
      fullPath: '/pinned/'
      preLoaderRoute: typeof PinnedIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cta/': {
      id: '/cta/'
      path: '/cta'
      fullPath: '/cta/'
      preLoaderRoute: typeof CtaIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived/': {
      id: '/archived/'
      path: '/archived'
      fullPath: '/archived/'
      preLoaderRoute: typeof ArchivedIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/': {
      id: '/all/'
      path: '/all'
      fullPath: '/all/'
      preLoaderRoute: typeof AllIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/roles/': {
      id: '/teams/roles/'
      path: '/roles'
      fullPath: '/teams/roles/'
      preLoaderRoute: typeof TeamsRolesIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/permissions/': {
      id: '/teams/permissions/'
      path: '/permissions'
      fullPath: '/teams/permissions/'
      preLoaderRoute: typeof TeamsPermissionsIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/overview/': {
      id: '/teams/overview/'
      path: '/overview'
      fullPath: '/teams/overview/'
      preLoaderRoute: typeof TeamsOverviewIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/members/': {
      id: '/teams/members/'
      path: '/members'
      fullPath: '/teams/members/'
      preLoaderRoute: typeof TeamsMembersIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/shared/shared-with-me/': {
      id: '/shared/shared-with-me/'
      path: '/shared-with-me'
      fullPath: '/shared/shared-with-me/'
      preLoaderRoute: typeof SharedSharedWithMeIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/shared/shared-by-me/': {
      id: '/shared/shared-by-me/'
      path: '/shared-by-me'
      fullPath: '/shared/shared-by-me/'
      preLoaderRoute: typeof SharedSharedByMeIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/settings/workspace/': {
      id: '/settings/workspace/'
      path: '/workspace'
      fullPath: '/settings/workspace/'
      preLoaderRoute: typeof SettingsWorkspaceIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/timezone/': {
      id: '/settings/timezone/'
      path: '/timezone'
      fullPath: '/settings/timezone/'
      preLoaderRoute: typeof SettingsTimezoneIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/security/': {
      id: '/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof SettingsSecurityIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/integrations/': {
      id: '/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof SettingsIntegrationsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/billing/': {
      id: '/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof SettingsBillingIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/automations/': {
      id: '/settings/automations/'
      path: '/automations'
      fullPath: '/settings/automations/'
      preLoaderRoute: typeof SettingsAutomationsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/folders/subfolders/': {
      id: '/folders/subfolders/'
      path: '/folders/subfolders'
      fullPath: '/folders/subfolders/'
      preLoaderRoute: typeof FoldersSubfoldersIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId/': {
      id: '/folders/$folderId/'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId/'
      preLoaderRoute: typeof FoldersFolderIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cta/help-support/': {
      id: '/cta/help-support/'
      path: '/cta/help-support'
      fullPath: '/cta/help-support/'
      preLoaderRoute: typeof CtaHelpSupportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/subfolders/$subfolderId/': {
      id: '/folders/subfolders/$subfolderId/'
      path: '/folders/subfolders/$subfolderId'
      fullPath: '/folders/subfolders/$subfolderId/'
      preLoaderRoute: typeof FoldersSubfoldersSubfolderIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteLazyRouteChildren {
  SettingsIndexLazyRoute: typeof SettingsIndexLazyRoute
  SettingsAutomationsIndexLazyRoute: typeof SettingsAutomationsIndexLazyRoute
  SettingsBillingIndexLazyRoute: typeof SettingsBillingIndexLazyRoute
  SettingsIntegrationsIndexLazyRoute: typeof SettingsIntegrationsIndexLazyRoute
  SettingsSecurityIndexLazyRoute: typeof SettingsSecurityIndexLazyRoute
  SettingsTimezoneIndexLazyRoute: typeof SettingsTimezoneIndexLazyRoute
  SettingsWorkspaceIndexLazyRoute: typeof SettingsWorkspaceIndexLazyRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsIndexLazyRoute: SettingsIndexLazyRoute,
  SettingsAutomationsIndexLazyRoute: SettingsAutomationsIndexLazyRoute,
  SettingsBillingIndexLazyRoute: SettingsBillingIndexLazyRoute,
  SettingsIntegrationsIndexLazyRoute: SettingsIntegrationsIndexLazyRoute,
  SettingsSecurityIndexLazyRoute: SettingsSecurityIndexLazyRoute,
  SettingsTimezoneIndexLazyRoute: SettingsTimezoneIndexLazyRoute,
  SettingsWorkspaceIndexLazyRoute: SettingsWorkspaceIndexLazyRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

interface SharedRouteLazyRouteChildren {
  SharedIndexLazyRoute: typeof SharedIndexLazyRoute
  SharedSharedByMeIndexLazyRoute: typeof SharedSharedByMeIndexLazyRoute
  SharedSharedWithMeIndexLazyRoute: typeof SharedSharedWithMeIndexLazyRoute
}

const SharedRouteLazyRouteChildren: SharedRouteLazyRouteChildren = {
  SharedIndexLazyRoute: SharedIndexLazyRoute,
  SharedSharedByMeIndexLazyRoute: SharedSharedByMeIndexLazyRoute,
  SharedSharedWithMeIndexLazyRoute: SharedSharedWithMeIndexLazyRoute,
}

const SharedRouteLazyRouteWithChildren = SharedRouteLazyRoute._addFileChildren(
  SharedRouteLazyRouteChildren,
)

interface TeamsRouteLazyRouteChildren {
  TeamsIndexLazyRoute: typeof TeamsIndexLazyRoute
  TeamsMembersIndexLazyRoute: typeof TeamsMembersIndexLazyRoute
  TeamsOverviewIndexLazyRoute: typeof TeamsOverviewIndexLazyRoute
  TeamsPermissionsIndexLazyRoute: typeof TeamsPermissionsIndexLazyRoute
  TeamsRolesIndexLazyRoute: typeof TeamsRolesIndexLazyRoute
}

const TeamsRouteLazyRouteChildren: TeamsRouteLazyRouteChildren = {
  TeamsIndexLazyRoute: TeamsIndexLazyRoute,
  TeamsMembersIndexLazyRoute: TeamsMembersIndexLazyRoute,
  TeamsOverviewIndexLazyRoute: TeamsOverviewIndexLazyRoute,
  TeamsPermissionsIndexLazyRoute: TeamsPermissionsIndexLazyRoute,
  TeamsRolesIndexLazyRoute: TeamsRolesIndexLazyRoute,
}

const TeamsRouteLazyRouteWithChildren = TeamsRouteLazyRoute._addFileChildren(
  TeamsRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  SharedRouteLazyRoute: SharedRouteLazyRouteWithChildren,
  TeamsRouteLazyRoute: TeamsRouteLazyRouteWithChildren,
  AllIndexLazyRoute: AllIndexLazyRoute,
  ArchivedIndexLazyRoute: ArchivedIndexLazyRoute,
  CtaIndexLazyRoute: CtaIndexLazyRoute,
  FoldersIndexLazyRoute: FoldersIndexLazyRoute,
  NotificationsIndexLazyRoute: NotificationsIndexLazyRoute,
  PinnedIndexLazyRoute: PinnedIndexLazyRoute,
  TrashIndexLazyRoute: TrashIndexLazyRoute,
  CtaHelpSupportIndexLazyRoute: CtaHelpSupportIndexLazyRoute,
  FoldersFolderIdIndexLazyRoute: FoldersFolderIdIndexLazyRoute,
  FoldersSubfoldersIndexLazyRoute: FoldersSubfoldersIndexLazyRoute,
  FoldersSubfoldersSubfolderIdIndexLazyRoute:
    FoldersSubfoldersSubfolderIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
