/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessDemoRouteImport } from './routes/_pathless-demo'
import { Route as DemoRouteImport } from './routes/_demo'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as AnchorIndexRouteImport } from './routes/anchor/index'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as PathlessDemoDemo2IndexRouteImport } from './routes/_pathless-demo/demo-2/index'
import { Route as PathlessDemoDemo1IndexRouteImport } from './routes/_pathless-demo/demo-1/index'
import { Route as DemoDemoIndexRouteImport } from './routes/_demo/demo/index'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const IndexLazyRouteImport = createFileRoute('/')()

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessDemoRoute = PathlessDemoRouteImport.update({
  id: '/_pathless-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const AnchorIndexRoute = AnchorIndexRouteImport.update({
  id: '/anchor/',
  path: '/anchor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PathlessDemoDemo2IndexRoute = PathlessDemoDemo2IndexRouteImport.update({
  id: '/demo-2/',
  path: '/demo-2/',
  getParentRoute: () => PathlessDemoRoute,
} as any)
const PathlessDemoDemo1IndexRoute = PathlessDemoDemo1IndexRouteImport.update({
  id: '/demo-1/',
  path: '/demo-1/',
  getParentRoute: () => PathlessDemoRoute,
} as any)
const DemoDemoIndexRoute = DemoDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => DemoRoute,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/anchor': typeof AnchorIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/demo': typeof DemoDemoIndexRoute
  '/demo-1': typeof PathlessDemoDemo1IndexRoute
  '/demo-2': typeof PathlessDemoDemo2IndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/anchor': typeof AnchorIndexRoute
  '/posts': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/demo': typeof DemoDemoIndexRoute
  '/demo-1': typeof PathlessDemoDemo1IndexRoute
  '/demo-2': typeof PathlessDemoDemo2IndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_demo': typeof DemoRouteWithChildren
  '/_pathless-demo': typeof PathlessDemoRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/anchor/': typeof AnchorIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/_demo/demo/': typeof DemoDemoIndexRoute
  '/_pathless-demo/demo-1/': typeof PathlessDemoDemo1IndexRoute
  '/_pathless-demo/demo-2/': typeof PathlessDemoDemo2IndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/anchor'
    | '/posts/'
    | '/route-a'
    | '/route-b'
    | '/demo'
    | '/demo-1'
    | '/demo-2'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anchor'
    | '/posts'
    | '/route-a'
    | '/route-b'
    | '/demo'
    | '/demo-1'
    | '/demo-2'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_demo'
    | '/_pathless-demo'
    | '/_pathlessLayout'
    | '/_pathlessLayout/_nested-layout'
    | '/anchor/'
    | '/posts/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/_demo/demo/'
    | '/_pathless-demo/demo-1/'
    | '/_pathless-demo/demo-2/'
    | '/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  PathlessDemoRoute: typeof PathlessDemoRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AnchorIndexRoute: typeof AnchorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-demo': {
      id: '/_pathless-demo'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/anchor/': {
      id: '/anchor/'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_pathless-demo/demo-2/': {
      id: '/_pathless-demo/demo-2/'
      path: '/demo-2'
      fullPath: '/demo-2'
      preLoaderRoute: typeof PathlessDemoDemo2IndexRouteImport
      parentRoute: typeof PathlessDemoRoute
    }
    '/_pathless-demo/demo-1/': {
      id: '/_pathless-demo/demo-1/'
      path: '/demo-1'
      fullPath: '/demo-1'
      preLoaderRoute: typeof PathlessDemoDemo1IndexRouteImport
      parentRoute: typeof PathlessDemoRoute
    }
    '/_demo/demo/': {
      id: '/_demo/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoDemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface DemoRouteChildren {
  DemoDemoIndexRoute: typeof DemoDemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDemoIndexRoute: DemoDemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface PathlessDemoRouteChildren {
  PathlessDemoDemo1IndexRoute: typeof PathlessDemoDemo1IndexRoute
  PathlessDemoDemo2IndexRoute: typeof PathlessDemoDemo2IndexRoute
}

const PathlessDemoRouteChildren: PathlessDemoRouteChildren = {
  PathlessDemoDemo1IndexRoute: PathlessDemoDemo1IndexRoute,
  PathlessDemoDemo2IndexRoute: PathlessDemoDemo2IndexRoute,
}

const PathlessDemoRouteWithChildren = PathlessDemoRoute._addFileChildren(
  PathlessDemoRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  PathlessDemoRoute: PathlessDemoRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AnchorIndexRoute: AnchorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
