/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const homeRouteLazyRouteImport = createFileRoute('/(home)')()
const homeIndexLazyRouteImport = createFileRoute('/(home)/')()
const homeSettingsRouteLazyRouteImport = createFileRoute('/(home)/settings')()
const homeTrashIndexLazyRouteImport = createFileRoute('/(home)/trash/')()
const homeTodayIndexLazyRouteImport = createFileRoute('/(home)/today/')()
const homeTagsIndexLazyRouteImport = createFileRoute('/(home)/tags/')()
const homeSettingsIndexLazyRouteImport = createFileRoute('/(home)/settings/')()
const homeScheduledIndexLazyRouteImport =
  createFileRoute('/(home)/scheduled/')()
const homeListsIndexLazyRouteImport = createFileRoute('/(home)/lists/')()
const homeFlaggedIndexLazyRouteImport = createFileRoute('/(home)/flagged/')()
const homeCtaIndexLazyRouteImport = createFileRoute('/(home)/cta/')()
const homeCompletedIndexLazyRouteImport =
  createFileRoute('/(home)/completed/')()
const homeArchiveIndexLazyRouteImport = createFileRoute('/(home)/archive/')()
const homeAllIndexLazyRouteImport = createFileRoute('/(home)/all/')()
const homeReminderIdIndexLazyRouteImport = createFileRoute(
  '/(home)/$reminderId/',
)()
const homeSettingsWorkspaceIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/workspace/',
)()
const homeSettingsUsersIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/users/',
)()
const homeSettingsSecurityIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/security/',
)()
const homeSettingsNotificationsIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/notifications/',
)()
const homeSettingsBillingIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/billing/',
)()
const homeSettingsAutomationsIndexLazyRouteImport = createFileRoute(
  '/(home)/settings/automations/',
)()
const homeListsListIdIndexLazyRouteImport = createFileRoute(
  '/(home)/lists/$listId/',
)()
const homeCtaHelpSupportIndexLazyRouteImport = createFileRoute(
  '/(home)/cta/help-support/',
)()

const homeRouteLazyRoute = homeRouteLazyRouteImport
  .update({
    id: '/(home)',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(home)/route.lazy').then((d) => d.Route))
const homeIndexLazyRoute = homeIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy').then((d) => d.Route))
const homeSettingsRouteLazyRoute = homeSettingsRouteLazyRouteImport
  .update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/settings/route.lazy').then((d) => d.Route),
  )
const homeTrashIndexLazyRoute = homeTrashIndexLazyRouteImport
  .update({
    id: '/trash/',
    path: '/trash/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/trash/index.lazy').then((d) => d.Route))
const homeTodayIndexLazyRoute = homeTodayIndexLazyRouteImport
  .update({
    id: '/today/',
    path: '/today/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/today/index.lazy').then((d) => d.Route))
const homeTagsIndexLazyRoute = homeTagsIndexLazyRouteImport
  .update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/tags/index.lazy').then((d) => d.Route))
const homeSettingsIndexLazyRoute = homeSettingsIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => homeSettingsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/settings/index.lazy').then((d) => d.Route),
  )
const homeScheduledIndexLazyRoute = homeScheduledIndexLazyRouteImport
  .update({
    id: '/scheduled/',
    path: '/scheduled/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/scheduled/index.lazy').then((d) => d.Route),
  )
const homeListsIndexLazyRoute = homeListsIndexLazyRouteImport
  .update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/lists/index.lazy').then((d) => d.Route))
const homeFlaggedIndexLazyRoute = homeFlaggedIndexLazyRouteImport
  .update({
    id: '/flagged/',
    path: '/flagged/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/flagged/index.lazy').then((d) => d.Route))
const homeCtaIndexLazyRoute = homeCtaIndexLazyRouteImport
  .update({
    id: '/cta/',
    path: '/cta/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/cta/index.lazy').then((d) => d.Route))
const homeCompletedIndexLazyRoute = homeCompletedIndexLazyRouteImport
  .update({
    id: '/completed/',
    path: '/completed/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/completed/index.lazy').then((d) => d.Route),
  )
const homeArchiveIndexLazyRoute = homeArchiveIndexLazyRouteImport
  .update({
    id: '/archive/',
    path: '/archive/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/archive/index.lazy').then((d) => d.Route))
const homeAllIndexLazyRoute = homeAllIndexLazyRouteImport
  .update({
    id: '/all/',
    path: '/all/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(home)/all/index.lazy').then((d) => d.Route))
const homeReminderIdIndexLazyRoute = homeReminderIdIndexLazyRouteImport
  .update({
    id: '/$reminderId/',
    path: '/$reminderId/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/$reminderId/index.lazy').then((d) => d.Route),
  )
const homeSettingsWorkspaceIndexLazyRoute =
  homeSettingsWorkspaceIndexLazyRouteImport
    .update({
      id: '/workspace/',
      path: '/workspace/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/workspace/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsUsersIndexLazyRoute = homeSettingsUsersIndexLazyRouteImport
  .update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => homeSettingsRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/settings/users/index.lazy').then((d) => d.Route),
  )
const homeSettingsSecurityIndexLazyRoute =
  homeSettingsSecurityIndexLazyRouteImport
    .update({
      id: '/security/',
      path: '/security/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/security/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsNotificationsIndexLazyRoute =
  homeSettingsNotificationsIndexLazyRouteImport
    .update({
      id: '/notifications/',
      path: '/notifications/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/notifications/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsBillingIndexLazyRoute =
  homeSettingsBillingIndexLazyRouteImport
    .update({
      id: '/billing/',
      path: '/billing/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/billing/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeSettingsAutomationsIndexLazyRoute =
  homeSettingsAutomationsIndexLazyRouteImport
    .update({
      id: '/automations/',
      path: '/automations/',
      getParentRoute: () => homeSettingsRouteLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(home)/settings/automations/index.lazy').then(
        (d) => d.Route,
      ),
    )
const homeListsListIdIndexLazyRoute = homeListsListIdIndexLazyRouteImport
  .update({
    id: '/lists/$listId/',
    path: '/lists/$listId/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/lists/$listId/index.lazy').then((d) => d.Route),
  )
const homeCtaHelpSupportIndexLazyRoute = homeCtaHelpSupportIndexLazyRouteImport
  .update({
    id: '/cta/help-support/',
    path: '/cta/help-support/',
    getParentRoute: () => homeRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(home)/cta/help-support/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof homeIndexLazyRoute
  '/settings': typeof homeSettingsRouteLazyRouteWithChildren
  '/$reminderId': typeof homeReminderIdIndexLazyRoute
  '/all': typeof homeAllIndexLazyRoute
  '/archive': typeof homeArchiveIndexLazyRoute
  '/completed': typeof homeCompletedIndexLazyRoute
  '/cta': typeof homeCtaIndexLazyRoute
  '/flagged': typeof homeFlaggedIndexLazyRoute
  '/lists': typeof homeListsIndexLazyRoute
  '/scheduled': typeof homeScheduledIndexLazyRoute
  '/settings/': typeof homeSettingsIndexLazyRoute
  '/tags': typeof homeTagsIndexLazyRoute
  '/today': typeof homeTodayIndexLazyRoute
  '/trash': typeof homeTrashIndexLazyRoute
  '/cta/help-support': typeof homeCtaHelpSupportIndexLazyRoute
  '/lists/$listId': typeof homeListsListIdIndexLazyRoute
  '/settings/automations': typeof homeSettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof homeSettingsBillingIndexLazyRoute
  '/settings/notifications': typeof homeSettingsNotificationsIndexLazyRoute
  '/settings/security': typeof homeSettingsSecurityIndexLazyRoute
  '/settings/users': typeof homeSettingsUsersIndexLazyRoute
  '/settings/workspace': typeof homeSettingsWorkspaceIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexLazyRoute
  '/$reminderId': typeof homeReminderIdIndexLazyRoute
  '/all': typeof homeAllIndexLazyRoute
  '/archive': typeof homeArchiveIndexLazyRoute
  '/completed': typeof homeCompletedIndexLazyRoute
  '/cta': typeof homeCtaIndexLazyRoute
  '/flagged': typeof homeFlaggedIndexLazyRoute
  '/lists': typeof homeListsIndexLazyRoute
  '/scheduled': typeof homeScheduledIndexLazyRoute
  '/settings': typeof homeSettingsIndexLazyRoute
  '/tags': typeof homeTagsIndexLazyRoute
  '/today': typeof homeTodayIndexLazyRoute
  '/trash': typeof homeTrashIndexLazyRoute
  '/cta/help-support': typeof homeCtaHelpSupportIndexLazyRoute
  '/lists/$listId': typeof homeListsListIdIndexLazyRoute
  '/settings/automations': typeof homeSettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof homeSettingsBillingIndexLazyRoute
  '/settings/notifications': typeof homeSettingsNotificationsIndexLazyRoute
  '/settings/security': typeof homeSettingsSecurityIndexLazyRoute
  '/settings/users': typeof homeSettingsUsersIndexLazyRoute
  '/settings/workspace': typeof homeSettingsWorkspaceIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteLazyRouteWithChildren
  '/(home)/settings': typeof homeSettingsRouteLazyRouteWithChildren
  '/(home)/': typeof homeIndexLazyRoute
  '/(home)/$reminderId/': typeof homeReminderIdIndexLazyRoute
  '/(home)/all/': typeof homeAllIndexLazyRoute
  '/(home)/archive/': typeof homeArchiveIndexLazyRoute
  '/(home)/completed/': typeof homeCompletedIndexLazyRoute
  '/(home)/cta/': typeof homeCtaIndexLazyRoute
  '/(home)/flagged/': typeof homeFlaggedIndexLazyRoute
  '/(home)/lists/': typeof homeListsIndexLazyRoute
  '/(home)/scheduled/': typeof homeScheduledIndexLazyRoute
  '/(home)/settings/': typeof homeSettingsIndexLazyRoute
  '/(home)/tags/': typeof homeTagsIndexLazyRoute
  '/(home)/today/': typeof homeTodayIndexLazyRoute
  '/(home)/trash/': typeof homeTrashIndexLazyRoute
  '/(home)/cta/help-support/': typeof homeCtaHelpSupportIndexLazyRoute
  '/(home)/lists/$listId/': typeof homeListsListIdIndexLazyRoute
  '/(home)/settings/automations/': typeof homeSettingsAutomationsIndexLazyRoute
  '/(home)/settings/billing/': typeof homeSettingsBillingIndexLazyRoute
  '/(home)/settings/notifications/': typeof homeSettingsNotificationsIndexLazyRoute
  '/(home)/settings/security/': typeof homeSettingsSecurityIndexLazyRoute
  '/(home)/settings/users/': typeof homeSettingsUsersIndexLazyRoute
  '/(home)/settings/workspace/': typeof homeSettingsWorkspaceIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$reminderId'
    | '/all'
    | '/archive'
    | '/completed'
    | '/cta'
    | '/flagged'
    | '/lists'
    | '/scheduled'
    | '/settings/'
    | '/tags'
    | '/today'
    | '/trash'
    | '/cta/help-support'
    | '/lists/$listId'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/users'
    | '/settings/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$reminderId'
    | '/all'
    | '/archive'
    | '/completed'
    | '/cta'
    | '/flagged'
    | '/lists'
    | '/scheduled'
    | '/settings'
    | '/tags'
    | '/today'
    | '/trash'
    | '/cta/help-support'
    | '/lists/$listId'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/users'
    | '/settings/workspace'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/settings'
    | '/(home)/'
    | '/(home)/$reminderId/'
    | '/(home)/all/'
    | '/(home)/archive/'
    | '/(home)/completed/'
    | '/(home)/cta/'
    | '/(home)/flagged/'
    | '/(home)/lists/'
    | '/(home)/scheduled/'
    | '/(home)/settings/'
    | '/(home)/tags/'
    | '/(home)/today/'
    | '/(home)/trash/'
    | '/(home)/cta/help-support/'
    | '/(home)/lists/$listId/'
    | '/(home)/settings/automations/'
    | '/(home)/settings/billing/'
    | '/(home)/settings/notifications/'
    | '/(home)/settings/security/'
    | '/(home)/settings/users/'
    | '/(home)/settings/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteLazyRoute: typeof homeRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/settings': {
      id: '/(home)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof homeSettingsRouteLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/trash/': {
      id: '/(home)/trash/'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof homeTrashIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/today/': {
      id: '/(home)/today/'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof homeTodayIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/tags/': {
      id: '/(home)/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof homeTagsIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/settings/': {
      id: '/(home)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof homeSettingsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/scheduled/': {
      id: '/(home)/scheduled/'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof homeScheduledIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/lists/': {
      id: '/(home)/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof homeListsIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/flagged/': {
      id: '/(home)/flagged/'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof homeFlaggedIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/cta/': {
      id: '/(home)/cta/'
      path: '/cta'
      fullPath: '/cta'
      preLoaderRoute: typeof homeCtaIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/completed/': {
      id: '/(home)/completed/'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof homeCompletedIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/archive/': {
      id: '/(home)/archive/'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof homeArchiveIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/all/': {
      id: '/(home)/all/'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof homeAllIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/$reminderId/': {
      id: '/(home)/$reminderId/'
      path: '/$reminderId'
      fullPath: '/$reminderId'
      preLoaderRoute: typeof homeReminderIdIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/settings/workspace/': {
      id: '/(home)/settings/workspace/'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof homeSettingsWorkspaceIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/users/': {
      id: '/(home)/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof homeSettingsUsersIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/security/': {
      id: '/(home)/settings/security/'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof homeSettingsSecurityIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/notifications/': {
      id: '/(home)/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof homeSettingsNotificationsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/billing/': {
      id: '/(home)/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof homeSettingsBillingIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/settings/automations/': {
      id: '/(home)/settings/automations/'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof homeSettingsAutomationsIndexLazyRouteImport
      parentRoute: typeof homeSettingsRouteLazyRoute
    }
    '/(home)/lists/$listId/': {
      id: '/(home)/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof homeListsListIdIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
    '/(home)/cta/help-support/': {
      id: '/(home)/cta/help-support/'
      path: '/cta/help-support'
      fullPath: '/cta/help-support'
      preLoaderRoute: typeof homeCtaHelpSupportIndexLazyRouteImport
      parentRoute: typeof homeRouteLazyRoute
    }
  }
}

interface homeSettingsRouteLazyRouteChildren {
  homeSettingsIndexLazyRoute: typeof homeSettingsIndexLazyRoute
  homeSettingsAutomationsIndexLazyRoute: typeof homeSettingsAutomationsIndexLazyRoute
  homeSettingsBillingIndexLazyRoute: typeof homeSettingsBillingIndexLazyRoute
  homeSettingsNotificationsIndexLazyRoute: typeof homeSettingsNotificationsIndexLazyRoute
  homeSettingsSecurityIndexLazyRoute: typeof homeSettingsSecurityIndexLazyRoute
  homeSettingsUsersIndexLazyRoute: typeof homeSettingsUsersIndexLazyRoute
  homeSettingsWorkspaceIndexLazyRoute: typeof homeSettingsWorkspaceIndexLazyRoute
}

const homeSettingsRouteLazyRouteChildren: homeSettingsRouteLazyRouteChildren = {
  homeSettingsIndexLazyRoute: homeSettingsIndexLazyRoute,
  homeSettingsAutomationsIndexLazyRoute: homeSettingsAutomationsIndexLazyRoute,
  homeSettingsBillingIndexLazyRoute: homeSettingsBillingIndexLazyRoute,
  homeSettingsNotificationsIndexLazyRoute:
    homeSettingsNotificationsIndexLazyRoute,
  homeSettingsSecurityIndexLazyRoute: homeSettingsSecurityIndexLazyRoute,
  homeSettingsUsersIndexLazyRoute: homeSettingsUsersIndexLazyRoute,
  homeSettingsWorkspaceIndexLazyRoute: homeSettingsWorkspaceIndexLazyRoute,
}

const homeSettingsRouteLazyRouteWithChildren =
  homeSettingsRouteLazyRoute._addFileChildren(
    homeSettingsRouteLazyRouteChildren,
  )

interface homeRouteLazyRouteChildren {
  homeSettingsRouteLazyRoute: typeof homeSettingsRouteLazyRouteWithChildren
  homeIndexLazyRoute: typeof homeIndexLazyRoute
  homeReminderIdIndexLazyRoute: typeof homeReminderIdIndexLazyRoute
  homeAllIndexLazyRoute: typeof homeAllIndexLazyRoute
  homeArchiveIndexLazyRoute: typeof homeArchiveIndexLazyRoute
  homeCompletedIndexLazyRoute: typeof homeCompletedIndexLazyRoute
  homeCtaIndexLazyRoute: typeof homeCtaIndexLazyRoute
  homeFlaggedIndexLazyRoute: typeof homeFlaggedIndexLazyRoute
  homeListsIndexLazyRoute: typeof homeListsIndexLazyRoute
  homeScheduledIndexLazyRoute: typeof homeScheduledIndexLazyRoute
  homeTagsIndexLazyRoute: typeof homeTagsIndexLazyRoute
  homeTodayIndexLazyRoute: typeof homeTodayIndexLazyRoute
  homeTrashIndexLazyRoute: typeof homeTrashIndexLazyRoute
  homeCtaHelpSupportIndexLazyRoute: typeof homeCtaHelpSupportIndexLazyRoute
  homeListsListIdIndexLazyRoute: typeof homeListsListIdIndexLazyRoute
}

const homeRouteLazyRouteChildren: homeRouteLazyRouteChildren = {
  homeSettingsRouteLazyRoute: homeSettingsRouteLazyRouteWithChildren,
  homeIndexLazyRoute: homeIndexLazyRoute,
  homeReminderIdIndexLazyRoute: homeReminderIdIndexLazyRoute,
  homeAllIndexLazyRoute: homeAllIndexLazyRoute,
  homeArchiveIndexLazyRoute: homeArchiveIndexLazyRoute,
  homeCompletedIndexLazyRoute: homeCompletedIndexLazyRoute,
  homeCtaIndexLazyRoute: homeCtaIndexLazyRoute,
  homeFlaggedIndexLazyRoute: homeFlaggedIndexLazyRoute,
  homeListsIndexLazyRoute: homeListsIndexLazyRoute,
  homeScheduledIndexLazyRoute: homeScheduledIndexLazyRoute,
  homeTagsIndexLazyRoute: homeTagsIndexLazyRoute,
  homeTodayIndexLazyRoute: homeTodayIndexLazyRoute,
  homeTrashIndexLazyRoute: homeTrashIndexLazyRoute,
  homeCtaHelpSupportIndexLazyRoute: homeCtaHelpSupportIndexLazyRoute,
  homeListsListIdIndexLazyRoute: homeListsListIdIndexLazyRoute,
}

const homeRouteLazyRouteWithChildren = homeRouteLazyRoute._addFileChildren(
  homeRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteLazyRoute: homeRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
