/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TeamsRouteLazyRouteImport = createFileRoute('/teams')()
const SharedRouteLazyRouteImport = createFileRoute('/shared')()
const SettingsRouteLazyRouteImport = createFileRoute('/settings')()
const IndexLazyRouteImport = createFileRoute('/')()
const TeamsIndexLazyRouteImport = createFileRoute('/teams/')()
const SharedIndexLazyRouteImport = createFileRoute('/shared/')()
const SettingsIndexLazyRouteImport = createFileRoute('/settings/')()
const RecentIndexLazyRouteImport = createFileRoute('/recent/')()
const NotificationsIndexLazyRouteImport = createFileRoute('/notifications/')()
const ImportExportIndexLazyRouteImport = createFileRoute('/import-export/')()
const GroupsIndexLazyRouteImport = createFileRoute('/groups/')()
const FavoritesIndexLazyRouteImport = createFileRoute('/favorites/')()
const CtaIndexLazyRouteImport = createFileRoute('/cta/')()
const UserContactIdIndexLazyRouteImport = createFileRoute('/user/$contactId/')()
const TeamsRolesIndexLazyRouteImport = createFileRoute('/teams/roles/')()
const TeamsPermissionsIndexLazyRouteImport = createFileRoute(
  '/teams/permissions/',
)()
const TeamsOverviewIndexLazyRouteImport = createFileRoute('/teams/overview/')()
const TeamsMembersIndexLazyRouteImport = createFileRoute('/teams/members/')()
const SharedSharedWithMeIndexLazyRouteImport = createFileRoute(
  '/shared/shared-with-me/',
)()
const SharedSharedByMeIndexLazyRouteImport = createFileRoute(
  '/shared/shared-by-me/',
)()
const SettingsWorkspaceIndexLazyRouteImport = createFileRoute(
  '/settings/workspace/',
)()
const SettingsSecurityIndexLazyRouteImport = createFileRoute(
  '/settings/security/',
)()
const SettingsIntegrationsIndexLazyRouteImport = createFileRoute(
  '/settings/integrations/',
)()
const SettingsBillingIndexLazyRouteImport =
  createFileRoute('/settings/billing/')()
const SettingsAutomationsIndexLazyRouteImport = createFileRoute(
  '/settings/automations/',
)()
const GroupsGroupIdIndexLazyRouteImport = createFileRoute('/groups/$groupId/')()
const CtaHelpSupportIndexLazyRouteImport =
  createFileRoute('/cta/help-support/')()

const TeamsRouteLazyRoute = TeamsRouteLazyRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams/route.lazy').then((d) => d.Route))
const SharedRouteLazyRoute = SharedRouteLazyRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/shared/route.lazy').then((d) => d.Route))
const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TeamsIndexLazyRoute = TeamsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() => import('./routes/teams/index.lazy').then((d) => d.Route))
const SharedIndexLazyRoute = SharedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRouteLazyRoute,
} as any).lazy(() => import('./routes/shared/index.lazy').then((d) => d.Route))
const SettingsIndexLazyRoute = SettingsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/index.lazy').then((d) => d.Route),
)
const RecentIndexLazyRoute = RecentIndexLazyRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recent/index.lazy').then((d) => d.Route))
const NotificationsIndexLazyRoute = NotificationsIndexLazyRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/notifications/index.lazy').then((d) => d.Route),
)
const ImportExportIndexLazyRoute = ImportExportIndexLazyRouteImport.update({
  id: '/import-export/',
  path: '/import-export/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/import-export/index.lazy').then((d) => d.Route),
)
const GroupsIndexLazyRoute = GroupsIndexLazyRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/groups/index.lazy').then((d) => d.Route))
const FavoritesIndexLazyRoute = FavoritesIndexLazyRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/favorites/index.lazy').then((d) => d.Route),
)
const CtaIndexLazyRoute = CtaIndexLazyRouteImport.update({
  id: '/cta/',
  path: '/cta/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cta/index.lazy').then((d) => d.Route))
const UserContactIdIndexLazyRoute = UserContactIdIndexLazyRouteImport.update({
  id: '/user/$contactId/',
  path: '/user/$contactId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/user/$contactId/index.lazy').then((d) => d.Route),
)
const TeamsRolesIndexLazyRoute = TeamsRolesIndexLazyRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/roles/index.lazy').then((d) => d.Route),
)
const TeamsPermissionsIndexLazyRoute =
  TeamsPermissionsIndexLazyRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => TeamsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/teams/permissions/index.lazy').then((d) => d.Route),
  )
const TeamsOverviewIndexLazyRoute = TeamsOverviewIndexLazyRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/overview/index.lazy').then((d) => d.Route),
)
const TeamsMembersIndexLazyRoute = TeamsMembersIndexLazyRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => TeamsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/teams/members/index.lazy').then((d) => d.Route),
)
const SharedSharedWithMeIndexLazyRoute =
  SharedSharedWithMeIndexLazyRouteImport.update({
    id: '/shared-with-me/',
    path: '/shared-with-me/',
    getParentRoute: () => SharedRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/shared/shared-with-me/index.lazy').then((d) => d.Route),
  )
const SharedSharedByMeIndexLazyRoute =
  SharedSharedByMeIndexLazyRouteImport.update({
    id: '/shared-by-me/',
    path: '/shared-by-me/',
    getParentRoute: () => SharedRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/shared/shared-by-me/index.lazy').then((d) => d.Route),
  )
const SettingsWorkspaceIndexLazyRoute =
  SettingsWorkspaceIndexLazyRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/workspace/index.lazy').then((d) => d.Route),
  )
const SettingsSecurityIndexLazyRoute =
  SettingsSecurityIndexLazyRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/security/index.lazy').then((d) => d.Route),
  )
const SettingsIntegrationsIndexLazyRoute =
  SettingsIntegrationsIndexLazyRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/integrations/index.lazy').then((d) => d.Route),
  )
const SettingsBillingIndexLazyRoute =
  SettingsBillingIndexLazyRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/billing/index.lazy').then((d) => d.Route),
  )
const SettingsAutomationsIndexLazyRoute =
  SettingsAutomationsIndexLazyRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/automations/index.lazy').then((d) => d.Route),
  )
const GroupsGroupIdIndexLazyRoute = GroupsGroupIdIndexLazyRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/groups/$groupId/index.lazy').then((d) => d.Route),
)
const CtaHelpSupportIndexLazyRoute = CtaHelpSupportIndexLazyRouteImport.update({
  id: '/cta/help-support/',
  path: '/cta/help-support/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/cta/help-support/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/shared': typeof SharedRouteLazyRouteWithChildren
  '/teams': typeof TeamsRouteLazyRouteWithChildren
  '/cta/': typeof CtaIndexLazyRoute
  '/favorites/': typeof FavoritesIndexLazyRoute
  '/groups/': typeof GroupsIndexLazyRoute
  '/import-export/': typeof ImportExportIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/recent/': typeof RecentIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/shared/': typeof SharedIndexLazyRoute
  '/teams/': typeof TeamsIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexLazyRoute
  '/settings/automations/': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing/': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security/': typeof SettingsSecurityIndexLazyRoute
  '/settings/workspace/': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me/': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me/': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members/': typeof TeamsMembersIndexLazyRoute
  '/teams/overview/': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions/': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles/': typeof TeamsRolesIndexLazyRoute
  '/user/$contactId/': typeof UserContactIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cta': typeof CtaIndexLazyRoute
  '/favorites': typeof FavoritesIndexLazyRoute
  '/groups': typeof GroupsIndexLazyRoute
  '/import-export': typeof ImportExportIndexLazyRoute
  '/notifications': typeof NotificationsIndexLazyRoute
  '/recent': typeof RecentIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
  '/shared': typeof SharedIndexLazyRoute
  '/teams': typeof TeamsIndexLazyRoute
  '/cta/help-support': typeof CtaHelpSupportIndexLazyRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexLazyRoute
  '/settings/automations': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security': typeof SettingsSecurityIndexLazyRoute
  '/settings/workspace': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members': typeof TeamsMembersIndexLazyRoute
  '/teams/overview': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles': typeof TeamsRolesIndexLazyRoute
  '/user/$contactId': typeof UserContactIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/shared': typeof SharedRouteLazyRouteWithChildren
  '/teams': typeof TeamsRouteLazyRouteWithChildren
  '/cta/': typeof CtaIndexLazyRoute
  '/favorites/': typeof FavoritesIndexLazyRoute
  '/groups/': typeof GroupsIndexLazyRoute
  '/import-export/': typeof ImportExportIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/recent/': typeof RecentIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/shared/': typeof SharedIndexLazyRoute
  '/teams/': typeof TeamsIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexLazyRoute
  '/settings/automations/': typeof SettingsAutomationsIndexLazyRoute
  '/settings/billing/': typeof SettingsBillingIndexLazyRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexLazyRoute
  '/settings/security/': typeof SettingsSecurityIndexLazyRoute
  '/settings/workspace/': typeof SettingsWorkspaceIndexLazyRoute
  '/shared/shared-by-me/': typeof SharedSharedByMeIndexLazyRoute
  '/shared/shared-with-me/': typeof SharedSharedWithMeIndexLazyRoute
  '/teams/members/': typeof TeamsMembersIndexLazyRoute
  '/teams/overview/': typeof TeamsOverviewIndexLazyRoute
  '/teams/permissions/': typeof TeamsPermissionsIndexLazyRoute
  '/teams/roles/': typeof TeamsRolesIndexLazyRoute
  '/user/$contactId/': typeof UserContactIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/cta/'
    | '/favorites/'
    | '/groups/'
    | '/import-export/'
    | '/notifications/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/teams/'
    | '/cta/help-support/'
    | '/groups/$groupId/'
    | '/settings/automations/'
    | '/settings/billing/'
    | '/settings/integrations/'
    | '/settings/security/'
    | '/settings/workspace/'
    | '/shared/shared-by-me/'
    | '/shared/shared-with-me/'
    | '/teams/members/'
    | '/teams/overview/'
    | '/teams/permissions/'
    | '/teams/roles/'
    | '/user/$contactId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cta'
    | '/favorites'
    | '/groups'
    | '/import-export'
    | '/notifications'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/cta/help-support'
    | '/groups/$groupId'
    | '/settings/automations'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/security'
    | '/settings/workspace'
    | '/shared/shared-by-me'
    | '/shared/shared-with-me'
    | '/teams/members'
    | '/teams/overview'
    | '/teams/permissions'
    | '/teams/roles'
    | '/user/$contactId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/shared'
    | '/teams'
    | '/cta/'
    | '/favorites/'
    | '/groups/'
    | '/import-export/'
    | '/notifications/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/teams/'
    | '/cta/help-support/'
    | '/groups/$groupId/'
    | '/settings/automations/'
    | '/settings/billing/'
    | '/settings/integrations/'
    | '/settings/security/'
    | '/settings/workspace/'
    | '/shared/shared-by-me/'
    | '/shared/shared-with-me/'
    | '/teams/members/'
    | '/teams/overview/'
    | '/teams/permissions/'
    | '/teams/roles/'
    | '/user/$contactId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  SharedRouteLazyRoute: typeof SharedRouteLazyRouteWithChildren
  TeamsRouteLazyRoute: typeof TeamsRouteLazyRouteWithChildren
  CtaIndexLazyRoute: typeof CtaIndexLazyRoute
  FavoritesIndexLazyRoute: typeof FavoritesIndexLazyRoute
  GroupsIndexLazyRoute: typeof GroupsIndexLazyRoute
  ImportExportIndexLazyRoute: typeof ImportExportIndexLazyRoute
  NotificationsIndexLazyRoute: typeof NotificationsIndexLazyRoute
  RecentIndexLazyRoute: typeof RecentIndexLazyRoute
  CtaHelpSupportIndexLazyRoute: typeof CtaHelpSupportIndexLazyRoute
  GroupsGroupIdIndexLazyRoute: typeof GroupsGroupIdIndexLazyRoute
  UserContactIdIndexLazyRoute: typeof UserContactIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/shared/': {
      id: '/shared/'
      path: '/'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/recent/': {
      id: '/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof RecentIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export/': {
      id: '/import-export/'
      path: '/import-export'
      fullPath: '/import-export/'
      preLoaderRoute: typeof ImportExportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cta/': {
      id: '/cta/'
      path: '/cta'
      fullPath: '/cta/'
      preLoaderRoute: typeof CtaIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$contactId/': {
      id: '/user/$contactId/'
      path: '/user/$contactId'
      fullPath: '/user/$contactId/'
      preLoaderRoute: typeof UserContactIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/roles/': {
      id: '/teams/roles/'
      path: '/roles'
      fullPath: '/teams/roles/'
      preLoaderRoute: typeof TeamsRolesIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/permissions/': {
      id: '/teams/permissions/'
      path: '/permissions'
      fullPath: '/teams/permissions/'
      preLoaderRoute: typeof TeamsPermissionsIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/overview/': {
      id: '/teams/overview/'
      path: '/overview'
      fullPath: '/teams/overview/'
      preLoaderRoute: typeof TeamsOverviewIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/teams/members/': {
      id: '/teams/members/'
      path: '/members'
      fullPath: '/teams/members/'
      preLoaderRoute: typeof TeamsMembersIndexLazyRouteImport
      parentRoute: typeof TeamsRouteLazyRoute
    }
    '/shared/shared-with-me/': {
      id: '/shared/shared-with-me/'
      path: '/shared-with-me'
      fullPath: '/shared/shared-with-me/'
      preLoaderRoute: typeof SharedSharedWithMeIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/shared/shared-by-me/': {
      id: '/shared/shared-by-me/'
      path: '/shared-by-me'
      fullPath: '/shared/shared-by-me/'
      preLoaderRoute: typeof SharedSharedByMeIndexLazyRouteImport
      parentRoute: typeof SharedRouteLazyRoute
    }
    '/settings/workspace/': {
      id: '/settings/workspace/'
      path: '/workspace'
      fullPath: '/settings/workspace/'
      preLoaderRoute: typeof SettingsWorkspaceIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/security/': {
      id: '/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof SettingsSecurityIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/integrations/': {
      id: '/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof SettingsIntegrationsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/billing/': {
      id: '/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof SettingsBillingIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/automations/': {
      id: '/settings/automations/'
      path: '/automations'
      fullPath: '/settings/automations/'
      preLoaderRoute: typeof SettingsAutomationsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cta/help-support/': {
      id: '/cta/help-support/'
      path: '/cta/help-support'
      fullPath: '/cta/help-support/'
      preLoaderRoute: typeof CtaHelpSupportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteLazyRouteChildren {
  SettingsIndexLazyRoute: typeof SettingsIndexLazyRoute
  SettingsAutomationsIndexLazyRoute: typeof SettingsAutomationsIndexLazyRoute
  SettingsBillingIndexLazyRoute: typeof SettingsBillingIndexLazyRoute
  SettingsIntegrationsIndexLazyRoute: typeof SettingsIntegrationsIndexLazyRoute
  SettingsSecurityIndexLazyRoute: typeof SettingsSecurityIndexLazyRoute
  SettingsWorkspaceIndexLazyRoute: typeof SettingsWorkspaceIndexLazyRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsIndexLazyRoute: SettingsIndexLazyRoute,
  SettingsAutomationsIndexLazyRoute: SettingsAutomationsIndexLazyRoute,
  SettingsBillingIndexLazyRoute: SettingsBillingIndexLazyRoute,
  SettingsIntegrationsIndexLazyRoute: SettingsIntegrationsIndexLazyRoute,
  SettingsSecurityIndexLazyRoute: SettingsSecurityIndexLazyRoute,
  SettingsWorkspaceIndexLazyRoute: SettingsWorkspaceIndexLazyRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

interface SharedRouteLazyRouteChildren {
  SharedIndexLazyRoute: typeof SharedIndexLazyRoute
  SharedSharedByMeIndexLazyRoute: typeof SharedSharedByMeIndexLazyRoute
  SharedSharedWithMeIndexLazyRoute: typeof SharedSharedWithMeIndexLazyRoute
}

const SharedRouteLazyRouteChildren: SharedRouteLazyRouteChildren = {
  SharedIndexLazyRoute: SharedIndexLazyRoute,
  SharedSharedByMeIndexLazyRoute: SharedSharedByMeIndexLazyRoute,
  SharedSharedWithMeIndexLazyRoute: SharedSharedWithMeIndexLazyRoute,
}

const SharedRouteLazyRouteWithChildren = SharedRouteLazyRoute._addFileChildren(
  SharedRouteLazyRouteChildren,
)

interface TeamsRouteLazyRouteChildren {
  TeamsIndexLazyRoute: typeof TeamsIndexLazyRoute
  TeamsMembersIndexLazyRoute: typeof TeamsMembersIndexLazyRoute
  TeamsOverviewIndexLazyRoute: typeof TeamsOverviewIndexLazyRoute
  TeamsPermissionsIndexLazyRoute: typeof TeamsPermissionsIndexLazyRoute
  TeamsRolesIndexLazyRoute: typeof TeamsRolesIndexLazyRoute
}

const TeamsRouteLazyRouteChildren: TeamsRouteLazyRouteChildren = {
  TeamsIndexLazyRoute: TeamsIndexLazyRoute,
  TeamsMembersIndexLazyRoute: TeamsMembersIndexLazyRoute,
  TeamsOverviewIndexLazyRoute: TeamsOverviewIndexLazyRoute,
  TeamsPermissionsIndexLazyRoute: TeamsPermissionsIndexLazyRoute,
  TeamsRolesIndexLazyRoute: TeamsRolesIndexLazyRoute,
}

const TeamsRouteLazyRouteWithChildren = TeamsRouteLazyRoute._addFileChildren(
  TeamsRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  SharedRouteLazyRoute: SharedRouteLazyRouteWithChildren,
  TeamsRouteLazyRoute: TeamsRouteLazyRouteWithChildren,
  CtaIndexLazyRoute: CtaIndexLazyRoute,
  FavoritesIndexLazyRoute: FavoritesIndexLazyRoute,
  GroupsIndexLazyRoute: GroupsIndexLazyRoute,
  ImportExportIndexLazyRoute: ImportExportIndexLazyRoute,
  NotificationsIndexLazyRoute: NotificationsIndexLazyRoute,
  RecentIndexLazyRoute: RecentIndexLazyRoute,
  CtaHelpSupportIndexLazyRoute: CtaHelpSupportIndexLazyRoute,
  GroupsGroupIdIndexLazyRoute: GroupsGroupIdIndexLazyRoute,
  UserContactIdIndexLazyRoute: UserContactIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
