/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const Settings1RouteLazyRouteImport = createFileRoute('/settings1')()
const SettingsRouteLazyRouteImport = createFileRoute('/settings')()
const ReportsRouteLazyRouteImport = createFileRoute('/reports')()
const InventoryRouteLazyRouteImport = createFileRoute('/inventory')()
const BooksRouteLazyRouteImport = createFileRoute('/books')()
const BankRouteLazyRouteImport = createFileRoute('/bank')()
const IndexLazyRouteImport = createFileRoute('/')()
const Settings1IndexLazyRouteImport = createFileRoute('/settings1/')()
const SettingsIndexLazyRouteImport = createFileRoute('/settings/')()
const ReportsIndexLazyRouteImport = createFileRoute('/reports/')()
const NotificationsIndexLazyRouteImport = createFileRoute('/notifications/')()
const InventoryIndexLazyRouteImport = createFileRoute('/inventory/')()
const CtaIndexLazyRouteImport = createFileRoute('/cta/')()
const ChatIndexLazyRouteImport = createFileRoute('/chat/')()
const BooksIndexLazyRouteImport = createFileRoute('/books/')()
const BankIndexLazyRouteImport = createFileRoute('/bank/')()
const ReportsSalesRouteLazyRouteImport = createFileRoute('/reports/sales')()
const ReportsPurchaseRouteLazyRouteImport =
  createFileRoute('/reports/purchase')()
const ReportsInventoryRouteLazyRouteImport =
  createFileRoute('/reports/inventory')()
const Settings1WorkspaceIndexLazyRouteImport = createFileRoute(
  '/settings1/workspace/',
)()
const Settings1SecurityIndexLazyRouteImport = createFileRoute(
  '/settings1/security/',
)()
const Settings1IntegrationsIndexLazyRouteImport = createFileRoute(
  '/settings1/integrations/',
)()
const Settings1BillingIndexLazyRouteImport = createFileRoute(
  '/settings1/billing/',
)()
const Settings1AutomationsIndexLazyRouteImport = createFileRoute(
  '/settings1/automations/',
)()
const SettingsTeamIndexLazyRouteImport = createFileRoute('/settings/team/')()
const SettingsNotificationsIndexLazyRouteImport = createFileRoute(
  '/settings/notifications/',
)()
const SettingsCompanyIndexLazyRouteImport =
  createFileRoute('/settings/company/')()
const SettingsAccountIndexLazyRouteImport =
  createFileRoute('/settings/account/')()
const ReportsSalesIndexLazyRouteImport = createFileRoute('/reports/sales/')()
const ReportsPurchaseIndexLazyRouteImport =
  createFileRoute('/reports/purchase/')()
const ReportsProfitLossIndexLazyRouteImport = createFileRoute(
  '/reports/profit-loss/',
)()
const ReportsOverviewIndexLazyRouteImport =
  createFileRoute('/reports/overview/')()
const ReportsInventoryIndexLazyRouteImport = createFileRoute(
  '/reports/inventory/',
)()
const ReportsChartOfAccountsIndexLazyRouteImport = createFileRoute(
  '/reports/chart-of-accounts/',
)()
const ReportsCashflowIndexLazyRouteImport =
  createFileRoute('/reports/cashflow/')()
const ReportsBalanceSheetIndexLazyRouteImport = createFileRoute(
  '/reports/balance-sheet/',
)()
const CtaHelpSupportIndexLazyRouteImport =
  createFileRoute('/cta/help-support/')()
const BooksSalesIndexLazyRouteImport = createFileRoute('/books/sales/')()
const BooksPurchaseIndexLazyRouteImport = createFileRoute('/books/purchase/')()
const BooksOverviewIndexLazyRouteImport = createFileRoute('/books/overview/')()
const BankOverviewIndexLazyRouteImport = createFileRoute('/bank/overview/')()
const BankAccountsIndexLazyRouteImport = createFileRoute('/bank/accounts/')()
const SettingsIntegrationsIndeLazyRouteImport = createFileRoute(
  '/settings/integrations/inde',
)()
const BankAccountsAccountsIdRouteLazyRouteImport = createFileRoute(
  '/bank/accounts/$accountsId',
)()
const ReportsSalesSalesReportIndexLazyRouteImport = createFileRoute(
  '/reports/sales/sales-report/',
)()
const ReportsSalesSalesRegisterIndexLazyRouteImport = createFileRoute(
  '/reports/sales/sales-register/',
)()
const ReportsSalesItemwiseReportIndexLazyRouteImport = createFileRoute(
  '/reports/sales/itemwise-report/',
)()
const ReportsSalesCustomerReportIndexLazyRouteImport = createFileRoute(
  '/reports/sales/customer-report/',
)()
const ReportsPurchaseSupplierReportsIndexLazyRouteImport = createFileRoute(
  '/reports/purchase/supplier-reports/',
)()
const ReportsPurchasePurchaserReportsIndexLazyRouteImport = createFileRoute(
  '/reports/purchase/purchaser-reports/',
)()
const ReportsPurchasePurchaseReportsIndexLazyRouteImport = createFileRoute(
  '/reports/purchase/purchase-reports/',
)()
const ReportsPurchaseItemwiseReportsIndexLazyRouteImport = createFileRoute(
  '/reports/purchase/itemwise-reports/',
)()
const ReportsInventoryItemwiseReportsIndexLazyRouteImport = createFileRoute(
  '/reports/inventory/itemwise-reports/',
)()
const ReportsInventoryItemssoldReportsIndexLazyRouteImport = createFileRoute(
  '/reports/inventory/itemssold-reports/',
)()
const ReportsInventoryItempurchaseReportsIndexLazyRouteImport = createFileRoute(
  '/reports/inventory/itempurchase-reports/',
)()
const BankAccountsAccountsIdIndexLazyRouteImport = createFileRoute(
  '/bank/accounts/$accountsId/',
)()
const BankAccountsAccountsIdTransactionsIndexLazyRouteImport = createFileRoute(
  '/bank/accounts/$accountsId/transactions/',
)()
const BankAccountsAccountsIdReconcilationIndexLazyRouteImport = createFileRoute(
  '/bank/accounts/$accountsId/reconcilation/',
)()
const BankAccountsAccountsIdOverviewIndexLazyRouteImport = createFileRoute(
  '/bank/accounts/$accountsId/overview/',
)()

const Settings1RouteLazyRoute = Settings1RouteLazyRouteImport.update({
  id: '/settings1',
  path: '/settings1',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings1/route.lazy').then((d) => d.Route),
)
const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const ReportsRouteLazyRoute = ReportsRouteLazyRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports/route.lazy').then((d) => d.Route))
const InventoryRouteLazyRoute = InventoryRouteLazyRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inventory/route.lazy').then((d) => d.Route),
)
const BooksRouteLazyRoute = BooksRouteLazyRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/books/route.lazy').then((d) => d.Route))
const BankRouteLazyRoute = BankRouteLazyRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bank/route.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const Settings1IndexLazyRoute = Settings1IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Settings1RouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings1/index.lazy').then((d) => d.Route),
)
const SettingsIndexLazyRoute = SettingsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/index.lazy').then((d) => d.Route),
)
const ReportsIndexLazyRoute = ReportsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRouteLazyRoute,
} as any).lazy(() => import('./routes/reports/index.lazy').then((d) => d.Route))
const NotificationsIndexLazyRoute = NotificationsIndexLazyRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/notifications/index.lazy').then((d) => d.Route),
)
const InventoryIndexLazyRoute = InventoryIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/inventory/index.lazy').then((d) => d.Route),
)
const CtaIndexLazyRoute = CtaIndexLazyRouteImport.update({
  id: '/cta/',
  path: '/cta/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cta/index.lazy').then((d) => d.Route))
const ChatIndexLazyRoute = ChatIndexLazyRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat/index.lazy').then((d) => d.Route))
const BooksIndexLazyRoute = BooksIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRouteLazyRoute,
} as any).lazy(() => import('./routes/books/index.lazy').then((d) => d.Route))
const BankIndexLazyRoute = BankIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BankRouteLazyRoute,
} as any).lazy(() => import('./routes/bank/index.lazy').then((d) => d.Route))
const ReportsSalesRouteLazyRoute = ReportsSalesRouteLazyRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/reports/sales/route.lazy').then((d) => d.Route),
)
const ReportsPurchaseRouteLazyRoute =
  ReportsPurchaseRouteLazyRouteImport.update({
    id: '/purchase',
    path: '/purchase',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/route.lazy').then((d) => d.Route),
  )
const ReportsInventoryRouteLazyRoute =
  ReportsInventoryRouteLazyRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/inventory/route.lazy').then((d) => d.Route),
  )
const Settings1WorkspaceIndexLazyRoute =
  Settings1WorkspaceIndexLazyRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => Settings1RouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings1/workspace/index.lazy').then((d) => d.Route),
  )
const Settings1SecurityIndexLazyRoute =
  Settings1SecurityIndexLazyRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => Settings1RouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings1/security/index.lazy').then((d) => d.Route),
  )
const Settings1IntegrationsIndexLazyRoute =
  Settings1IntegrationsIndexLazyRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => Settings1RouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings1/integrations/index.lazy').then((d) => d.Route),
  )
const Settings1BillingIndexLazyRoute =
  Settings1BillingIndexLazyRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => Settings1RouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings1/billing/index.lazy').then((d) => d.Route),
  )
const Settings1AutomationsIndexLazyRoute =
  Settings1AutomationsIndexLazyRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => Settings1RouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings1/automations/index.lazy').then((d) => d.Route),
  )
const SettingsTeamIndexLazyRoute = SettingsTeamIndexLazyRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/team/index.lazy').then((d) => d.Route),
)
const SettingsNotificationsIndexLazyRoute =
  SettingsNotificationsIndexLazyRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications/index.lazy').then((d) => d.Route),
  )
const SettingsCompanyIndexLazyRoute =
  SettingsCompanyIndexLazyRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/company/index.lazy').then((d) => d.Route),
  )
const SettingsAccountIndexLazyRoute =
  SettingsAccountIndexLazyRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/account/index.lazy').then((d) => d.Route),
  )
const ReportsSalesIndexLazyRoute = ReportsSalesIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsSalesRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/reports/sales/index.lazy').then((d) => d.Route),
)
const ReportsPurchaseIndexLazyRoute =
  ReportsPurchaseIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReportsPurchaseRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/index.lazy').then((d) => d.Route),
  )
const ReportsProfitLossIndexLazyRoute =
  ReportsProfitLossIndexLazyRouteImport.update({
    id: '/profit-loss/',
    path: '/profit-loss/',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/profit-loss/index.lazy').then((d) => d.Route),
  )
const ReportsOverviewIndexLazyRoute =
  ReportsOverviewIndexLazyRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/overview/index.lazy').then((d) => d.Route),
  )
const ReportsInventoryIndexLazyRoute =
  ReportsInventoryIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReportsInventoryRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/inventory/index.lazy').then((d) => d.Route),
  )
const ReportsChartOfAccountsIndexLazyRoute =
  ReportsChartOfAccountsIndexLazyRouteImport.update({
    id: '/chart-of-accounts/',
    path: '/chart-of-accounts/',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/chart-of-accounts/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsCashflowIndexLazyRoute =
  ReportsCashflowIndexLazyRouteImport.update({
    id: '/cashflow/',
    path: '/cashflow/',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/cashflow/index.lazy').then((d) => d.Route),
  )
const ReportsBalanceSheetIndexLazyRoute =
  ReportsBalanceSheetIndexLazyRouteImport.update({
    id: '/balance-sheet/',
    path: '/balance-sheet/',
    getParentRoute: () => ReportsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/balance-sheet/index.lazy').then((d) => d.Route),
  )
const CtaHelpSupportIndexLazyRoute = CtaHelpSupportIndexLazyRouteImport.update({
  id: '/cta/help-support/',
  path: '/cta/help-support/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/cta/help-support/index.lazy').then((d) => d.Route),
)
const BooksSalesIndexLazyRoute = BooksSalesIndexLazyRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => BooksRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/books/sales/index.lazy').then((d) => d.Route),
)
const BooksPurchaseIndexLazyRoute = BooksPurchaseIndexLazyRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => BooksRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/books/purchase/index.lazy').then((d) => d.Route),
)
const BooksOverviewIndexLazyRoute = BooksOverviewIndexLazyRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => BooksRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/books/overview/index.lazy').then((d) => d.Route),
)
const BankOverviewIndexLazyRoute = BankOverviewIndexLazyRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => BankRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/bank/overview/index.lazy').then((d) => d.Route),
)
const BankAccountsIndexLazyRoute = BankAccountsIndexLazyRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => BankRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/bank/accounts/index.lazy').then((d) => d.Route),
)
const SettingsIntegrationsIndeLazyRoute =
  SettingsIntegrationsIndeLazyRouteImport.update({
    id: '/integrations/inde',
    path: '/integrations/inde',
    getParentRoute: () => SettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/settings/integrations/inde.lazy').then((d) => d.Route),
  )
const BankAccountsAccountsIdRouteLazyRoute =
  BankAccountsAccountsIdRouteLazyRouteImport.update({
    id: '/accounts/$accountsId',
    path: '/accounts/$accountsId',
    getParentRoute: () => BankRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/bank/accounts/$accountsId/route.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsSalesSalesReportIndexLazyRoute =
  ReportsSalesSalesReportIndexLazyRouteImport.update({
    id: '/sales-report/',
    path: '/sales-report/',
    getParentRoute: () => ReportsSalesRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/sales/sales-report/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsSalesSalesRegisterIndexLazyRoute =
  ReportsSalesSalesRegisterIndexLazyRouteImport.update({
    id: '/sales-register/',
    path: '/sales-register/',
    getParentRoute: () => ReportsSalesRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/sales/sales-register/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsSalesItemwiseReportIndexLazyRoute =
  ReportsSalesItemwiseReportIndexLazyRouteImport.update({
    id: '/itemwise-report/',
    path: '/itemwise-report/',
    getParentRoute: () => ReportsSalesRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/sales/itemwise-report/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsSalesCustomerReportIndexLazyRoute =
  ReportsSalesCustomerReportIndexLazyRouteImport.update({
    id: '/customer-report/',
    path: '/customer-report/',
    getParentRoute: () => ReportsSalesRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/sales/customer-report/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsPurchaseSupplierReportsIndexLazyRoute =
  ReportsPurchaseSupplierReportsIndexLazyRouteImport.update({
    id: '/supplier-reports/',
    path: '/supplier-reports/',
    getParentRoute: () => ReportsPurchaseRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/supplier-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsPurchasePurchaserReportsIndexLazyRoute =
  ReportsPurchasePurchaserReportsIndexLazyRouteImport.update({
    id: '/purchaser-reports/',
    path: '/purchaser-reports/',
    getParentRoute: () => ReportsPurchaseRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/purchaser-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsPurchasePurchaseReportsIndexLazyRoute =
  ReportsPurchasePurchaseReportsIndexLazyRouteImport.update({
    id: '/purchase-reports/',
    path: '/purchase-reports/',
    getParentRoute: () => ReportsPurchaseRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/purchase-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsPurchaseItemwiseReportsIndexLazyRoute =
  ReportsPurchaseItemwiseReportsIndexLazyRouteImport.update({
    id: '/itemwise-reports/',
    path: '/itemwise-reports/',
    getParentRoute: () => ReportsPurchaseRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/purchase/itemwise-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsInventoryItemwiseReportsIndexLazyRoute =
  ReportsInventoryItemwiseReportsIndexLazyRouteImport.update({
    id: '/itemwise-reports/',
    path: '/itemwise-reports/',
    getParentRoute: () => ReportsInventoryRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/inventory/itemwise-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsInventoryItemssoldReportsIndexLazyRoute =
  ReportsInventoryItemssoldReportsIndexLazyRouteImport.update({
    id: '/itemssold-reports/',
    path: '/itemssold-reports/',
    getParentRoute: () => ReportsInventoryRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/inventory/itemssold-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ReportsInventoryItempurchaseReportsIndexLazyRoute =
  ReportsInventoryItempurchaseReportsIndexLazyRouteImport.update({
    id: '/itempurchase-reports/',
    path: '/itempurchase-reports/',
    getParentRoute: () => ReportsInventoryRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/reports/inventory/itempurchase-reports/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BankAccountsAccountsIdIndexLazyRoute =
  BankAccountsAccountsIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BankAccountsAccountsIdRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/bank/accounts/$accountsId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BankAccountsAccountsIdTransactionsIndexLazyRoute =
  BankAccountsAccountsIdTransactionsIndexLazyRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => BankAccountsAccountsIdRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/bank/accounts/$accountsId/transactions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BankAccountsAccountsIdReconcilationIndexLazyRoute =
  BankAccountsAccountsIdReconcilationIndexLazyRouteImport.update({
    id: '/reconcilation/',
    path: '/reconcilation/',
    getParentRoute: () => BankAccountsAccountsIdRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/bank/accounts/$accountsId/reconcilation/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BankAccountsAccountsIdOverviewIndexLazyRoute =
  BankAccountsAccountsIdOverviewIndexLazyRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => BankAccountsAccountsIdRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/bank/accounts/$accountsId/overview/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/bank': typeof BankRouteLazyRouteWithChildren
  '/books': typeof BooksRouteLazyRouteWithChildren
  '/inventory': typeof InventoryRouteLazyRouteWithChildren
  '/reports': typeof ReportsRouteLazyRouteWithChildren
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/settings1': typeof Settings1RouteLazyRouteWithChildren
  '/reports/inventory': typeof ReportsInventoryRouteLazyRouteWithChildren
  '/reports/purchase': typeof ReportsPurchaseRouteLazyRouteWithChildren
  '/reports/sales': typeof ReportsSalesRouteLazyRouteWithChildren
  '/bank/': typeof BankIndexLazyRoute
  '/books/': typeof BooksIndexLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
  '/cta/': typeof CtaIndexLazyRoute
  '/inventory/': typeof InventoryIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/reports/': typeof ReportsIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/settings1/': typeof Settings1IndexLazyRoute
  '/bank/accounts/$accountsId': typeof BankAccountsAccountsIdRouteLazyRouteWithChildren
  '/settings/integrations/inde': typeof SettingsIntegrationsIndeLazyRoute
  '/bank/accounts/': typeof BankAccountsIndexLazyRoute
  '/bank/overview/': typeof BankOverviewIndexLazyRoute
  '/books/overview/': typeof BooksOverviewIndexLazyRoute
  '/books/purchase/': typeof BooksPurchaseIndexLazyRoute
  '/books/sales/': typeof BooksSalesIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/reports/balance-sheet/': typeof ReportsBalanceSheetIndexLazyRoute
  '/reports/cashflow/': typeof ReportsCashflowIndexLazyRoute
  '/reports/chart-of-accounts/': typeof ReportsChartOfAccountsIndexLazyRoute
  '/reports/inventory/': typeof ReportsInventoryIndexLazyRoute
  '/reports/overview/': typeof ReportsOverviewIndexLazyRoute
  '/reports/profit-loss/': typeof ReportsProfitLossIndexLazyRoute
  '/reports/purchase/': typeof ReportsPurchaseIndexLazyRoute
  '/reports/sales/': typeof ReportsSalesIndexLazyRoute
  '/settings/account/': typeof SettingsAccountIndexLazyRoute
  '/settings/company/': typeof SettingsCompanyIndexLazyRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexLazyRoute
  '/settings/team/': typeof SettingsTeamIndexLazyRoute
  '/settings1/automations/': typeof Settings1AutomationsIndexLazyRoute
  '/settings1/billing/': typeof Settings1BillingIndexLazyRoute
  '/settings1/integrations/': typeof Settings1IntegrationsIndexLazyRoute
  '/settings1/security/': typeof Settings1SecurityIndexLazyRoute
  '/settings1/workspace/': typeof Settings1WorkspaceIndexLazyRoute
  '/bank/accounts/$accountsId/': typeof BankAccountsAccountsIdIndexLazyRoute
  '/reports/inventory/itempurchase-reports/': typeof ReportsInventoryItempurchaseReportsIndexLazyRoute
  '/reports/inventory/itemssold-reports/': typeof ReportsInventoryItemssoldReportsIndexLazyRoute
  '/reports/inventory/itemwise-reports/': typeof ReportsInventoryItemwiseReportsIndexLazyRoute
  '/reports/purchase/itemwise-reports/': typeof ReportsPurchaseItemwiseReportsIndexLazyRoute
  '/reports/purchase/purchase-reports/': typeof ReportsPurchasePurchaseReportsIndexLazyRoute
  '/reports/purchase/purchaser-reports/': typeof ReportsPurchasePurchaserReportsIndexLazyRoute
  '/reports/purchase/supplier-reports/': typeof ReportsPurchaseSupplierReportsIndexLazyRoute
  '/reports/sales/customer-report/': typeof ReportsSalesCustomerReportIndexLazyRoute
  '/reports/sales/itemwise-report/': typeof ReportsSalesItemwiseReportIndexLazyRoute
  '/reports/sales/sales-register/': typeof ReportsSalesSalesRegisterIndexLazyRoute
  '/reports/sales/sales-report/': typeof ReportsSalesSalesReportIndexLazyRoute
  '/bank/accounts/$accountsId/overview/': typeof BankAccountsAccountsIdOverviewIndexLazyRoute
  '/bank/accounts/$accountsId/reconcilation/': typeof BankAccountsAccountsIdReconcilationIndexLazyRoute
  '/bank/accounts/$accountsId/transactions/': typeof BankAccountsAccountsIdTransactionsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/bank': typeof BankIndexLazyRoute
  '/books': typeof BooksIndexLazyRoute
  '/chat': typeof ChatIndexLazyRoute
  '/cta': typeof CtaIndexLazyRoute
  '/inventory': typeof InventoryIndexLazyRoute
  '/notifications': typeof NotificationsIndexLazyRoute
  '/reports': typeof ReportsIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
  '/settings1': typeof Settings1IndexLazyRoute
  '/settings/integrations/inde': typeof SettingsIntegrationsIndeLazyRoute
  '/bank/accounts': typeof BankAccountsIndexLazyRoute
  '/bank/overview': typeof BankOverviewIndexLazyRoute
  '/books/overview': typeof BooksOverviewIndexLazyRoute
  '/books/purchase': typeof BooksPurchaseIndexLazyRoute
  '/books/sales': typeof BooksSalesIndexLazyRoute
  '/cta/help-support': typeof CtaHelpSupportIndexLazyRoute
  '/reports/balance-sheet': typeof ReportsBalanceSheetIndexLazyRoute
  '/reports/cashflow': typeof ReportsCashflowIndexLazyRoute
  '/reports/chart-of-accounts': typeof ReportsChartOfAccountsIndexLazyRoute
  '/reports/inventory': typeof ReportsInventoryIndexLazyRoute
  '/reports/overview': typeof ReportsOverviewIndexLazyRoute
  '/reports/profit-loss': typeof ReportsProfitLossIndexLazyRoute
  '/reports/purchase': typeof ReportsPurchaseIndexLazyRoute
  '/reports/sales': typeof ReportsSalesIndexLazyRoute
  '/settings/account': typeof SettingsAccountIndexLazyRoute
  '/settings/company': typeof SettingsCompanyIndexLazyRoute
  '/settings/notifications': typeof SettingsNotificationsIndexLazyRoute
  '/settings/team': typeof SettingsTeamIndexLazyRoute
  '/settings1/automations': typeof Settings1AutomationsIndexLazyRoute
  '/settings1/billing': typeof Settings1BillingIndexLazyRoute
  '/settings1/integrations': typeof Settings1IntegrationsIndexLazyRoute
  '/settings1/security': typeof Settings1SecurityIndexLazyRoute
  '/settings1/workspace': typeof Settings1WorkspaceIndexLazyRoute
  '/bank/accounts/$accountsId': typeof BankAccountsAccountsIdIndexLazyRoute
  '/reports/inventory/itempurchase-reports': typeof ReportsInventoryItempurchaseReportsIndexLazyRoute
  '/reports/inventory/itemssold-reports': typeof ReportsInventoryItemssoldReportsIndexLazyRoute
  '/reports/inventory/itemwise-reports': typeof ReportsInventoryItemwiseReportsIndexLazyRoute
  '/reports/purchase/itemwise-reports': typeof ReportsPurchaseItemwiseReportsIndexLazyRoute
  '/reports/purchase/purchase-reports': typeof ReportsPurchasePurchaseReportsIndexLazyRoute
  '/reports/purchase/purchaser-reports': typeof ReportsPurchasePurchaserReportsIndexLazyRoute
  '/reports/purchase/supplier-reports': typeof ReportsPurchaseSupplierReportsIndexLazyRoute
  '/reports/sales/customer-report': typeof ReportsSalesCustomerReportIndexLazyRoute
  '/reports/sales/itemwise-report': typeof ReportsSalesItemwiseReportIndexLazyRoute
  '/reports/sales/sales-register': typeof ReportsSalesSalesRegisterIndexLazyRoute
  '/reports/sales/sales-report': typeof ReportsSalesSalesReportIndexLazyRoute
  '/bank/accounts/$accountsId/overview': typeof BankAccountsAccountsIdOverviewIndexLazyRoute
  '/bank/accounts/$accountsId/reconcilation': typeof BankAccountsAccountsIdReconcilationIndexLazyRoute
  '/bank/accounts/$accountsId/transactions': typeof BankAccountsAccountsIdTransactionsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/bank': typeof BankRouteLazyRouteWithChildren
  '/books': typeof BooksRouteLazyRouteWithChildren
  '/inventory': typeof InventoryRouteLazyRouteWithChildren
  '/reports': typeof ReportsRouteLazyRouteWithChildren
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/settings1': typeof Settings1RouteLazyRouteWithChildren
  '/reports/inventory': typeof ReportsInventoryRouteLazyRouteWithChildren
  '/reports/purchase': typeof ReportsPurchaseRouteLazyRouteWithChildren
  '/reports/sales': typeof ReportsSalesRouteLazyRouteWithChildren
  '/bank/': typeof BankIndexLazyRoute
  '/books/': typeof BooksIndexLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
  '/cta/': typeof CtaIndexLazyRoute
  '/inventory/': typeof InventoryIndexLazyRoute
  '/notifications/': typeof NotificationsIndexLazyRoute
  '/reports/': typeof ReportsIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
  '/settings1/': typeof Settings1IndexLazyRoute
  '/bank/accounts/$accountsId': typeof BankAccountsAccountsIdRouteLazyRouteWithChildren
  '/settings/integrations/inde': typeof SettingsIntegrationsIndeLazyRoute
  '/bank/accounts/': typeof BankAccountsIndexLazyRoute
  '/bank/overview/': typeof BankOverviewIndexLazyRoute
  '/books/overview/': typeof BooksOverviewIndexLazyRoute
  '/books/purchase/': typeof BooksPurchaseIndexLazyRoute
  '/books/sales/': typeof BooksSalesIndexLazyRoute
  '/cta/help-support/': typeof CtaHelpSupportIndexLazyRoute
  '/reports/balance-sheet/': typeof ReportsBalanceSheetIndexLazyRoute
  '/reports/cashflow/': typeof ReportsCashflowIndexLazyRoute
  '/reports/chart-of-accounts/': typeof ReportsChartOfAccountsIndexLazyRoute
  '/reports/inventory/': typeof ReportsInventoryIndexLazyRoute
  '/reports/overview/': typeof ReportsOverviewIndexLazyRoute
  '/reports/profit-loss/': typeof ReportsProfitLossIndexLazyRoute
  '/reports/purchase/': typeof ReportsPurchaseIndexLazyRoute
  '/reports/sales/': typeof ReportsSalesIndexLazyRoute
  '/settings/account/': typeof SettingsAccountIndexLazyRoute
  '/settings/company/': typeof SettingsCompanyIndexLazyRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexLazyRoute
  '/settings/team/': typeof SettingsTeamIndexLazyRoute
  '/settings1/automations/': typeof Settings1AutomationsIndexLazyRoute
  '/settings1/billing/': typeof Settings1BillingIndexLazyRoute
  '/settings1/integrations/': typeof Settings1IntegrationsIndexLazyRoute
  '/settings1/security/': typeof Settings1SecurityIndexLazyRoute
  '/settings1/workspace/': typeof Settings1WorkspaceIndexLazyRoute
  '/bank/accounts/$accountsId/': typeof BankAccountsAccountsIdIndexLazyRoute
  '/reports/inventory/itempurchase-reports/': typeof ReportsInventoryItempurchaseReportsIndexLazyRoute
  '/reports/inventory/itemssold-reports/': typeof ReportsInventoryItemssoldReportsIndexLazyRoute
  '/reports/inventory/itemwise-reports/': typeof ReportsInventoryItemwiseReportsIndexLazyRoute
  '/reports/purchase/itemwise-reports/': typeof ReportsPurchaseItemwiseReportsIndexLazyRoute
  '/reports/purchase/purchase-reports/': typeof ReportsPurchasePurchaseReportsIndexLazyRoute
  '/reports/purchase/purchaser-reports/': typeof ReportsPurchasePurchaserReportsIndexLazyRoute
  '/reports/purchase/supplier-reports/': typeof ReportsPurchaseSupplierReportsIndexLazyRoute
  '/reports/sales/customer-report/': typeof ReportsSalesCustomerReportIndexLazyRoute
  '/reports/sales/itemwise-report/': typeof ReportsSalesItemwiseReportIndexLazyRoute
  '/reports/sales/sales-register/': typeof ReportsSalesSalesRegisterIndexLazyRoute
  '/reports/sales/sales-report/': typeof ReportsSalesSalesReportIndexLazyRoute
  '/bank/accounts/$accountsId/overview/': typeof BankAccountsAccountsIdOverviewIndexLazyRoute
  '/bank/accounts/$accountsId/reconcilation/': typeof BankAccountsAccountsIdReconcilationIndexLazyRoute
  '/bank/accounts/$accountsId/transactions/': typeof BankAccountsAccountsIdTransactionsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/books'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/settings1'
    | '/reports/inventory'
    | '/reports/purchase'
    | '/reports/sales'
    | '/bank/'
    | '/books/'
    | '/chat/'
    | '/cta/'
    | '/inventory/'
    | '/notifications/'
    | '/reports/'
    | '/settings/'
    | '/settings1/'
    | '/bank/accounts/$accountsId'
    | '/settings/integrations/inde'
    | '/bank/accounts/'
    | '/bank/overview/'
    | '/books/overview/'
    | '/books/purchase/'
    | '/books/sales/'
    | '/cta/help-support/'
    | '/reports/balance-sheet/'
    | '/reports/cashflow/'
    | '/reports/chart-of-accounts/'
    | '/reports/inventory/'
    | '/reports/overview/'
    | '/reports/profit-loss/'
    | '/reports/purchase/'
    | '/reports/sales/'
    | '/settings/account/'
    | '/settings/company/'
    | '/settings/notifications/'
    | '/settings/team/'
    | '/settings1/automations/'
    | '/settings1/billing/'
    | '/settings1/integrations/'
    | '/settings1/security/'
    | '/settings1/workspace/'
    | '/bank/accounts/$accountsId/'
    | '/reports/inventory/itempurchase-reports/'
    | '/reports/inventory/itemssold-reports/'
    | '/reports/inventory/itemwise-reports/'
    | '/reports/purchase/itemwise-reports/'
    | '/reports/purchase/purchase-reports/'
    | '/reports/purchase/purchaser-reports/'
    | '/reports/purchase/supplier-reports/'
    | '/reports/sales/customer-report/'
    | '/reports/sales/itemwise-report/'
    | '/reports/sales/sales-register/'
    | '/reports/sales/sales-report/'
    | '/bank/accounts/$accountsId/overview/'
    | '/bank/accounts/$accountsId/reconcilation/'
    | '/bank/accounts/$accountsId/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/books'
    | '/chat'
    | '/cta'
    | '/inventory'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/settings1'
    | '/settings/integrations/inde'
    | '/bank/accounts'
    | '/bank/overview'
    | '/books/overview'
    | '/books/purchase'
    | '/books/sales'
    | '/cta/help-support'
    | '/reports/balance-sheet'
    | '/reports/cashflow'
    | '/reports/chart-of-accounts'
    | '/reports/inventory'
    | '/reports/overview'
    | '/reports/profit-loss'
    | '/reports/purchase'
    | '/reports/sales'
    | '/settings/account'
    | '/settings/company'
    | '/settings/notifications'
    | '/settings/team'
    | '/settings1/automations'
    | '/settings1/billing'
    | '/settings1/integrations'
    | '/settings1/security'
    | '/settings1/workspace'
    | '/bank/accounts/$accountsId'
    | '/reports/inventory/itempurchase-reports'
    | '/reports/inventory/itemssold-reports'
    | '/reports/inventory/itemwise-reports'
    | '/reports/purchase/itemwise-reports'
    | '/reports/purchase/purchase-reports'
    | '/reports/purchase/purchaser-reports'
    | '/reports/purchase/supplier-reports'
    | '/reports/sales/customer-report'
    | '/reports/sales/itemwise-report'
    | '/reports/sales/sales-register'
    | '/reports/sales/sales-report'
    | '/bank/accounts/$accountsId/overview'
    | '/bank/accounts/$accountsId/reconcilation'
    | '/bank/accounts/$accountsId/transactions'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/books'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/settings1'
    | '/reports/inventory'
    | '/reports/purchase'
    | '/reports/sales'
    | '/bank/'
    | '/books/'
    | '/chat/'
    | '/cta/'
    | '/inventory/'
    | '/notifications/'
    | '/reports/'
    | '/settings/'
    | '/settings1/'
    | '/bank/accounts/$accountsId'
    | '/settings/integrations/inde'
    | '/bank/accounts/'
    | '/bank/overview/'
    | '/books/overview/'
    | '/books/purchase/'
    | '/books/sales/'
    | '/cta/help-support/'
    | '/reports/balance-sheet/'
    | '/reports/cashflow/'
    | '/reports/chart-of-accounts/'
    | '/reports/inventory/'
    | '/reports/overview/'
    | '/reports/profit-loss/'
    | '/reports/purchase/'
    | '/reports/sales/'
    | '/settings/account/'
    | '/settings/company/'
    | '/settings/notifications/'
    | '/settings/team/'
    | '/settings1/automations/'
    | '/settings1/billing/'
    | '/settings1/integrations/'
    | '/settings1/security/'
    | '/settings1/workspace/'
    | '/bank/accounts/$accountsId/'
    | '/reports/inventory/itempurchase-reports/'
    | '/reports/inventory/itemssold-reports/'
    | '/reports/inventory/itemwise-reports/'
    | '/reports/purchase/itemwise-reports/'
    | '/reports/purchase/purchase-reports/'
    | '/reports/purchase/purchaser-reports/'
    | '/reports/purchase/supplier-reports/'
    | '/reports/sales/customer-report/'
    | '/reports/sales/itemwise-report/'
    | '/reports/sales/sales-register/'
    | '/reports/sales/sales-report/'
    | '/bank/accounts/$accountsId/overview/'
    | '/bank/accounts/$accountsId/reconcilation/'
    | '/bank/accounts/$accountsId/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BankRouteLazyRoute: typeof BankRouteLazyRouteWithChildren
  BooksRouteLazyRoute: typeof BooksRouteLazyRouteWithChildren
  InventoryRouteLazyRoute: typeof InventoryRouteLazyRouteWithChildren
  ReportsRouteLazyRoute: typeof ReportsRouteLazyRouteWithChildren
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  Settings1RouteLazyRoute: typeof Settings1RouteLazyRouteWithChildren
  ChatIndexLazyRoute: typeof ChatIndexLazyRoute
  CtaIndexLazyRoute: typeof CtaIndexLazyRoute
  NotificationsIndexLazyRoute: typeof NotificationsIndexLazyRoute
  CtaHelpSupportIndexLazyRoute: typeof CtaHelpSupportIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings1': {
      id: '/settings1'
      path: '/settings1'
      fullPath: '/settings1'
      preLoaderRoute: typeof Settings1RouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings1/': {
      id: '/settings1/'
      path: '/'
      fullPath: '/settings1/'
      preLoaderRoute: typeof Settings1IndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexLazyRouteImport
      parentRoute: typeof InventoryRouteLazyRoute
    }
    '/cta/': {
      id: '/cta/'
      path: '/cta'
      fullPath: '/cta/'
      preLoaderRoute: typeof CtaIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexLazyRouteImport
      parentRoute: typeof BooksRouteLazyRoute
    }
    '/bank/': {
      id: '/bank/'
      path: '/'
      fullPath: '/bank/'
      preLoaderRoute: typeof BankIndexLazyRouteImport
      parentRoute: typeof BankRouteLazyRoute
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/purchase': {
      id: '/reports/purchase'
      path: '/purchase'
      fullPath: '/reports/purchase'
      preLoaderRoute: typeof ReportsPurchaseRouteLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/settings1/workspace/': {
      id: '/settings1/workspace/'
      path: '/workspace'
      fullPath: '/settings1/workspace/'
      preLoaderRoute: typeof Settings1WorkspaceIndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings1/security/': {
      id: '/settings1/security/'
      path: '/security'
      fullPath: '/settings1/security/'
      preLoaderRoute: typeof Settings1SecurityIndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings1/integrations/': {
      id: '/settings1/integrations/'
      path: '/integrations'
      fullPath: '/settings1/integrations/'
      preLoaderRoute: typeof Settings1IntegrationsIndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings1/billing/': {
      id: '/settings1/billing/'
      path: '/billing'
      fullPath: '/settings1/billing/'
      preLoaderRoute: typeof Settings1BillingIndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings1/automations/': {
      id: '/settings1/automations/'
      path: '/automations'
      fullPath: '/settings1/automations/'
      preLoaderRoute: typeof Settings1AutomationsIndexLazyRouteImport
      parentRoute: typeof Settings1RouteLazyRoute
    }
    '/settings/team/': {
      id: '/settings/team/'
      path: '/team'
      fullPath: '/settings/team/'
      preLoaderRoute: typeof SettingsTeamIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof SettingsNotificationsIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/company/': {
      id: '/settings/company/'
      path: '/company'
      fullPath: '/settings/company/'
      preLoaderRoute: typeof SettingsCompanyIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/account/': {
      id: '/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof SettingsAccountIndexLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/reports/sales/': {
      id: '/reports/sales/'
      path: '/'
      fullPath: '/reports/sales/'
      preLoaderRoute: typeof ReportsSalesIndexLazyRouteImport
      parentRoute: typeof ReportsSalesRouteLazyRoute
    }
    '/reports/purchase/': {
      id: '/reports/purchase/'
      path: '/'
      fullPath: '/reports/purchase/'
      preLoaderRoute: typeof ReportsPurchaseIndexLazyRouteImport
      parentRoute: typeof ReportsPurchaseRouteLazyRoute
    }
    '/reports/profit-loss/': {
      id: '/reports/profit-loss/'
      path: '/profit-loss'
      fullPath: '/reports/profit-loss/'
      preLoaderRoute: typeof ReportsProfitLossIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/overview/': {
      id: '/reports/overview/'
      path: '/overview'
      fullPath: '/reports/overview/'
      preLoaderRoute: typeof ReportsOverviewIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/inventory/': {
      id: '/reports/inventory/'
      path: '/'
      fullPath: '/reports/inventory/'
      preLoaderRoute: typeof ReportsInventoryIndexLazyRouteImport
      parentRoute: typeof ReportsInventoryRouteLazyRoute
    }
    '/reports/chart-of-accounts/': {
      id: '/reports/chart-of-accounts/'
      path: '/chart-of-accounts'
      fullPath: '/reports/chart-of-accounts/'
      preLoaderRoute: typeof ReportsChartOfAccountsIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/cashflow/': {
      id: '/reports/cashflow/'
      path: '/cashflow'
      fullPath: '/reports/cashflow/'
      preLoaderRoute: typeof ReportsCashflowIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/reports/balance-sheet/': {
      id: '/reports/balance-sheet/'
      path: '/balance-sheet'
      fullPath: '/reports/balance-sheet/'
      preLoaderRoute: typeof ReportsBalanceSheetIndexLazyRouteImport
      parentRoute: typeof ReportsRouteLazyRoute
    }
    '/cta/help-support/': {
      id: '/cta/help-support/'
      path: '/cta/help-support'
      fullPath: '/cta/help-support/'
      preLoaderRoute: typeof CtaHelpSupportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/sales/': {
      id: '/books/sales/'
      path: '/sales'
      fullPath: '/books/sales/'
      preLoaderRoute: typeof BooksSalesIndexLazyRouteImport
      parentRoute: typeof BooksRouteLazyRoute
    }
    '/books/purchase/': {
      id: '/books/purchase/'
      path: '/purchase'
      fullPath: '/books/purchase/'
      preLoaderRoute: typeof BooksPurchaseIndexLazyRouteImport
      parentRoute: typeof BooksRouteLazyRoute
    }
    '/books/overview/': {
      id: '/books/overview/'
      path: '/overview'
      fullPath: '/books/overview/'
      preLoaderRoute: typeof BooksOverviewIndexLazyRouteImport
      parentRoute: typeof BooksRouteLazyRoute
    }
    '/bank/overview/': {
      id: '/bank/overview/'
      path: '/overview'
      fullPath: '/bank/overview/'
      preLoaderRoute: typeof BankOverviewIndexLazyRouteImport
      parentRoute: typeof BankRouteLazyRoute
    }
    '/bank/accounts/': {
      id: '/bank/accounts/'
      path: '/accounts'
      fullPath: '/bank/accounts/'
      preLoaderRoute: typeof BankAccountsIndexLazyRouteImport
      parentRoute: typeof BankRouteLazyRoute
    }
    '/settings/integrations/inde': {
      id: '/settings/integrations/inde'
      path: '/integrations/inde'
      fullPath: '/settings/integrations/inde'
      preLoaderRoute: typeof SettingsIntegrationsIndeLazyRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/bank/accounts/$accountsId': {
      id: '/bank/accounts/$accountsId'
      path: '/accounts/$accountsId'
      fullPath: '/bank/accounts/$accountsId'
      preLoaderRoute: typeof BankAccountsAccountsIdRouteLazyRouteImport
      parentRoute: typeof BankRouteLazyRoute
    }
    '/reports/sales/sales-report/': {
      id: '/reports/sales/sales-report/'
      path: '/sales-report'
      fullPath: '/reports/sales/sales-report/'
      preLoaderRoute: typeof ReportsSalesSalesReportIndexLazyRouteImport
      parentRoute: typeof ReportsSalesRouteLazyRoute
    }
    '/reports/sales/sales-register/': {
      id: '/reports/sales/sales-register/'
      path: '/sales-register'
      fullPath: '/reports/sales/sales-register/'
      preLoaderRoute: typeof ReportsSalesSalesRegisterIndexLazyRouteImport
      parentRoute: typeof ReportsSalesRouteLazyRoute
    }
    '/reports/sales/itemwise-report/': {
      id: '/reports/sales/itemwise-report/'
      path: '/itemwise-report'
      fullPath: '/reports/sales/itemwise-report/'
      preLoaderRoute: typeof ReportsSalesItemwiseReportIndexLazyRouteImport
      parentRoute: typeof ReportsSalesRouteLazyRoute
    }
    '/reports/sales/customer-report/': {
      id: '/reports/sales/customer-report/'
      path: '/customer-report'
      fullPath: '/reports/sales/customer-report/'
      preLoaderRoute: typeof ReportsSalesCustomerReportIndexLazyRouteImport
      parentRoute: typeof ReportsSalesRouteLazyRoute
    }
    '/reports/purchase/supplier-reports/': {
      id: '/reports/purchase/supplier-reports/'
      path: '/supplier-reports'
      fullPath: '/reports/purchase/supplier-reports/'
      preLoaderRoute: typeof ReportsPurchaseSupplierReportsIndexLazyRouteImport
      parentRoute: typeof ReportsPurchaseRouteLazyRoute
    }
    '/reports/purchase/purchaser-reports/': {
      id: '/reports/purchase/purchaser-reports/'
      path: '/purchaser-reports'
      fullPath: '/reports/purchase/purchaser-reports/'
      preLoaderRoute: typeof ReportsPurchasePurchaserReportsIndexLazyRouteImport
      parentRoute: typeof ReportsPurchaseRouteLazyRoute
    }
    '/reports/purchase/purchase-reports/': {
      id: '/reports/purchase/purchase-reports/'
      path: '/purchase-reports'
      fullPath: '/reports/purchase/purchase-reports/'
      preLoaderRoute: typeof ReportsPurchasePurchaseReportsIndexLazyRouteImport
      parentRoute: typeof ReportsPurchaseRouteLazyRoute
    }
    '/reports/purchase/itemwise-reports/': {
      id: '/reports/purchase/itemwise-reports/'
      path: '/itemwise-reports'
      fullPath: '/reports/purchase/itemwise-reports/'
      preLoaderRoute: typeof ReportsPurchaseItemwiseReportsIndexLazyRouteImport
      parentRoute: typeof ReportsPurchaseRouteLazyRoute
    }
    '/reports/inventory/itemwise-reports/': {
      id: '/reports/inventory/itemwise-reports/'
      path: '/itemwise-reports'
      fullPath: '/reports/inventory/itemwise-reports/'
      preLoaderRoute: typeof ReportsInventoryItemwiseReportsIndexLazyRouteImport
      parentRoute: typeof ReportsInventoryRouteLazyRoute
    }
    '/reports/inventory/itemssold-reports/': {
      id: '/reports/inventory/itemssold-reports/'
      path: '/itemssold-reports'
      fullPath: '/reports/inventory/itemssold-reports/'
      preLoaderRoute: typeof ReportsInventoryItemssoldReportsIndexLazyRouteImport
      parentRoute: typeof ReportsInventoryRouteLazyRoute
    }
    '/reports/inventory/itempurchase-reports/': {
      id: '/reports/inventory/itempurchase-reports/'
      path: '/itempurchase-reports'
      fullPath: '/reports/inventory/itempurchase-reports/'
      preLoaderRoute: typeof ReportsInventoryItempurchaseReportsIndexLazyRouteImport
      parentRoute: typeof ReportsInventoryRouteLazyRoute
    }
    '/bank/accounts/$accountsId/': {
      id: '/bank/accounts/$accountsId/'
      path: '/'
      fullPath: '/bank/accounts/$accountsId/'
      preLoaderRoute: typeof BankAccountsAccountsIdIndexLazyRouteImport
      parentRoute: typeof BankAccountsAccountsIdRouteLazyRoute
    }
    '/bank/accounts/$accountsId/transactions/': {
      id: '/bank/accounts/$accountsId/transactions/'
      path: '/transactions'
      fullPath: '/bank/accounts/$accountsId/transactions/'
      preLoaderRoute: typeof BankAccountsAccountsIdTransactionsIndexLazyRouteImport
      parentRoute: typeof BankAccountsAccountsIdRouteLazyRoute
    }
    '/bank/accounts/$accountsId/reconcilation/': {
      id: '/bank/accounts/$accountsId/reconcilation/'
      path: '/reconcilation'
      fullPath: '/bank/accounts/$accountsId/reconcilation/'
      preLoaderRoute: typeof BankAccountsAccountsIdReconcilationIndexLazyRouteImport
      parentRoute: typeof BankAccountsAccountsIdRouteLazyRoute
    }
    '/bank/accounts/$accountsId/overview/': {
      id: '/bank/accounts/$accountsId/overview/'
      path: '/overview'
      fullPath: '/bank/accounts/$accountsId/overview/'
      preLoaderRoute: typeof BankAccountsAccountsIdOverviewIndexLazyRouteImport
      parentRoute: typeof BankAccountsAccountsIdRouteLazyRoute
    }
  }
}

interface BankAccountsAccountsIdRouteLazyRouteChildren {
  BankAccountsAccountsIdIndexLazyRoute: typeof BankAccountsAccountsIdIndexLazyRoute
  BankAccountsAccountsIdOverviewIndexLazyRoute: typeof BankAccountsAccountsIdOverviewIndexLazyRoute
  BankAccountsAccountsIdReconcilationIndexLazyRoute: typeof BankAccountsAccountsIdReconcilationIndexLazyRoute
  BankAccountsAccountsIdTransactionsIndexLazyRoute: typeof BankAccountsAccountsIdTransactionsIndexLazyRoute
}

const BankAccountsAccountsIdRouteLazyRouteChildren: BankAccountsAccountsIdRouteLazyRouteChildren =
  {
    BankAccountsAccountsIdIndexLazyRoute: BankAccountsAccountsIdIndexLazyRoute,
    BankAccountsAccountsIdOverviewIndexLazyRoute:
      BankAccountsAccountsIdOverviewIndexLazyRoute,
    BankAccountsAccountsIdReconcilationIndexLazyRoute:
      BankAccountsAccountsIdReconcilationIndexLazyRoute,
    BankAccountsAccountsIdTransactionsIndexLazyRoute:
      BankAccountsAccountsIdTransactionsIndexLazyRoute,
  }

const BankAccountsAccountsIdRouteLazyRouteWithChildren =
  BankAccountsAccountsIdRouteLazyRoute._addFileChildren(
    BankAccountsAccountsIdRouteLazyRouteChildren,
  )

interface BankRouteLazyRouteChildren {
  BankIndexLazyRoute: typeof BankIndexLazyRoute
  BankAccountsAccountsIdRouteLazyRoute: typeof BankAccountsAccountsIdRouteLazyRouteWithChildren
  BankAccountsIndexLazyRoute: typeof BankAccountsIndexLazyRoute
  BankOverviewIndexLazyRoute: typeof BankOverviewIndexLazyRoute
}

const BankRouteLazyRouteChildren: BankRouteLazyRouteChildren = {
  BankIndexLazyRoute: BankIndexLazyRoute,
  BankAccountsAccountsIdRouteLazyRoute:
    BankAccountsAccountsIdRouteLazyRouteWithChildren,
  BankAccountsIndexLazyRoute: BankAccountsIndexLazyRoute,
  BankOverviewIndexLazyRoute: BankOverviewIndexLazyRoute,
}

const BankRouteLazyRouteWithChildren = BankRouteLazyRoute._addFileChildren(
  BankRouteLazyRouteChildren,
)

interface BooksRouteLazyRouteChildren {
  BooksIndexLazyRoute: typeof BooksIndexLazyRoute
  BooksOverviewIndexLazyRoute: typeof BooksOverviewIndexLazyRoute
  BooksPurchaseIndexLazyRoute: typeof BooksPurchaseIndexLazyRoute
  BooksSalesIndexLazyRoute: typeof BooksSalesIndexLazyRoute
}

const BooksRouteLazyRouteChildren: BooksRouteLazyRouteChildren = {
  BooksIndexLazyRoute: BooksIndexLazyRoute,
  BooksOverviewIndexLazyRoute: BooksOverviewIndexLazyRoute,
  BooksPurchaseIndexLazyRoute: BooksPurchaseIndexLazyRoute,
  BooksSalesIndexLazyRoute: BooksSalesIndexLazyRoute,
}

const BooksRouteLazyRouteWithChildren = BooksRouteLazyRoute._addFileChildren(
  BooksRouteLazyRouteChildren,
)

interface InventoryRouteLazyRouteChildren {
  InventoryIndexLazyRoute: typeof InventoryIndexLazyRoute
}

const InventoryRouteLazyRouteChildren: InventoryRouteLazyRouteChildren = {
  InventoryIndexLazyRoute: InventoryIndexLazyRoute,
}

const InventoryRouteLazyRouteWithChildren =
  InventoryRouteLazyRoute._addFileChildren(InventoryRouteLazyRouteChildren)

interface ReportsInventoryRouteLazyRouteChildren {
  ReportsInventoryIndexLazyRoute: typeof ReportsInventoryIndexLazyRoute
  ReportsInventoryItempurchaseReportsIndexLazyRoute: typeof ReportsInventoryItempurchaseReportsIndexLazyRoute
  ReportsInventoryItemssoldReportsIndexLazyRoute: typeof ReportsInventoryItemssoldReportsIndexLazyRoute
  ReportsInventoryItemwiseReportsIndexLazyRoute: typeof ReportsInventoryItemwiseReportsIndexLazyRoute
}

const ReportsInventoryRouteLazyRouteChildren: ReportsInventoryRouteLazyRouteChildren =
  {
    ReportsInventoryIndexLazyRoute: ReportsInventoryIndexLazyRoute,
    ReportsInventoryItempurchaseReportsIndexLazyRoute:
      ReportsInventoryItempurchaseReportsIndexLazyRoute,
    ReportsInventoryItemssoldReportsIndexLazyRoute:
      ReportsInventoryItemssoldReportsIndexLazyRoute,
    ReportsInventoryItemwiseReportsIndexLazyRoute:
      ReportsInventoryItemwiseReportsIndexLazyRoute,
  }

const ReportsInventoryRouteLazyRouteWithChildren =
  ReportsInventoryRouteLazyRoute._addFileChildren(
    ReportsInventoryRouteLazyRouteChildren,
  )

interface ReportsPurchaseRouteLazyRouteChildren {
  ReportsPurchaseIndexLazyRoute: typeof ReportsPurchaseIndexLazyRoute
  ReportsPurchaseItemwiseReportsIndexLazyRoute: typeof ReportsPurchaseItemwiseReportsIndexLazyRoute
  ReportsPurchasePurchaseReportsIndexLazyRoute: typeof ReportsPurchasePurchaseReportsIndexLazyRoute
  ReportsPurchasePurchaserReportsIndexLazyRoute: typeof ReportsPurchasePurchaserReportsIndexLazyRoute
  ReportsPurchaseSupplierReportsIndexLazyRoute: typeof ReportsPurchaseSupplierReportsIndexLazyRoute
}

const ReportsPurchaseRouteLazyRouteChildren: ReportsPurchaseRouteLazyRouteChildren =
  {
    ReportsPurchaseIndexLazyRoute: ReportsPurchaseIndexLazyRoute,
    ReportsPurchaseItemwiseReportsIndexLazyRoute:
      ReportsPurchaseItemwiseReportsIndexLazyRoute,
    ReportsPurchasePurchaseReportsIndexLazyRoute:
      ReportsPurchasePurchaseReportsIndexLazyRoute,
    ReportsPurchasePurchaserReportsIndexLazyRoute:
      ReportsPurchasePurchaserReportsIndexLazyRoute,
    ReportsPurchaseSupplierReportsIndexLazyRoute:
      ReportsPurchaseSupplierReportsIndexLazyRoute,
  }

const ReportsPurchaseRouteLazyRouteWithChildren =
  ReportsPurchaseRouteLazyRoute._addFileChildren(
    ReportsPurchaseRouteLazyRouteChildren,
  )

interface ReportsSalesRouteLazyRouteChildren {
  ReportsSalesIndexLazyRoute: typeof ReportsSalesIndexLazyRoute
  ReportsSalesCustomerReportIndexLazyRoute: typeof ReportsSalesCustomerReportIndexLazyRoute
  ReportsSalesItemwiseReportIndexLazyRoute: typeof ReportsSalesItemwiseReportIndexLazyRoute
  ReportsSalesSalesRegisterIndexLazyRoute: typeof ReportsSalesSalesRegisterIndexLazyRoute
  ReportsSalesSalesReportIndexLazyRoute: typeof ReportsSalesSalesReportIndexLazyRoute
}

const ReportsSalesRouteLazyRouteChildren: ReportsSalesRouteLazyRouteChildren = {
  ReportsSalesIndexLazyRoute: ReportsSalesIndexLazyRoute,
  ReportsSalesCustomerReportIndexLazyRoute:
    ReportsSalesCustomerReportIndexLazyRoute,
  ReportsSalesItemwiseReportIndexLazyRoute:
    ReportsSalesItemwiseReportIndexLazyRoute,
  ReportsSalesSalesRegisterIndexLazyRoute:
    ReportsSalesSalesRegisterIndexLazyRoute,
  ReportsSalesSalesReportIndexLazyRoute: ReportsSalesSalesReportIndexLazyRoute,
}

const ReportsSalesRouteLazyRouteWithChildren =
  ReportsSalesRouteLazyRoute._addFileChildren(
    ReportsSalesRouteLazyRouteChildren,
  )

interface ReportsRouteLazyRouteChildren {
  ReportsInventoryRouteLazyRoute: typeof ReportsInventoryRouteLazyRouteWithChildren
  ReportsPurchaseRouteLazyRoute: typeof ReportsPurchaseRouteLazyRouteWithChildren
  ReportsSalesRouteLazyRoute: typeof ReportsSalesRouteLazyRouteWithChildren
  ReportsIndexLazyRoute: typeof ReportsIndexLazyRoute
  ReportsBalanceSheetIndexLazyRoute: typeof ReportsBalanceSheetIndexLazyRoute
  ReportsCashflowIndexLazyRoute: typeof ReportsCashflowIndexLazyRoute
  ReportsChartOfAccountsIndexLazyRoute: typeof ReportsChartOfAccountsIndexLazyRoute
  ReportsOverviewIndexLazyRoute: typeof ReportsOverviewIndexLazyRoute
  ReportsProfitLossIndexLazyRoute: typeof ReportsProfitLossIndexLazyRoute
}

const ReportsRouteLazyRouteChildren: ReportsRouteLazyRouteChildren = {
  ReportsInventoryRouteLazyRoute: ReportsInventoryRouteLazyRouteWithChildren,
  ReportsPurchaseRouteLazyRoute: ReportsPurchaseRouteLazyRouteWithChildren,
  ReportsSalesRouteLazyRoute: ReportsSalesRouteLazyRouteWithChildren,
  ReportsIndexLazyRoute: ReportsIndexLazyRoute,
  ReportsBalanceSheetIndexLazyRoute: ReportsBalanceSheetIndexLazyRoute,
  ReportsCashflowIndexLazyRoute: ReportsCashflowIndexLazyRoute,
  ReportsChartOfAccountsIndexLazyRoute: ReportsChartOfAccountsIndexLazyRoute,
  ReportsOverviewIndexLazyRoute: ReportsOverviewIndexLazyRoute,
  ReportsProfitLossIndexLazyRoute: ReportsProfitLossIndexLazyRoute,
}

const ReportsRouteLazyRouteWithChildren =
  ReportsRouteLazyRoute._addFileChildren(ReportsRouteLazyRouteChildren)

interface SettingsRouteLazyRouteChildren {
  SettingsIndexLazyRoute: typeof SettingsIndexLazyRoute
  SettingsIntegrationsIndeLazyRoute: typeof SettingsIntegrationsIndeLazyRoute
  SettingsAccountIndexLazyRoute: typeof SettingsAccountIndexLazyRoute
  SettingsCompanyIndexLazyRoute: typeof SettingsCompanyIndexLazyRoute
  SettingsNotificationsIndexLazyRoute: typeof SettingsNotificationsIndexLazyRoute
  SettingsTeamIndexLazyRoute: typeof SettingsTeamIndexLazyRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsIndexLazyRoute: SettingsIndexLazyRoute,
  SettingsIntegrationsIndeLazyRoute: SettingsIntegrationsIndeLazyRoute,
  SettingsAccountIndexLazyRoute: SettingsAccountIndexLazyRoute,
  SettingsCompanyIndexLazyRoute: SettingsCompanyIndexLazyRoute,
  SettingsNotificationsIndexLazyRoute: SettingsNotificationsIndexLazyRoute,
  SettingsTeamIndexLazyRoute: SettingsTeamIndexLazyRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

interface Settings1RouteLazyRouteChildren {
  Settings1IndexLazyRoute: typeof Settings1IndexLazyRoute
  Settings1AutomationsIndexLazyRoute: typeof Settings1AutomationsIndexLazyRoute
  Settings1BillingIndexLazyRoute: typeof Settings1BillingIndexLazyRoute
  Settings1IntegrationsIndexLazyRoute: typeof Settings1IntegrationsIndexLazyRoute
  Settings1SecurityIndexLazyRoute: typeof Settings1SecurityIndexLazyRoute
  Settings1WorkspaceIndexLazyRoute: typeof Settings1WorkspaceIndexLazyRoute
}

const Settings1RouteLazyRouteChildren: Settings1RouteLazyRouteChildren = {
  Settings1IndexLazyRoute: Settings1IndexLazyRoute,
  Settings1AutomationsIndexLazyRoute: Settings1AutomationsIndexLazyRoute,
  Settings1BillingIndexLazyRoute: Settings1BillingIndexLazyRoute,
  Settings1IntegrationsIndexLazyRoute: Settings1IntegrationsIndexLazyRoute,
  Settings1SecurityIndexLazyRoute: Settings1SecurityIndexLazyRoute,
  Settings1WorkspaceIndexLazyRoute: Settings1WorkspaceIndexLazyRoute,
}

const Settings1RouteLazyRouteWithChildren =
  Settings1RouteLazyRoute._addFileChildren(Settings1RouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BankRouteLazyRoute: BankRouteLazyRouteWithChildren,
  BooksRouteLazyRoute: BooksRouteLazyRouteWithChildren,
  InventoryRouteLazyRoute: InventoryRouteLazyRouteWithChildren,
  ReportsRouteLazyRoute: ReportsRouteLazyRouteWithChildren,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  Settings1RouteLazyRoute: Settings1RouteLazyRouteWithChildren,
  ChatIndexLazyRoute: ChatIndexLazyRoute,
  CtaIndexLazyRoute: CtaIndexLazyRoute,
  NotificationsIndexLazyRoute: NotificationsIndexLazyRoute,
  CtaHelpSupportIndexLazyRoute: CtaHelpSupportIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
