# @vx/INFO: @vx/ci - trigger
name: playground-app | bnd

on:
  workflow_dispatch:
  push:
    branches: [timeline, next, feat/*]
    paths:
      - '.github/workflows/playground-app.yml'
      - 'vx/handbooks/ci.md'
      # - 'packages/**'
      - 'apps_internals/playground-app/**'

jobs:
  run_if:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.filter.outputs.all }}
      deploy: ${{ steps.filter.outputs.deploy }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            all:
              - '.github/workflows/playground-app.yml'
              - 'vx/handbooks/ci.md'
            deploy:
              - 'apps_internals/playground-app/**'
              - 'packages/**'

  deploy:
    needs: run_if
    if: ${{ needs.run_if.outputs.all == 'true' || needs.run_if.outputs.deploy == 'true' }}
    name: playground-app | ${{ github.ref_name }}
    uses: vezham/vx-deployer/.github/workflows/playground-app.yml@timeline
    secrets: inherit
    with:
      CALLER: ${{ github.ref_name }}
